### Data Collection - Capture social media data from platforms (e.g., Twitter, Facebook, LinkedIn, YouTube) using APIs such as Twitter API v2, Facebook Graph API, and YouTube Data API, along with scraping and crawling techniques (e.g., BeautifulSoap, Selenium)

In [ ]:
import requests
URL = "https://news.ycombinator.com/ask"
r = requests.get(URL)
print(r.content)

b'<html lang="en" op="ask"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?Y6kWEjCA9NYsuD0e1zNN">\n        <link rel="icon" href="y18.svg">\n                <title>Ask | Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">\n        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.svg" width="18" height="18" style="border:1px white solid; display:block"></a></td>\n                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>\n                            <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <span class="topsel"><a href="ask">ask</a></span> | <a href="show">show</a> | <a href="jobs">jobs</a> | <a href="submit" rel="nofollow">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">\n                              <a href="login?goto=ask">login</a>\n                          </span></td>\n              </tr></table></td></tr>\n<tr id="pagespace" title="Ask" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0">\n            <tr class=\'athing submission\' id=\'43154065\'>\n      <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43154065\' href=\'vote?id=43154065&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43154065">Ask HN: What are you working on? (February 2025)</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43154065">203 points</span> by <a href="user?id=david927" class="hnuser">david927</a> <span class="age" title="2025-02-23T23:00:16 1740351616"><a href="item?id=43154065">23 hours ago</a></span> <span id="unv_43154065"></span> | <a href="item?id=43154065">719&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43164498\'>\n      <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43164498\' href=\'vote?id=43164498&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43164498">Ask HN: Former devs who can&#x27;t get a job, what did you end up doing for work?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43164498">20 points</span> by <a href="user?id=throw81398475" class="hnuser">throw81398475</a> <span class="age" title="2025-02-24T20:22:37 1740428557"><a href="item?id=43164498">7 hours ago</a></span> <span id="unv_43164498"></span> | <a href="item?id=43164498">2&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43166256\'>\n      <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43166256\' href=\'vote?id=43166256&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43166256">Ask HN: My father passed away. How do deal with the grief?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43166256">9 points</span> by <a href="user?id=gogo61" class="hnuser">gogo61</a> <span class="age" title="2025-02-24T23:37:25 1740440245"><a href="item?id=43166256">4 hours ago</a></span> <span id="unv_43166256"></span> | <a href="item?id=43166256">7&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43158402\'>\n      <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43158402\' href=\'vote?id=43158402&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43158402">Ask HN: Have you written or consumed OpenAPI Arazzo specification?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43158402">5 points</span> by <a href="user?id=sb13" class="hnuser">sb13</a> <span class="age" title="2025-02-24T11:41:47 1740397307"><a href="item?id=43158402">16 hours ago</a></span> <span id="unv_43158402"></span> | <a href="item?id=43158402">1&nbsp;comment</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43148408\'>\n      <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43148408\' href=\'vote?id=43148408&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43148408">Tell HN: Five random IndieWeb blog links on your terminal</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43148408">44 points</span> by <a href="user?id=susam" class="hnuser">susam</a> <span class="age" title="2025-02-23T10:55:47 1740308147"><a href="item?id=43148408">1 day ago</a></span> <span id="unv_43148408"></span> | <a href="item?id=43148408">11&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43141368\'>\n      <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43141368\' href=\'vote?id=43141368&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43141368">Ask HN: Is anyone still using Dreamweaver?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43141368">165 points</span> by <a href="user?id=gillytech" class="hnuser">gillytech</a> <span class="age" title="2025-02-22T17:59:27 1740247167"><a href="item?id=43141368">2 days ago</a></span> <span id="unv_43141368"></span> | <a href="item?id=43141368">171&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43149437\'>\n      <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43149437\' href=\'vote?id=43149437&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43149437">Navigating a Broken Dev Culture</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43149437">58 points</span> by <a href="user?id=lightserver" class="hnuser">lightserver</a> <span class="age" title="2025-02-23T14:27:18 1740320838"><a href="item?id=43149437">1 day ago</a></span> <span id="unv_43149437"></span> | <a href="item?id=43149437">33&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43138523\'>\n      <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43138523\' href=\'vote?id=43138523&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43138523">Ask HN: Do you practice lucid dreaming?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43138523">13 points</span> by <a href="user?id=raunometsa" class="hnuser">raunometsa</a> <span class="age" title="2025-02-22T12:45:26 1740228326"><a href="item?id=43138523">2 days ago</a></span> <span id="unv_43138523"></span> | <a href="item?id=43138523">23&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43122800\'>\n      <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43122800\' href=\'vote?id=43122800&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43122800">Ask HN: Tired of startups \xe2\x80\x93 want a normal job. Help</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43122800">95 points</span> by <a href="user?id=mertleee" class="hnuser">mertleee</a> <span class="age" title="2025-02-21T00:59:57 1740099597"><a href="item?id=43122800">4 days ago</a></span> <span id="unv_43122800"></span> | <a href="item?id=43122800">95&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43166405\'>\n      <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43166405\' href=\'vote?id=43166405&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43166405">Ask HN: What happened to all those metaverse projects from 2022?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43166405">6 points</span> by <a href="user?id=herval" class="hnuser">herval</a> <span class="age" title="2025-02-24T23:57:08 1740441428"><a href="item?id=43166405">4 hours ago</a></span> <span id="unv_43166405"></span> | <a href="item?id=43166405">4&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43138540\'>\n      <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43138540\' href=\'vote?id=43138540&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43138540">Ask HN: Are there online communities for single-owner run companies?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43138540">5 points</span> by <a href="user?id=indulona" class="hnuser">indulona</a> <span class="age" title="2025-02-22T12:47:53 1740228473"><a href="item?id=43138540">2 days ago</a></span> <span id="unv_43138540"></span> | <a href="item?id=43138540">2&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43087383\'>\n      <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43087383\' href=\'vote?id=43087383&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43087383">Ask HN: Can I really create a company around my open-source software?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43087383">73 points</span> by <a href="user?id=darkhorse13" class="hnuser">darkhorse13</a> <span class="age" title="2025-02-18T08:37:01 1739867821"><a href="item?id=43087383">4 days ago</a></span> <span id="unv_43087383"></span> | <a href="item?id=43087383">62&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43162490\'>\n      <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43162490\' href=\'vote?id=43162490&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43162490">Ask HN: Anyone building a non AI product&#x2F;startup?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43162490">5 points</span> by <a href="user?id=codegeek" class="hnuser">codegeek</a> <span class="age" title="2025-02-24T17:46:16 1740419176"><a href="item?id=43162490">10 hours ago</a></span> <span id="unv_43162490"></span> | <a href="item?id=43162490">4&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43132313\'>\n      <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43132313\' href=\'vote?id=43132313&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43132313">Ask HN: Why is Cursor IDE accessing all my env vars?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43132313">14 points</span> by <a href="user?id=iyn" class="hnuser">iyn</a> <span class="age" title="2025-02-21T20:07:29 1740168449"><a href="item?id=43132313">3 days ago</a></span> <span id="unv_43132313"></span> | <a href="item?id=43132313">25&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43084739\'>\n      <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43084739\' href=\'vote?id=43084739&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43084739">Ask HN: What fiction&#x2F;non-fiction book should everyone read on the topic of CS?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43084739">35 points</span> by <a href="user?id=Eavolution" class="hnuser">Eavolution</a> <span class="age" title="2025-02-18T00:40:33 1739839233"><a href="item?id=43084739">7 days ago</a></span> <span id="unv_43084739"></span> | <a href="item?id=43084739">25&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43146311\'>\n      <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43146311\' href=\'vote?id=43146311&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43146311">Ask HN: Advice for someone who stagnated in their career. Help</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43146311">10 points</span> by <a href="user?id=justonemore" class="hnuser">justonemore</a> <span class="age" title="2025-02-23T03:49:26 1740282566"><a href="item?id=43146311">2 days ago</a></span> <span id="unv_43146311"></span> | <a href="item?id=43146311">7&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43158741\'>\n      <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43158741\' href=\'vote?id=43158741&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43158741">Ask HN: Tips on how to find great technical recruiters to land the right job?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43158741">3 points</span> by <a href="user?id=Glimjaur" class="hnuser">Glimjaur</a> <span class="age" title="2025-02-24T12:27:57 1740400077"><a href="item?id=43158741">15 hours ago</a></span> <span id="unv_43158741"></span> | <a href="item?id=43158741">1&nbsp;comment</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43145225\'>\n      <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43145225\' href=\'vote?id=43145225&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43145225">Ask HN: Why is it taking so long to build computer controlling agents?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43145225">10 points</span> by <a href="user?id=louisfialho" class="hnuser">louisfialho</a> <span class="age" title="2025-02-23T01:19:39 1740273579"><a href="item?id=43145225">2 days ago</a></span> <span id="unv_43145225"></span> | <a href="item?id=43145225">22&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43137645\'>\n      <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43137645\' href=\'vote?id=43137645&amp;how=up&amp;goto=ask\'><div class=\'votearrow\' title=\'upvote\'></div></a></center></td><td class="title"><span class="titleline"><a href="item?id=43137645">Ask HN: Tips to make a pitch for &quot;acquihire of one&quot;?</a></span></td></tr><tr><td colspan="2"></td><td class="subtext"><span class="subline">\n          <span class="score" id="score_43137645">2 points</span> by <a href="user?id=rglullis" class="hnuser">rglullis</a> <span class="age" title="2025-02-22T10:00:30 1740218430"><a href="item?id=43137645">2 days ago</a></span> <span id="unv_43137645"></span> | <a href="item?id=43137645">3&nbsp;comments</a>        </span>\n              </td></tr>\n      <tr class="spacer" style="height:5px"></tr>\n                <tr class=\'athing submission\' id=\'43137496\'>\n      <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id=\'up_43137496\

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(r.content, 'html.parser')
#soup = BeautifulSoup(r.content, 'html5lib')
print(soup.prettify())

<html lang="en" op="ask">
 <head>
  <meta content="origin" name="referrer"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="news.css?Y6kWEjCA9NYsuD0e1zNN" rel="stylesheet" type="text/css"/>
  <link href="y18.svg" rel="icon"/>
  <title>
   Ask | Hacker News
  </title>
 </head>
 <body>
  <center>
   <table bgcolor="#f6f6ef" border="0" cellpadding="0" cellspacing="0" id="hnmain" width="85%">
    <tr>
     <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" style="padding:2px" width="100%">
       <tr>
        <td style="width:18px;padding-right:4px">
         <a href="https://news.ycombinator.com">
          <img height="18" src="y18.svg" style="border:1px white solid; display:block" width="18"/>
         </a>
        </td>
        <td style="line-height:12pt; height:10px;">
         <span class="pagetop">
          <b class="hnname">
           <a href="news">
            Hacker News
           </a>
          </b>
          <a href="newest">
           new
          </a>
          |
          <a href="front">
           past
          </a>
          |
          <a href="newcomments">
           comments
          </a>
          |
          <span class="topsel">
           <a href="ask">
            ask
           </a>
          </span>
          |
          <a href="show">
           show
          </a>
          |
          <a href="jobs">
           jobs
          </a>
          |
          <a href="submit" rel="nofollow">
           submit
          </a>
         </span>
        </td>
        <td style="text-align:right;padding-right:4px;">
         <span class="pagetop">
          <a href="login?goto=ask">
           login
          </a>
         </span>
        </td>
       </tr>
      </table>
     </td>
    </tr>
    <tr id="pagespace" style="height:10px" title="Ask">
    </tr>
    <tr>
     <td>
      <table border="0" cellpadding="0" cellspacing="0">
       <tr class="athing submission" id="43154065">
        <td align="right" class="title" valign="top">
         <span class="rank">
          1.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43154065&amp;how=up&amp;goto=ask" id="up_43154065">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43154065">
           Ask HN: What are you working on? (February 2025)
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43154065">
           203 points
          </span>
          by
          <a class="hnuser" href="user?id=david927">
           david927
          </a>
          <span class="age" title="2025-02-23T23:00:16 1740351616">
           <a href="item?id=43154065">
            23 hours ago
           </a>
          </span>
          <span id="unv_43154065">
          </span>
          |
          <a href="item?id=43154065">
           719 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43164498">
        <td align="right" class="title" valign="top">
         <span class="rank">
          2.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43164498&amp;how=up&amp;goto=ask" id="up_43164498">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43164498">
           Ask HN: Former devs who can't get a job, what did you end up doing for work?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43164498">
           20 points
          </span>
          by
          <a class="hnuser" href="user?id=throw81398475">
           throw81398475
          </a>
          <span class="age" title="2025-02-24T20:22:37 1740428557">
           <a href="item?id=43164498">
            7 hours ago
           </a>
          </span>
          <span id="unv_43164498">
          </span>
          |
          <a href="item?id=43164498">
           2 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43166256">
        <td align="right" class="title" valign="top">
         <span class="rank">
          3.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43166256&amp;how=up&amp;goto=ask" id="up_43166256">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43166256">
           Ask HN: My father passed away. How do deal with the grief?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43166256">
           9 points
          </span>
          by
          <a class="hnuser" href="user?id=gogo61">
           gogo61
          </a>
          <span class="age" title="2025-02-24T23:37:25 1740440245">
           <a href="item?id=43166256">
            4 hours ago
           </a>
          </span>
          <span id="unv_43166256">
          </span>
          |
          <a href="item?id=43166256">
           7 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43158402">
        <td align="right" class="title" valign="top">
         <span class="rank">
          4.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43158402&amp;how=up&amp;goto=ask" id="up_43158402">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43158402">
           Ask HN: Have you written or consumed OpenAPI Arazzo specification?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43158402">
           5 points
          </span>
          by
          <a class="hnuser" href="user?id=sb13">
           sb13
          </a>
          <span class="age" title="2025-02-24T11:41:47 1740397307">
           <a href="item?id=43158402">
            16 hours ago
           </a>
          </span>
          <span id="unv_43158402">
          </span>
          |
          <a href="item?id=43158402">
           1 comment
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43148408">
        <td align="right" class="title" valign="top">
         <span class="rank">
          5.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43148408&amp;how=up&amp;goto=ask" id="up_43148408">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43148408">
           Tell HN: Five random IndieWeb blog links on your terminal
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43148408">
           44 points
          </span>
          by
          <a class="hnuser" href="user?id=susam">
           susam
          </a>
          <span class="age" title="2025-02-23T10:55:47 1740308147">
           <a href="item?id=43148408">
            1 day ago
           </a>
          </span>
          <span id="unv_43148408">
          </span>
          |
          <a href="item?id=43148408">
           11 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43141368">
        <td align="right" class="title" valign="top">
         <span class="rank">
          6.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43141368&amp;how=up&amp;goto=ask" id="up_43141368">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43141368">
           Ask HN: Is anyone still using Dreamweaver?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43141368">
           165 points
          </span>
          by
          <a class="hnuser" href="user?id=gillytech">
           gillytech
          </a>
          <span class="age" title="2025-02-22T17:59:27 1740247167">
           <a href="item?id=43141368">
            2 days ago
           </a>
          </span>
          <span id="unv_43141368">
          </span>
          |
          <a href="item?id=43141368">
           171 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43149437">
        <td align="right" class="title" valign="top">
         <span class="rank">
          7.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43149437&amp;how=up&amp;goto=ask" id="up_43149437">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43149437">
           Navigating a Broken Dev Culture
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43149437">
           58 points
          </span>
          by
          <a class="hnuser" href="user?id=lightserver">
           lightserver
          </a>
          <span class="age" title="2025-02-23T14:27:18 1740320838">
           <a href="item?id=43149437">
            1 day ago
           </a>
          </span>
          <span id="unv_43149437">
          </span>
          |
          <a href="item?id=43149437">
           33 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43138523">
        <td align="right" class="title" valign="top">
         <span class="rank">
          8.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43138523&amp;how=up&amp;goto=ask" id="up_43138523">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43138523">
           Ask HN: Do you practice lucid dreaming?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43138523">
           13 points
          </span>
          by
          <a class="hnuser" href="user?id=raunometsa">
           raunometsa
          </a>
          <span class="age" title="2025-02-22T12:45:26 1740228326">
           <a href="item?id=43138523">
            2 days ago
           </a>
          </span>
          <span id="unv_43138523">
          </span>
          |
          <a href="item?id=43138523">
           23 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43122800">
        <td align="right" class="title" valign="top">
         <span class="rank">
          9.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43122800&amp;how=up&amp;goto=ask" id="up_43122800">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43122800">
           Ask HN: Tired of startups â€“ want a normal job. Help
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43122800">
           95 points
          </span>
          by
          <a class="hnuser" href="user?id=mertleee">
           mertleee
          </a>
          <span class="age" title="2025-02-21T00:59:57 1740099597">
           <a href="item?id=43122800">
            4 days ago
           </a>
          </span>
          <span id="unv_43122800">
          </span>
          |
          <a href="item?id=43122800">
           95 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43166405">
        <td align="right" class="title" valign="top">
         <span class="rank">
          10.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43166405&amp;how=up&amp;goto=ask" id="up_43166405">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43166405">
           Ask HN: What happened to all those metaverse projects from 2022?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43166405">
           6 points
          </span>
          by
          <a class="hnuser" href="user?id=herval">
           herval
          </a>
          <span class="age" title="2025-02-24T23:57:08 1740441428">
           <a href="item?id=43166405">
            4 hours ago
           </a>
          </span>
          <span id="unv_43166405">
          </span>
          |
          <a href="item?id=43166405">
           4 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43138540">
        <td align="right" class="title" valign="top">
         <span class="rank">
          11.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43138540&amp;how=up&amp;goto=ask" id="up_43138540">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43138540">
           Ask HN: Are there online communities for single-owner run companies?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43138540">
           5 points
          </span>
          by
          <a class="hnuser" href="user?id=indulona">
           indulona
          </a>
          <span class="age" title="2025-02-22T12:47:53 1740228473">
           <a href="item?id=43138540">
            2 days ago
           </a>
          </span>
          <span id="unv_43138540">
          </span>
          |
          <a href="item?id=43138540">
           2 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43087383">
        <td align="right" class="title" valign="top">
         <span class="rank">
          12.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43087383&amp;how=up&amp;goto=ask" id="up_43087383">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43087383">
           Ask HN: Can I really create a company around my open-source software?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43087383">
           73 points
          </span>
          by
          <a class="hnuser" href="user?id=darkhorse13">
           darkhorse13
          </a>
          <span class="age" title="2025-02-18T08:37:01 1739867821">
           <a href="item?id=43087383">
            4 days ago
           </a>
          </span>
          <span id="unv_43087383">
          </span>
          |
          <a href="item?id=43087383">
           62 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43162490">
        <td align="right" class="title" valign="top">
         <span class="rank">
          13.
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=43162490&amp;how=up&amp;goto=ask" id="up_43162490">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=43162490">
           Ask HN: Anyone building a non AI product/startup?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_43162490">
           5 points
          </span>
          by
          <a class="hnuser" href="user?id=codegeek">
           codegeek
          </a>
          <span class="age" title="2025-02-24T17:46:16 1740419176">
           <a href="item?id=43162490">
            10 hours ago
           </a>
          </span>
          <span id="unv_43162490">
          </span>
          |
          <a href="item?id=43162490">
           4 comments
          </a>
         </span>
        </td>
       </tr>
       <tr class="spacer" style="height:5px">
       </tr>
       <tr class="athing submission" id="43132313">
        <td align="right" class="title" valign="top">
         <span class="rank">
          14.
         </span>
        </td>

In [ ]:
data_str = ""
for item in soup.find_all("td", class_="title"):
	data_str = data_str + item.get_text()

print(data_str)

1.Ask HN: What are you working on? (February 2025)2.Ask HN: Former devs who can't get a job, what did you end up doing for work?3.Ask HN: My father passed away. How do deal with the grief?4.Ask HN: Have you written or consumed OpenAPI Arazzo specification?5.Tell HN: Five random IndieWeb blog links on your terminal6.Ask HN: Is anyone still using Dreamweaver?7.Navigating a Broken Dev Culture8.Ask HN: Do you practice lucid dreaming?9.Ask HN: Tired of startups â€“ want a normal job. Help10.Ask HN: What happened to all those metaverse projects from 2022?11.Ask HN: Are there online communities for single-owner run companies?12.Ask HN: Can I really create a company around my open-source software?13.Ask HN: Anyone building a non AI product/startup?14.Ask HN: Why is Cursor IDE accessing all my env vars?15.Ask HN: What fiction/non-fiction book should everyone read on the topic of CS?16.Ask HN: Advice for someone who stagnated in their career. Help17.Ask HN: Tips on how to find great technical recruiters to land the right job?18.Ask HN: Why is it taking so long to build computer controlling agents?19.Ask HN: Tips to make a pitch for "acquihire of one"?20.Tell HN: Generational Gap21.Ask HN: A retrofitted C dialect?22.Ask HN: How do you use local LLMs?23.Segment for LLM Traces? Seeking Feedback on an Open Source LLM Log Router24.Ask HN: How can I prepare my digital life for geopolitical disruptions?25.I'm broke and non-technical, trying to develop tech startup26.Ask HN: Did you grow up with adventure games and how did that affect yo?27.Ask HN: How can I get my 7-year-old started with web development?28.How to create LLM-driven tiny gnome robots?29.Ask HN: Dot EU domain instead of dot com?30.How do you approach appealing to formal seniority in a technical discussion?More

In [ ]:
import pandas as pd
data = pd.DataFrame
data_str1 = ""
for item in soup.find_all("a", href="item?id=39135679"):
	data_str1 = data_str + item.get_text()

print(data_str1)

In [ ]:
age_element = soup.find_all("span", class_="age")
for age in age_element:
  age_text = age.find("a").text
  print(age_text)

23 hours ago
7 hours ago
4 hours ago
16 hours ago
1 day ago
2 days ago
1 day ago
2 days ago
4 days ago
4 hours ago
2 days ago
4 days ago
10 hours ago
3 days ago
7 days ago
2 days ago
15 hours ago
2 days ago
2 days ago
2 days ago
2 days ago
3 days ago
3 days ago
4 days ago
2 days ago
10 hours ago
4 days ago
6 days ago
3 days ago
12 hours ago

In [ ]:
age_element = soup.find("span", class_="age")
if age_element and age_element.has_attr("title"):
    age = age_element["title"]
    print(f"Age: {age}")
    date_time_string = age.split()[0]

    try:
        datetime_object = datetime.fromisoformat(date_time_string)
        date = datetime_object.date()
        time = datetime_object.time()
        print(f"Parsed Date: {date}")
        print(f"Parsed Time: {time}")
    except ValueError as e:
        print(f"Error parsing datetime: {e}")
else:
    print("No valid 'age' element with a 'title' attribute found.")

Age: 2025-02-23T23:00:16 1740351616
Parsed Date: 2025-02-23
Parsed Time: 23:00:16

In [ ]:
import pandas as pd
data = []

listings = soup.find_all("tr", class_="athing")
from datetime import datetime
for listing in listings:
  title_element = listing.find("span", class_="titleline")
  title = title_element.find("a").text.strip()
  link_element = title_element.find("a")
  href = link_element["href"]
  full_link = f"https://news.ycombinator.com/{href}"

  next_row = listing.find_next("tr")
  subtext_element = next_row.find("td", class_="subtext")

  user_element = subtext_element.find("a", class_="hnuser")
  user = user_element.text.strip()

  age_element = subtext_element.find("span", class_="age")
  relative_time = age_element.find("a").text.strip()
  age = age_element["title"]
  date_time_string = age.split()[0]

  try:
      datetime_object = datetime.fromisoformat(date_time_string)
      date = datetime_object.date()
      time = datetime_object.time()
  except ValueError as e:
      print(f"Error parsing datetime: {e}")
      date = None
      time = None

  date = datetime_object.date()
  time = datetime_object.time()

  score_element = subtext_element.find("span", class_="score")
  score = int(score_element.text.split()[0])

  print(f"Title: {title}")
  print(f"User: {user}")
  print(f"Relative time: {relative_time}")
  print(f"Date: {date}")
  print(f"Time: {time}")
  print(f"Score: {score}")
  print(f"Link: {full_link}")
  print("---")

  data.append({
    "Title": title,
    "User": user,
    "Relative time": relative_time,
    "Date": date,
    "Time": time,
    "Score": score,
    "Link": full_link
  })

df = pd.DataFrame(data)

Title: Ask HN: What are you working on? (February 2025)
User: david927
Relative time: 23 hours ago
Date: 2025-02-23
Time: 23:00:16
Score: 203
Link: https://news.ycombinator.com/item?id=43154065
---
Title: Ask HN: Former devs who can't get a job, what did you end up doing for work?
User: throw81398475
Relative time: 7 hours ago
Date: 2025-02-24
Time: 20:22:37
Score: 20
Link: https://news.ycombinator.com/item?id=43164498
---
Title: Ask HN: My father passed away. How do deal with the grief?
User: gogo61
Relative time: 4 hours ago
Date: 2025-02-24
Time: 23:37:25
Score: 9
Link: https://news.ycombinator.com/item?id=43166256
---
Title: Ask HN: Have you written or consumed OpenAPI Arazzo specification?
User: sb13
Relative time: 16 hours ago
Date: 2025-02-24
Time: 11:41:47
Score: 5
Link: https://news.ycombinator.com/item?id=43158402
---
Title: Tell HN: Five random IndieWeb blog links on your terminal
User: susam
Relative time: 1 day ago
Date: 2025-02-23
Time: 10:55:47
Score: 44
Link: https://news.ycombinator.com/item?id=43148408
---
Title: Ask HN: Is anyone still using Dreamweaver?
User: gillytech
Relative time: 2 days ago
Date: 2025-02-22
Time: 17:59:27
Score: 165
Link: https://news.ycombinator.com/item?id=43141368
---
Title: Navigating a Broken Dev Culture
User: lightserver
Relative time: 1 day ago
Date: 2025-02-23
Time: 14:27:18
Score: 58
Link: https://news.ycombinator.com/item?id=43149437
---
Title: Ask HN: Do you practice lucid dreaming?
User: raunometsa
Relative time: 2 days ago
Date: 2025-02-22
Time: 12:45:26
Score: 13
Link: https://news.ycombinator.com/item?id=43138523
---
Title: Ask HN: Tired of startups â€“ want a normal job. Help
User: mertleee
Relative time: 4 days ago
Date: 2025-02-21
Time: 00:59:57
Score: 95
Link: https://news.ycombinator.com/item?id=43122800
---
Title: Ask HN: What happened to all those metaverse projects from 2022?
User: herval
Relative time: 4 hours ago
Date: 2025-02-24
Time: 23:57:08
Score: 6
Link: https://news.ycombinator.com/item?id=43166405
---
Title: Ask HN: Are there online communities for single-owner run companies?
User: indulona
Relative time: 2 days ago
Date: 2025-02-22
Time: 12:47:53
Score: 5
Link: https://news.ycombinator.com/item?id=43138540
---
Title: Ask HN: Can I really create a company around my open-source software?
User: darkhorse13
Relative time: 4 days ago
Date: 2025-02-18
Time: 08:37:01
Score: 73
Link: https://news.ycombinator.com/item?id=43087383
---
Title: Ask HN: Anyone building a non AI product/startup?
User: codegeek
Relative time: 10 hours ago
Date: 2025-02-24
Time: 17:46:16
Score: 5
Link: https://news.ycombinator.com/item?id=43162490
---
Title: Ask HN: Why is Cursor IDE accessing all my env vars?
User: iyn
Relative time: 3 days ago
Date: 2025-02-21
Time: 20:07:29
Score: 14
Link: https://news.ycombinator.com/item?id=43132313
---
Title: Ask HN: What fiction/non-fiction book should everyone read on the topic of CS?
User: Eavolution
Relative time: 7 days ago
Date: 2025-02-18
Time: 00:40:33
Score: 35
Link: https://news.ycombinator.com/item?id=43084739
---
Title: Ask HN: Advice for someone who stagnated in their career. Help
User: justonemore
Relative time: 2 days ago
Date: 2025-02-23
Time: 03:49:26
Score: 10
Link: https://news.ycombinator.com/item?id=43146311
---
Title: Ask HN: Tips on how to find great technical recruiters to land the right job?
User: Glimjaur
Relative time: 15 hours ago
Date: 2025-02-24
Time: 12:27:57
Score: 3
Link: https://news.ycombinator.com/item?id=43158741
---
Title: Ask HN: Why is it taking so long to build computer controlling agents?
User: louisfialho
Relative time: 2 days ago
Date: 2025-02-23
Time: 01:19:39
Score: 10
Link: https://news.ycombinator.com/item?id=43145225
---
Title: Ask HN: Tips to make a pitch for "acquihire of one"?
User: rglullis
Relative time: 2 days ago
Date: 2025-02-22
Time: 10:00:30
Score: 2
Link: https://news.ycombinator.com/item?id=43137645
---
Title: Tell HN: Generational Gap
User: yonisto
Relative time: 2 days ago
Date: 2025-02-22
Time: 09:21:37
Score: 4
Link: https://news.ycombinator.com/item?id=43137496
---
Title: Ask HN: A retrofitted C dialect?
User: anqurvanillapy
Relative time: 2 days ago
Date: 2025-02-22
Time: 08:11:45
Score: 7
Link: https://news.ycombinator.com/item?id=43137171
---
Title: Ask HN: How do you use local LLMs?
User: Haeuserschlucht
Relative time: 3 days ago
Date: 2025-02-21
Time: 08:52:01
Score: 7
Link: https://news.ycombinator.com/item?id=43125486
---
Title: Segment for LLM Traces? Seeking Feedback on an Open Source LLM Log Router
User: patethegreat
Relative time: 3 days ago
Date: 2025-02-21
Time: 22:44:57
Score: 11
Link: https://news.ycombinator.com/item?id=43133994
---
Title: Ask HN: How can I prepare my digital life for geopolitical disruptions?
User: mwinatschek
Relative time: 4 days ago
Date: 2025-02-20
Time: 09:16:45
Score: 30
Link: https://news.ycombinator.com/item?id=43112703
---
Title: I'm broke and non-technical, trying to develop tech startup
User: vyasaveda
Relative time: 2 days ago
Date: 2025-02-22
Time: 17:47:25
Score: 5
Link: https://news.ycombinator.com/item?id=43141235
---
Title: Ask HN: Did you grow up with adventure games and how did that affect yo?
User: HellDunkel
Relative time: 10 hours ago
Date: 2025-02-24
Time: 17:48:07
Score: 7
Link: https://news.ycombinator.com/item?id=43162513
---
Title: Ask HN: How can I get my 7-year-old started with web development?
User: johnz
Relative time: 4 days ago
Date: 2025-02-20
Time: 22:43:53
Score: 9
Link: https://news.ycombinator.com/item?id=43121372
---
Title: How to create LLM-driven tiny gnome robots?
User: r33b33
Relative time: 6 days ago
Date: 2025-02-18
Time: 12:54:51
Score: 13
Link: https://news.ycombinator.com/item?id=43088935
---
Title: Ask HN: Dot EU domain instead of dot com?
User: skwee357
Relative time: 3 days ago
Date: 2025-02-21
Time: 09:25:03
Score: 9
Link: https://news.ycombinator.com/item?id=43125655
---
Title: How do you approach appealing to formal seniority in a technical discussion?
User: begoon
Relative time: 12 hours ago
Date: 2025-02-24
Time: 16:05:48
Score: 6
Link: https://news.ycombinator.com/item?id=43161112
---

In [ ]:
df

,Title,User,Relative time,Date,Time,Score,Link
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065
1,"Ask HN: Former devs who can't get a job, what ...",throw81398475,7 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498
2,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,9,https://news.ycombinator.com/item?id=43166256
3,Ask HN: Have you written or consumed OpenAPI A...,sb13,16 hours ago,2025-02-24,11:41:47,5,https://news.ycombinator.com/item?id=43158402
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368
6,Navigating a Broken Dev Culture,lightserver,1 day ago,2025-02-23,14:27:18,58,https://news.ycombinator.com/item?id=43149437
7,Ask HN: Do you practice lucid dreaming?,raunometsa,2 days ago,2025-02-22,12:45:26,13,https://news.ycombinator.com/item?id=43138523
8,Ask HN: Tired of startups â€“ want a normal jo...,mertleee,4 days ago,2025-02-21,00:59:57,95,https://news.ycombinator.com/item?id=43122800
9,Ask HN: What happened to all those metaverse p...,herval,4 hours ago,2025-02-24,23:57:08,6,https://news.ycombinator.com/item?id=43166405
10,Ask HN: Are there online communities for singl...,indulona,2 days ago,2025-02-22,12:47:53,5,https://news.ycombinator.com/item?id=43138540
11,Ask HN: Can I really create a company around m...,darkhorse13,4 days ago,2025-02-18,08:37:01,73,https://news.ycombinator.com/item?id=43087383
12,Ask HN: Anyone building a non AI product/startup?,codegeek,10 hours ago,2025-02-24,17:46:16,5,https://news.ycombinator.com/item?id=43162490
13,Ask HN: Why is Cursor IDE accessing all my env...,iyn,3 days ago,2025-02-21,20:07:29,14,https://news.ycombinator.com/item?id=43132313
14,Ask HN: What fiction/non-fiction book should e...,Eavolution,7 days ago,2025-02-18,00:40:33,35,https://news.ycombinator.com/item?id=43084739
15,Ask HN: Advice for someone who stagnated in th...,justonemore,2 days ago,2025-02-23,03:49:26,10,https://news.ycombinator.com/item?id=43146311
16,Ask HN: Tips on how to find great technical re...,Glimjaur,15 hours ago,2025-02-24,12:27:57,3,https://news.ycombinator.com/item?id=43158741
17,Ask HN: Why is it taking so long to build comp...,louisfialho,2 days ago,2025-02-23,01:19:39,10,https://news.ycombinator.com/item?id=43145225
18,"Ask HN: Tips to make a pitch for ""acquihire of...",rglullis,2 days ago,2025-02-22,10:00:30,2,https://news.ycombinator.com/item?id=43137645
19,Tell HN: Generational Gap,yonisto,2 days ago,2025-02-22,09:21:37,4,https://news.ycombinator.com/item?id=43137496
20,Ask HN: A retrofitted C dialect?,anqurvanillapy,2 days ago,2025-02-22,08:11:45,7,https://news.ycombinator.com/item?id=43137171
21,Ask HN: How do you use local LLMs?,Haeuserschlucht,3 days ago,2025-02-21,08:52:01,7,https://news.ycombinator.com/item?id=43125486
22,Segment for LLM Traces? Seeking Feedback on an...,patethegreat,3 days ago,2025-02-21,22:44:57,11,https://news.ycombinator.com/item?id=43133994
23,Ask HN: How can I prepare my digital life for ...,mwinatschek,4 days ago,2025-02-20,09:16:45,30,https://news.ycombinator.com/item?id=43112703
24,"I'm broke and non-technical, trying to develop...",vyasaveda,2 days ago,2025-02-22,17:47:25,5,https://news.ycombinator.com/item?id=43141235
25,Ask HN: Did you grow up with adventure games a...,HellDunkel,10 hours ago,2025-02-24,17:48:07,7,https://news.ycombinator.com/item?id=43162513
26,Ask HN: How can I get my 7-year-old started wi...,johnz,4 days ago,2025-02-20,22:43:53,9,https://news.ycombinator.com/item?id=43121372
27,How to create LLM-driven tiny gnome robots?,r33b33,6 days ago,2025-02-18,12:54:51,13,https://news.ycombinator.com/item?id=43088935
28,Ask HN: Dot EU domain instead of dot com?,skwee357,3 days ago,2025-02-21,09:25:03,9,https://news.ycombinator.com/item?id=43125655
29,How do you approach appealing to formal senior...,begoon,12 hours ago,2025-02-24,16:05:48,6,https://news.ycombinator.com/item?id=43161112

In [ ]:
df.drop(index=3, inplace=True)
df.drop(index=11, inplace=True)
df.drop(index=16, inplace=True)
df.drop(index=22, inplace=True)

In [ ]:
df

,Title,User,Relative time,Date,Time,Score,Link
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065
1,"Ask HN: Former devs who can't get a job, what ...",throw81398475,7 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498
2,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,9,https://news.ycombinator.com/item?id=43166256
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368
6,Navigating a Broken Dev Culture,lightserver,1 day ago,2025-02-23,14:27:18,58,https://news.ycombinator.com/item?id=43149437
7,Ask HN: Do you practice lucid dreaming?,raunometsa,2 days ago,2025-02-22,12:45:26,13,https://news.ycombinator.com/item?id=43138523
8,Ask HN: Tired of startups â€“ want a normal jo...,mertleee,4 days ago,2025-02-21,00:59:57,95,https://news.ycombinator.com/item?id=43122800
9,Ask HN: What happened to all those metaverse p...,herval,4 hours ago,2025-02-24,23:57:08,6,https://news.ycombinator.com/item?id=43166405
10,Ask HN: Are there online communities for singl...,indulona,2 days ago,2025-02-22,12:47:53,5,https://news.ycombinator.com/item?id=43138540
12,Ask HN: Anyone building a non AI product/startup?,codegeek,10 hours ago,2025-02-24,17:46:16,5,https://news.ycombinator.com/item?id=43162490
13,Ask HN: Why is Cursor IDE accessing all my env...,iyn,3 days ago,2025-02-21,20:07:29,14,https://news.ycombinator.com/item?id=43132313
14,Ask HN: What fiction/non-fiction book should e...,Eavolution,7 days ago,2025-02-18,00:40:33,35,https://news.ycombinator.com/item?id=43084739
15,Ask HN: Advice for someone who stagnated in th...,justonemore,2 days ago,2025-02-23,03:49:26,10,https://news.ycombinator.com/item?id=43146311
17,Ask HN: Why is it taking so long to build comp...,louisfialho,2 days ago,2025-02-23,01:19:39,10,https://news.ycombinator.com/item?id=43145225
18,"Ask HN: Tips to make a pitch for ""acquihire of...",rglullis,2 days ago,2025-02-22,10:00:30,2,https://news.ycombinator.com/item?id=43137645
19,Tell HN: Generational Gap,yonisto,2 days ago,2025-02-22,09:21:37,4,https://news.ycombinator.com/item?id=43137496
20,Ask HN: A retrofitted C dialect?,anqurvanillapy,2 days ago,2025-02-22,08:11:45,7,https://news.ycombinator.com/item?id=43137171
21,Ask HN: How do you use local LLMs?,Haeuserschlucht,3 days ago,2025-02-21,08:52:01,7,https://news.ycombinator.com/item?id=43125486
23,Ask HN: How can I prepare my digital life for ...,mwinatschek,4 days ago,2025-02-20,09:16:45,30,https://news.ycombinator.com/item?id=43112703
24,"I'm broke and non-technical, trying to develop...",vyasaveda,2 days ago,2025-02-22,17:47:25,5,https://news.ycombinator.com/item?id=43141235
25,Ask HN: Did you grow up with adventure games a...,HellDunkel,10 hours ago,2025-02-24,17:48:07,7,https://news.ycombinator.com/item?id=43162513
26,Ask HN: How can I get my 7-year-old started wi...,johnz,4 days ago,2025-02-20,22:43:53,9,https://news.ycombinator.com/item?id=43121372
27,How to create LLM-driven tiny gnome robots?,r33b33,6 days ago,2025-02-18,12:54:51,13,https://news.ycombinator.com/item?id=43088935
28,Ask HN: Dot EU domain instead of dot com?,skwee357,3 days ago,2025-02-21,09:25:03,9,https://news.ycombinator.com/item?id=43125655
29,How do you approach appealing to formal senior...,begoon,12 hours ago,2025-02-24,16:05:48,6,https://news.ycombinator.com/item?id=43161112

In [ ]:
URL = "https://news.ycombinator.com/item?id=39171079"
r = requests.get(URL)
soup = BeautifulSoup(r.content, 'html.parser')
print(soup.prettify())

<html lang="en" op="item">
 <head>
  <meta content="origin" name="referrer"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="news.css?Y6kWEjCA9NYsuD0e1zNN" rel="stylesheet" type="text/css"/>
  <link href="y18.svg" rel="icon"/>
  <link href="https://news.ycombinator.com/item?id=39171079" rel="canonical">
   <title>
    Ask HN: Those who've joined a friend's startup as an employee, how did that go? | Hacker News
   </title>
  </link>
 </head>
 <body>
  <center>
   <table bgcolor="#f6f6ef" border="0" cellpadding="0" cellspacing="0" id="hnmain" width="85%">
    <tr>
     <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" style="padding:2px" width="100%">
       <tr>
        <td style="width:18px;padding-right:4px">
         <a href="https://news.ycombinator.com">
          <img height="18" src="y18.svg" style="border:1px white solid; display:block" width="18"/>
         </a>
        </td>
        <td style="line-height:12pt; height:10px;">
         <span class="pagetop">
          <b class="hnname">
           <a href="news">
            Hacker News
           </a>
          </b>
          <a href="newest">
           new
          </a>
          |
          <a href="front">
           past
          </a>
          |
          <a href="newcomments">
           comments
          </a>
          |
          <a href="ask">
           ask
          </a>
          |
          <a href="show">
           show
          </a>
          |
          <a href="jobs">
           jobs
          </a>
          |
          <a href="submit" rel="nofollow">
           submit
          </a>
         </span>
        </td>
        <td style="text-align:right;padding-right:4px;">
         <span class="pagetop">
          <a href="login?goto=item%3Fid%3D39171079">
           login
          </a>
         </span>
        </td>
       </tr>
      </table>
     </td>
    </tr>
    <tr id="pagespace" style="height:10px" title="Ask HN: Those who've joined a friend's startup as an employee, how did that go?">
    </tr>
    <tr>
     <td>
      <table border="0" class="fatitem">
       <tr class="athing submission" id="39171079">
        <td align="right" class="title" valign="top">
         <span class="rank">
         </span>
        </td>
        <td class="votelinks" valign="top">
         <center>
          <a href="vote?id=39171079&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39171079">
           <div class="votearrow" title="upvote">
           </div>
          </a>
         </center>
        </td>
        <td class="title">
         <span class="titleline">
          <a href="item?id=39171079">
           Ask HN: Those who've joined a friend's startup as an employee, how did that go?
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td class="subtext">
         <span class="subline">
          <span class="score" id="score_39171079">
           227 points
          </span>
          by
          <a class="hnuser" href="user?id=humbleferret">
           humbleferret
          </a>
          <span class="age" title="2024-01-28T23:41:15 1706485275">
           <a href="item?id=39171079">
            on Jan 28, 2024
           </a>
          </span>
          <span id="unv_39171079">
          </span>
          |
          <a href="hide?id=39171079&amp;goto=item%3Fid%3D39171079">
           hide
          </a>
          |
          <a class="hnpast" href="https://hn.algolia.com/?query=Ask%20HN%3A%20Those%20who%27ve%20joined%20a%20friend%27s%20startup%20as%20an%20employee%2C%20how%20did%20that%20go%3F&amp;type=story&amp;dateRange=all&amp;sort=byDate&amp;storyText=false&amp;prefix&amp;page=0">
           past
          </a>
          |
          <a href="fave?id=39171079&amp;auth=d426929409008082e8d599b1a7c0603b0408ef70">
           favorite
          </a>
          |
          <a href="item?id=39171079">
           280 comments
          </a>
         </span>
        </td>
       </tr>
       <tr>
        <td style="height:2px">
        </td>
       </tr>
       <tr>
        <td colspan="2">
        </td>
        <td>
         <div class="toptext">
          While much has been said about co-founding with friends, the dynamics of joining a friend's startup as an employee aren't as widely discussed.
          <p>
           Have you gone to work for your friend's startup as an employee? How did that go? Would you do it again?
          </p>
         </div>
        </td>
       </tr>
      </table>
      <br/>
      <br/>
      <table border="0" class="comment-tree">
       <tr class="athing comtr" id="39171711">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="0">
            <img height="1" src="s.gif" width="0"/>
           </td>
           <td class="votelinks" valign="top">
            <center>
             <a href="vote?id=39171711&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39171711">
              <div class="votearrow" title="upvote">
              </div>
             </a>
            </center>
           </td>
           <td class="default">
            <div style="margin-top:2px; margin-bottom:-10px;">
             <span class="comhead">
              <a class="hnuser" href="user?id=xrd">
               xrd
              </a>
              <span class="age" title="2024-01-29T01:12:45 1706490765">
               <a href="item?id=39171711">
                on Jan 29, 2024
               </a>
              </span>
              <span id="unv_39171711">
              </span>
              <span class="navs">
               |
               <a aria-hidden="true" class="clicky" href="#39175594">
                next
               </a>
               <a class="togg clicky" href="javascript:void(0)" id="39171711" n="24">
                [–]
               </a>
               <span class="onstory">
               </span>
              </span>
             </span>
            </div>
            <br/>
            <div class="comment">
             <div class="commtext c00">
              It definitely ruined a friendship of mine. His startup was making insane amounts of money. He offered me a position, then his business priorities changed and forced me into a poor role with no long term prospects. I struggled in that new role and he noticed that. He then terminated our agreement two months early.
              <p>
               There are reasons he's right about what he did and there are reasons I'm right about being upset about it but it definitely cost us our friendship.
               <p>
                I think back that if he had operated with integrity and honored his agreement to keep me on for two extra months it would have not been upsetting to leave then. As it was it left me scrambling with three small kids.
                <p>
                 The lesson to me is that even if the startup is flush with cash, there will be issues. How the founder manages those issues matters.
                 <p>
                  I recall when I had my startup I did a bunch of business coaching and really had to take on a lot of uncomfortable things about myself. I'm grateful for that. I invited him many times to participate in that work and he never did. When the money is good you think you don't need it.
                 </p>
                </p>
               </p>
              </p>
             </div>
             <div class="reply">
              <p>
               <font size="1">
               </font>
              </p>
             </div>
            </div>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr class="athing comtr" id="39177242">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="1">
            <img height="1" src="s.gif" width="40"/>
           </td>
           <td class="votelinks" valign="top">
            <center>
             <a href="vote?id=39177242&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39177242">
              <div class="votearrow" title="upvote">
              </div>
             </a>
            </center>
           </td>
           <td class="default">
            <div style="margin-top:2px; margin-bottom:-10px;">
             <span class="comhead">
              <a class="hnuser" href="user?id=mercenario">
               mercenario
              </a>
              <span class="age" title="2024-01-29T15:20:53 1706541653">
               <a href="item?id=39177242">
                on Jan 29, 2024
               </a>
              </span>
              <span id="unv_39177242">
              </span>
              <span class="navs">
               |
               <a aria-hidden="true" class="clicky" href="#39171711">
                parent
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39174170">
                next
               </a>
               <a class="togg clicky" href="javascript:void(0)" id="39177242" n="2">
                [–]
               </a>
               <span class="onstory">
               </span>
              </span>
             </span>
            </div>
            <br/>
            <div class="comment">
             <div class="commtext c00">
              On one side you were a employee, so he needs to treat you kinda like a regular employee. If what he did to you would be normal for another employee, then he has a point. Doing different could even be seem as unfair for the other employees.
              <p>
               On the other side you are a friend, I really don't know what he could have done differently, very hard.
              </p>
             </div>
             <div class="reply">
              <p>
               <font size="1">
               </font>
              </p>
             </div>
            </div>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr class="athing comtr" id="39205809">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="2">
            <img height="1" src="s.gif" width="80"/>
           </td>
           <td class="votelinks" valign="top">
            <center>
             <a href="vote?id=39205809&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39205809">
              <div class="votearrow" title="upvote">
              </div>
             </a>
            </center>
           </td>
           <td class="default">
            <div style="margin-top:2px; margin-bottom:-10px;">
             <span class="comhead">
              <a class="hnuser" href="user?id=solardev">
               solardev
              </a>
              <span class="age" title="2024-01-31T16:35:43 1706718943">
               <a href="item?id=39205809">
                on Jan 31, 2024
               </a>
              </span>
              <span id="unv_39205809">
              </span>
              <span class="navs">
               |
               <a aria-hidden="true" class="clicky" href="#39171711">
                root
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39177242">
                parent
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39174170">
                next
               </a>
               <a class="togg clicky" href="javascript:void(0)" id="39205809" n="1">
                [–]
               </a>
               <span class="onstory">
               </span>
              </span>
             </span>
            </div>
            <br/>
            <div class="comment">
             <div class="commtext c00">
              Wouldn't the right thing to have done for any employee, friend or not, be to simply pay them the remaining two months but let them go early?
             </div>
             <div class="reply">
              <p>
               <font size="1">
               </font>
              </p>
             </div>
            </div>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr class="athing comtr" id="39174170">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="1">
            <img height="1" src="s.gif" width="40"/>
           </td>
           <td class="votelinks" valign="top">
            <center>
             <a href="vote?id=39174170&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39174170">
              <div class="votearrow" title="upvote">
              </div>
             </a>
            </center>
           </td>
           <td class="default">
            <div style="margin-top:2px; margin-bottom:-10px;">
             <span class="comhead">
              <a class="hnuser" href="user?id=geraldhh">
               geraldhh
              </a>
              <span class="age" title="2024-01-29T08:47:53 1706518073">
               <a href="item?id=39174170">
                on Jan 29, 2024
               </a>
              </span>
              <span id="unv_39174170">
              </span>
              <span class="navs">
               |
               <a aria-hidden="true" class="clicky" href="#39171711">
                parent
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39177242">
                prev
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39175594">
                next
               </a>
               <a class="togg clicky" href="javascript:void(0)" id="39174170" n="21">
                [–]
               </a>
               <span class="onstory">
               </span>
              </span>
             </span>
            </div>
            <br/>
            <div class="comment">
             <div class="commtext c00">
              &gt; As it was it left me scrambling with three small kids.
              <p>
               you did not mention whether this early termination was communicated beforehand.
               <p>
                nevertheless this person probably never was your friend. sry
               </p>
              </p>
             </div>
             <div class="reply">
              <p>
               <font size="1">
               </font>
              </p>
             </div>
            </div>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr class="athing comtr" id="39175690">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="2">
            <img height="1" src="s.gif" width="80"/>
           </td>
           <td class="votelinks" valign="top">
            <center>
             <a href="vote?id=39175690&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39175690">
              <div class="votearrow" title="upvote">
              </div>
             </a>
            </center>
           </td>
           <td class="default">
            <div style="margin-top:2px; margin-bottom:-10px;">
             <span class="comhead">
              <a class="hnuser" href="user?id=michaelt">
               michaelt
              </a>
              <span class="age" title="2024-01-29T12:56:27 1706532987">
               <a href="item?id=39175690">
                on Jan 29, 2024
               </a>
              </span>
              <span id="unv_39175690">
              </span>
              <span class="navs">
               |
               <a aria-hidden="true" class="clicky" href="#39171711">
                root
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39174170">
                parent
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39175952">
                next
               </a>
               <a class="togg clicky" href="javascript:void(0)" id="39175690" n="17">
                [–]
               </a>
               <span class="onstory">
               </span>
              </span>
             </span>
            </div>
            <br/>
            <div class="comment">
             <div class="commtext c00">
              <i>
               &gt; nevertheless this person probably never was your friend. sry
              </i>
              <p>
               No, it's completely common for friendships to break down over business.
               <p>
                Very few friendships are robust enough to survive one party costing the other $20,000.
               </p>
              </p>
             </div>
             <div class="reply">
              <p>
               <font size="1">
               </font>
              </p>
             </div>
            </div>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr class="athing comtr" id="39175924">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="3">
            <img height="1" src="s.gif" width="120"/>
           </td>
           <td class="votelinks" valign="top">
            <center>
             <a href="vote?id=39175924&amp;how=up&amp;goto=item%3Fid%3D39171079" id="up_39175924">
              <div class="votearrow" title="upvote">
              </div>
             </a>
            </center>
           </td>
           <td class="default">
            <div style="margin-top:2px; margin-bottom:-10px;">
             <span class="comhead">
              <a class="hnuser" href="user?id=xrd">
               xrd
              </a>
              <span class="age" title="2024-01-29T13:24:45 1706534685">
               <a href="item?id=39175924">
                on Jan 29, 2024
               </a>
              </span>
              <span id="unv_39175924">
              </span>
              <span class="navs">
               |
               <a aria-hidden="true" class="clicky" href="#39171711">
                root
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39175690">
                parent
               </a>
               |
               <a aria-hidden="true" class="clicky" href="#39176384">
                next
               </a>
               <a class="togg clicky" href="javascript:void(0)" id="39175924" n="12">
                [–]
               </a>
               <span class="onstory">
               </span>
              </span>
             </span>
            </div>
            <br/>
            <div class="comment">
             <div class="commtext c00">
              It's wild that you said that amount because that was exactly the number.
              <p>
               I have other friendships that have been tested for similar amounts that have survived. But, it leaves a mark.
               <p>
                I had an ex-employee who worked for me under starvation wages in a startup long ago. He was upset about that and some tax implications, and brought it up with me. I gave him a smallish lump sum and enabled him to put a down payment on a house. I need to ask him about that, it was really brave to ask me to clean something up, and I never did that with the friend from the OP. I wonder if it would have gone differently.
                <p>
                 I'm seeing a lot of people in my circle struggling right now. I bet 2024 is going to be a bad year for friendships.
                </p>
               </p>
              </p>
             </div>
             <div class="reply">
              <p>
               <font size="1">
               </font>
              </p>
             </div>
            </div>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr class="athing comtr" id="39176113">
        <td>
         <table border="0">
          <tr>
           <td class="ind" indent="4">

In [ ]:
listing = soup.find("div", class_="toptext")
text_content = listing.get_text(strip=True)
text_content

"While much has been said about co-founding with friends, the dynamics of joining a friend's startup as an employee aren't as widely discussed.Have you gone to work for your friend's startup as an employee? How did that go? Would you do it again?"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26 entries, 0 to 29
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          26 non-null     object
 1   User           26 non-null     object
 2   Relative time  26 non-null     object
 3   Date           26 non-null     object
 4   Time           26 non-null     object
 5   Score          26 non-null     int64
 6   Link           26 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.7+ KB

In [ ]:
df['Link'][9]

'https://news.ycombinator.com/item?id=43166405'

In [ ]:
for link in df['Link']:
    URL = link
    r = requests.get(URL)
    soup = BeautifulSoup(r.content, 'html.parser')
    listing = soup.find("div", class_="toptext")

    if listing:
        text_content = listing.get_text(strip=True)
        row_index = df[df['Link'] == link].index[0]
        df.loc[row_index, 'Question'] = text_content
    else:
        print("Warning: 'div' element with class 'toptext' not found for link:", link)
        df.loc[row_index, 'Question'] = None

    print(link)
    print(text_content)

https://news.ycombinator.com/item?id=43154065
What are you working on?  Any new ideas that you're thinking about?
https://news.ycombinator.com/item?id=43164498
That's all.Savings are getting low, and I'm going to be struggling to pay rent soon.  I'm curious what other kinds of work other former developers got into and if they like it.  Cheers.
https://news.ycombinator.com/item?id=43166256
It has been one month since he passed and i have been continuously crying. I am writing this with tears in my eye.
https://news.ycombinator.com/item?id=43148408
Hello HN!  I believe some of you might have come across this pretty interesting post about discovering IndieWeb blogs, one blog at a time: <https://news.ycombinator.com/item?id=43139953>That post is actually a link to <https://indieblog.page/>, which features an impressive list of independently maintained personal websites and blogs with RSS feeds.I was wondering, if instead of discovering one blog at a time, I could discover five blogs at once, directly from my terminal!  Turns out the website has <https://indieblog.page/random> which picks a random blog and redirects you to it.  It has daily feeds of N random posts too, where N = 1, 3, 5, and 10.But if, like me, you'd like to have five random blogs suggested in your terminal, here is a quick shell one-liner I'd like to share.  It fetches the random blog picker page five times, cleans up the URLs a bit, and prints them on the terminal:for _ in $(seq 1 5); do curl -sSI https://indieblog.page/random | grep location | sed 's/location: \(.*\).utm_source=.*/\1/'; doneOr if you want something to go in ~/.zshrc, ~/.bashrc, etc., then you could have a tiny shell function like this:iw5() {
      for _ in $(seq 1 5)
      do
          curl -sSI https://indieblog.page/random |
              grep location |
              sed 's/location: \(.*\).utm_source=.*/\1/'
      done
  }Here is an example output:$ iw5
  https://justinsimoni.com/colorado-trail-24-hour-backpacking-challenge-in-may-how-far-can-i-hike/
  http://www.iamcal.com/2024-09/10218/
  https://dracos.co.uk/wrote/advent-of-code-2024-7/
  https://leancrew.com/all-this/2024/12/mind-your-plotting/
  http://i.never.nu/personal-foundational-texts/It helps me to quickly browse through a set of random suggestions on the terminal, decide which one I want to visit, right click on it, and select the "open link" option to open the link in a web browser.  Yes, I know this amounts to judging a post by its link, but sometimes the post slug (if present) alone sparks enough curiosity to dive deeper, and it's a quick way to explore new posts without overthinking it.If you're using this, please be considerate of the indieblog.page web server.  Avoid running it too frequently to prevent putting unnecessary strain on the server.
https://news.ycombinator.com/item?id=43141368
When I was learning to build websites in 2010 Dreamweaver was the go-to. I remember it thoroughly confused the heck out of me. Anyone here able to use it effectively?
https://news.ycombinator.com/item?id=43149437
My Current Job is a Mess—But I Won’t Let It Define Me(Disclaimer: Not here to trash my company, just sharing my experience.)I work on the AI team at my current job, meaning I get to play with cutting-edge generative AI tech. I’ve built some pretty cool things:
 • Designed an end-to-end image generation pipeline for a virtual friend app.
 • Implemented self-hosted Stable Diffusion with Automatic1111, adding sentiment-based image optimization & image retrieval.
 • Used Vicuna (uncensored) + VLLM for serving our text model.Sounds exciting, right? That’s about where the good part ends.The Bad: A Tech Culture Stuck in the Stone AgeThe engineering practices at my company are, to put it mildly, nonexistent:
 • Testing? None. Even revenue-generating products (~$200K/yr) are tested manually.
 • Deployments? Manual SSH into the server, copy the build, and pray.
 • CI/CD? What’s that?
 • Docker/Kubernetes? Not in our vocabulary.
 • Code Quality? Negative.I’ve tried pushing for better practices—heck, I even gave a Docker session to the team—but there’s no buy-in.The New Obsession: AI is Eating Our JobsManagement (none of whom are engineers) has fully bought into the “AI replaces devs” hype. Our CTO literally said:“Use GPT to write code. This is a one-day task; it shouldn’t take more than that.”They genuinely believe AI can replace skilled developers overnight. Meanwhile, they’ve never used GPT to write production code themselves. They just read the PR spin and assume it’s magic.Despite this chaos, I’ve refused to let the environment affect my growth. WFH helped me stay sane, but now that we’re back in the office, I know it’s time to move on.I never had a formal AI background, but I self-learned everything while on the job. Along the way:
 • Cleared GSoC and worked on Intel’s ML toolkit OpenVINO (JS bindings).
 • Discovered OpenTensor (decentralized intelligence), cold-emailed a contributor, and worked part-time on his startup.
 • Got my Rust PR accepted into Docify (used by Polkadot).
 • Built a Rust + HTMX startup backend using Rocket (signed an NDA, so can’t share details).What’s Next?I’m scrambling to find a new job. Ideally, I’d love to work on FOSS full-time rather than jumping into another corporate dev job. The problem? Finding an opportunity that matches my current compensation in India.I recently worked a contract gig for $17.35/hr—if I had a year-long commitment at that rate, I’d have left my job yesterday.I know going full-time into FOSS isn’t easy, but if you have advice—or know FOSS projects that need contributors—I’d love to connect.My stack:
 • Frontend: React / Next.js / TypeScript
 • Backend: Node.js / FastAPI / Flask
 • GenAI: LangChain, RAG, Stable Diffusion, Tool-Calling
 • DevOps: (Self-learning)I’m in a phase where I can afford to push myself to maximize my learning, but I also need to be practical. If you’ve been through something similar or have insights on making a sustainable career in FOSS, I’d love to hear from you.Thanks for reading—I appreciate any thoughts, advice, or connections!
https://news.ycombinator.com/item?id=43138523
Hey!I know this is a question we're not usually discussing here on HN but I'm sure some of you have at least once in their life experienced lucid dreaming if not practicing regularly.Would be fun to hear about your experiences. I'm not actively practicing now but should pick it up again (it was a lot of fun).What I always emphasise when talking about LD's this: it's REAL. It's a full virtual reality experience not only with visuals and sounds but with taste, touch, and emotions, too.I'm putting together a small report called The State of Lucid Dreaming 2025. Here are 9 questions if you'd like to participate:
https://dreamvr.co/stats/questionsAnd here are the preliminary results:
https://dreamvr.co/stats
https://news.ycombinator.com/item?id=43122800
All but the first few years out of school I spent the better part of my 20's working in startups.  I've networked well enough, had some ups and some downs.  Initially just working for startups as an IC eventually moving into product / technical product and later actually founding / co-founding two companies.One fizzled out, the other was acquired in a way I sort of made money.Recently the market has been a bit of a mess and although I took a break to avoid burnout I'm realizing startups (at least with my level of ability and intelligence) are likely just not a great way to make money.I'm newly 30 and starting to realize I kind of just want a life and a reasonable tech salary.  Nothing insane, just something that could support me in a b-tier city with my own place where I have enough time to actually have a girlfriend and well... a normal life.I'm freaking out because the market is beyond fucked and it seems like my only real choice if I want to "grow" as an engineer / product guy is founding another company.  Fortunately I got into some solid accelerators in the valley with a friend from a few years back.  It feels good, but at the same time, I feel old and just want a normal job.  Even shooting around what new college grads are getting would be fine ($120-140k).  I feel like a freaking loser given my age and my relative career stagnation / my inability to actually turn my mildly above average skills into any real money.Last time I interviewed, my litany of previous startups seemed to totally kneecap my chances of getting return callbacks led alone offers.  Any advice where I should look next - I feel like between AI and offshoring I might just need to do something else all-together.Any advice here is appreciated :)
Warning: 'div' element with class 'toptext' not found for link: https://news.ycombinator.com/item?id=43166405
https://news.ycombinator.com/item?id=43166405
All but the first few years out of school I spent the better part of my 20's working in startups.  I've networked well enough, had some ups and some downs.  Initially just working for startups as an IC eventually moving into product / technical product and later actually founding / co-founding two companies.One fizzled out, the other was acquired in a way I sort of made money.Recently the market has been a bit of a mess and although I took a break to avoid burnout I'm realizing startups (at least with my level of ability and intelligence) are likely just not a great way to make money.I'm newly 30 and starting to realize I kind of just want a life and a reasonable tech salary.  Nothing insane, just something that could support me in a b-tier city with my own place where I have enough time to actually have a girlfriend and well... a normal life.I'm freaking out because the market is beyond fucked and it seems like my only real choice if I want to "grow" as an engineer / product guy is founding another company.  Fortunately I got into some solid accelerators in the valley with a friend from a few years back.  It feels good, but at the same time, I feel old and just want a normal job.  Even shooting around what new college grads are getting would be fine ($120-140k).  I feel like a freaking loser given my age and my relative career stagnation / my inability to actually turn my mildly above average skills into any real money.Last time I interviewed, my litany of previous startups seemed to totally kneecap my chances of getting return callbacks led alone offers.  Any advice where I should look next - I feel like between AI and offshoring I might just need to do something else all-together.Any advice here is appreciated :)
https://news.ycombinator.com/item?id=43138540
I am wondering if there are any online communities(discord, slack, forums) for people who have single-handedly built and run their online businesses - AND it is not a cesspool of never-ending promos and garbage ads ala linkedin?
https://news.ycombinator.com/item?id=43162490
AI is an exciting technology that is surely changing the world. But I would love to know if anyone is building non AI stuff in 2025. At least not primarily AI.
https://news.ycombinator.com/item?id=43132313
Recently I tried playing with https://www.cursor.com/ but got spooked by the LuLu alert (https://objective-see.org/products/lulu.html) when launching the app, where the process args included "JSON.stringify(process.env)" part, see screenshot here: https://imgur.com/a/DmDuGTzIs this... normal? I don't understand why they might want to serialize/access all of my env vars. Does anyone have a suggestion for that behaviour? I'm probably missing some reasonable explanation, happy to learn more.I've been running a lot of stuff in VMs lately anyway, but don't want to end up having to spin up a VM for the core app like a code editor. How do you all deal with untrusted (but not really malware-level untrusted) software?
https://news.ycombinator.com/item?id=43084739
This should be interpreted in the broadest sense to include books like both American Kingpin and Practical Vim as examples.
https://news.ycombinator.com/item?id=43146311
Hi HN. 50 year old here. I had a mixed career in corporate roles (product dev, bus dev - first 10 years of working), then a startup (did ok, but more learning than earning), and now have been teaching in a university for 10 years. Along the way I built a niche out of running startup programs for other institutions.I enjoy the work. It's fun and people definitely enjoy and tell me they benefit from what I do.But it's not enough financially. The university doesn't pay much and I am just breaking even each year and dependent on consulting income to pay for growing family expenses. Every time I get brought in to a new consulting project I knock it out of the park. But those projects are one-offs and seem to be dwindling. Side projects I spin up come to low thousands a year and while I enjoy them, don't do anything to take the financial pressure off. When I was 25 I used to pride myself on being able to live on a shoestring out of a backpack, but it's a different story with a wife and kids.I don't project confidence (something I probably am resistant to) but once I land somewhere I usually become a go-to person that gets things done and makes a team productive. But I haven't been able to get in the door anywhere new (corporate, consulting, or funded startup) and I can't figure out why. At this point I don't know who wants to hire someone like me.Anyone dealt with something like this? What did you do? Or what worked and didn't work?I appreciate any advice.
https://news.ycombinator.com/item?id=43145225
I'm not a PhD but I assume training computer controlling agents is a straightforward problem as we can define clear tasks (e.g. schedule appointment with details xyz or buy product xyz) on real or generated websites and just let the models figure our where to click (through vlm) and learn through RL.What am I missing, why isn't this a solved problem by now?
https://news.ycombinator.com/item?id=43137645
This could also be called "How can I pitch myself for a job at a company for a position that does not exist?".Is there such a thing? Can anyone share any stories of how they got in contact with an acquiring company? Does it just become a job interview?
https://news.ycombinator.com/item?id=43137496
So this week, I was teaching a new employee about the system. He is 30 years old and has been in the industry for six years now. At one point, I described an external tool that we use, which produces an XML file. Something felt off about his questions, and then a realization hit me:"Do you know what XML is?"He didn't.I have a few takeaways:1. I'm old.
2. I envy him—I hate XML. 99% of the time, it actively sabotages my work.
3. JSON simplicity won.That's it. No moral.
https://news.ycombinator.com/item?id=43137171
Hi I'm Anqur, a senior software engineer with different backgrounds where development in C was often an important part of my work. E.g.1) Game: A Chinese/Vietnam game with C/C++ for making server/client, Lua for scripting [1]. 2) Embedded systems: Switch/router with network stack all written in C [2]. 3) (Networked) file system: Ceph FS client, which is a kernel module. [3](I left some unnecessary details in links, but are true projects I used to work on.)Recently, there's a hot topic about Rust and C in kernel and a message [4] just draws my attention, where it talks about the "Rust" experiment in kernel development:> I'd like to understand what the goal of this Rust "experiment" is:  If we want to fix existing issues with memory safety we need to do that for existing code and find ways to retrofit it.So for many years, I keep thinking about having a new C dialect for retrofitting the problems, but ofC itself.Sometimes big systems and software (e.g. OS, browsers, databases) could be made entirely in different languages like C++, Rust, D, Zig, etc. But typically, like I slightly mentioned above, making a good filesystem client requires one to write kernel modules (i.e. to provide a VFS implementation. I do know FUSE, but I believe it's better if one could use VFS directly), it's not always feasible to switch languages.And I still love C, for its unique "bare-bone" experience:1) Just talk to the platform, almost all the platforms speak C. Nothing like Rust's PAL (platform-agnostic layer) is needed. 2) Just talk to other languages, C is the lingua franca (except Go needs no libc by default). Not to mention if I want WebAssembly to talk to Rust, `extern "C"` is need in Rust code. 3) Just a libc, widely available, write my own data structures carefully. Since usually one is writing some critical components of a bigger system in C, it's just okay there are not many choices of existing libraries to use. 4) I don't need an over-generalized generics functionality, use of generics is quite limited.So unlike a few `unsafe` in a safe Rust, I want something like a few "safe" in an ambient "unsafe" C dialect. But I'm not saying "unsafe" is good or bad, I'm saying that "don't talk about unsafe vs safe", it's C itself, you wouldn't say anything is "safe" or "unsafe" in C.Actually I'm also an expert on implementing advanced type systems, some of my works include:1) A row-polymorphic JavaScript dialect [5]. 2) A tiny theorem prover with Lean 4 syntax in less than 1K LOC [6]. 3) A Rust dialect with reuse analysis [7].Language features like generics, compile-time eval, trait/typeclass, bidirectional typechecking are trivial for me, I successfully implemented them above.For the retrofitted C, these features initially come to my mind:1) Code generation directly to C, no LLVM IR, no machine code. 2) Module, like C++20 module, to eliminate use of headers. 3) Compile-time eval, type-level computation, like `malloc(int)` is actually a thing. 4) Tactics-like metaprogramming to generate definitions, acting like type-safe macros. 5) Quantitative types [8] to track the use of resources (pointers, FDs). The typechecker tells the user how to insert `free` in all possible positions, don't do anything like RAII. 6) Limited lifetime checking, but some people tells me lifetime is not needed in such a language.Any further insights? Shall I kickstart such project? Please I need your ideas very much.[1]: https://vi.wikipedia.org/wiki/V%C3%B5_L%C3%A2m_Truy%E1%BB%81n_K%E1%BB%B3[2]: https://e.huawei.com/en/products/optical-access/ma5800[3]: https://docs.ceph.com/en/reef/cephfs/[4]: https://lore.kernel.org/rust-for-linux/Z7SwcnUzjZYfuJ4-@infradead.org/[5]: https://github.com/rowscript/rowscript[6]: https://github.com/anqurvanillapy/TinyLean[7]: https://github.com/SchrodingerZhu/reussir-lang[8]: https://bentnib.org/quantitative-type-theory.html
https://news.ycombinator.com/item?id=43125486
What applications(as in use cases, not in software names) have you found for local LLMs that you use yourself on a daily basis, and which LLMs do you use?
https://news.ycombinator.com/item?id=43112703
I'm from Germany and currently rely on macOS and iOS, with all my personal data stored in iCloud. Recent political tensions have made me question what might happen in the event of a military conflict between the US and Europe. Could Apple be forced to shut down its services in Europe? What would happen to my devices, operating systems, and stored data in such a scenario?Are there steps I can take now to prepare for this possibility? Alternatives like Windows and Android are also American-based, and even Linux has strong ties to the US. What options do I have to ensure access to my devices and data during such an event?I’d appreciate any advice or strategies for preparing for this kind of situation.
https://news.ycombinator.com/item?id=43141235

In [ ]:
df

,Title,User,Relative time,Date,Time,Score,Link,Question
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065,What are you working on? Any new ideas that y...
1,"Ask HN: Former devs who can't get a job, what ...",throw81398475,7 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498,"That's all.Savings are getting low, and I'm go..."
2,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,9,https://news.ycombinator.com/item?id=43166256,It has been one month since he passed and i ha...
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408,Hello HN! I believe some of you might have co...
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368,When I was learning to build websites in 2010 ...
6,Navigating a Broken Dev Culture,lightserver,1 day ago,2025-02-23,14:27:18,58,https://news.ycombinator.com/item?id=43149437,My Current Job is a Mess—But I Won’t Let It De...
7,Ask HN: Do you practice lucid dreaming?,raunometsa,2 days ago,2025-02-22,12:45:26,13,https://news.ycombinator.com/item?id=43138523,Hey!I know this is a question we're not usuall...
8,Ask HN: Tired of startups â€“ want a normal jo...,mertleee,4 days ago,2025-02-21,00:59:57,95,https://news.ycombinator.com/item?id=43122800,None
9,Ask HN: What happened to all those metaverse p...,herval,4 hours ago,2025-02-24,23:57:08,6,https://news.ycombinator.com/item?id=43166405,NaN
10,Ask HN: Are there online communities for singl...,indulona,2 days ago,2025-02-22,12:47:53,5,https://news.ycombinator.com/item?id=43138540,I am wondering if there are any online communi...
12,Ask HN: Anyone building a non AI product/startup?,codegeek,10 hours ago,2025-02-24,17:46:16,5,https://news.ycombinator.com/item?id=43162490,AI is an exciting technology that is surely ch...
13,Ask HN: Why is Cursor IDE accessing all my env...,iyn,3 days ago,2025-02-21,20:07:29,14,https://news.ycombinator.com/item?id=43132313,Recently I tried playing with https://www.curs...
14,Ask HN: What fiction/non-fiction book should e...,Eavolution,7 days ago,2025-02-18,00:40:33,35,https://news.ycombinator.com/item?id=43084739,This should be interpreted in the broadest sen...
15,Ask HN: Advice for someone who stagnated in th...,justonemore,2 days ago,2025-02-23,03:49:26,10,https://news.ycombinator.com/item?id=43146311,Hi HN. 50 year old here. I had a mixed career ...
17,Ask HN: Why is it taking so long to build comp...,louisfialho,2 days ago,2025-02-23,01:19:39,10,https://news.ycombinator.com/item?id=43145225,I'm not a PhD but I assume training computer c...
18,"Ask HN: Tips to make a pitch for ""acquihire of...",rglullis,2 days ago,2025-02-22,10:00:30,2,https://news.ycombinator.com/item?id=43137645,"This could also be called ""How can I pitch mys..."
19,Tell HN: Generational Gap,yonisto,2 days ago,2025-02-22,09:21:37,4,https://news.ycombinator.com/item?id=43137496,"So this week, I was teaching a new employee ab..."
20,Ask HN: A retrofitted C dialect?,anqurvanillapy,2 days ago,2025-02-22,08:11:45,7,https://news.ycombinator.com/item?id=43137171,"Hi I'm Anqur, a senior software engineer with ..."
21,Ask HN: How do you use local LLMs?,Haeuserschlucht,3 days ago,2025-02-21,08:52:01,7,https://news.ycombinator.com/item?id=43125486,"What applications(as in use cases, not in soft..."
23,Ask HN: How can I prepare my digital life for ...,mwinatschek,4 days ago,2025-02-20,09:16:45,30,https://news.ycombinator.com/item?id=43112703,I'm from Germany and currently rely on macOS a...
24,"I'm broke and non-technical, trying to develop...",vyasaveda,2 days ago,2025-02-22,17:47:25,5,https://news.ycombinator.com/item?id=43141235,"Before COVID, I started a marketing and consul..."
25,Ask HN: Did you grow up with adventure games a...,HellDunkel,10 hours ago,2025-02-24,17:48:07,7,https://news.ycombinator.com/item?id=43162513,I grew up with sierra adventure games and thes...
26,Ask HN: How can I get my 7-year-old started wi...,johnz,4 days ago,2025-02-20,22:43:53,9,https://news.ycombinator.com/item?id=43121372,"I started my career as a front-end developer, ..."
27,How to create LLM-driven tiny gnome robots?,r33b33,6 days ago,2025-02-18,12:54:51,13,https://news.ycombinator.com/item?id=43088935,"You know, like in the movie ""The Borrowers"". S..."
28,Ask HN: Dot EU domain instead of dot com?,skwee357,3 days ago,2025-02-21,09:25:03,9,https://news.ycombinator.com/item?id=43125655,I'm working on a service that targets mainly E...
29,How do you approach appealing to formal senior...,begoon,12 hours ago,2025-02-24,16:05:48,6,https://news.ycombinator.com/item?id=43161112,How do you approach appealing to formal senior...

In [ ]:
df2 = df.dropna(subset=["Question"])
df2

,Title,User,Relative time,Date,Time,Score,Link,Question
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065,What are you working on? Any new ideas that y...
1,"Ask HN: Former devs who can't get a job, what ...",throw81398475,7 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498,"That's all.Savings are getting low, and I'm go..."
2,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,9,https://news.ycombinator.com/item?id=43166256,It has been one month since he passed and i ha...
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408,Hello HN! I believe some of you might have co...
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368,When I was learning to build websites in 2010 ...
6,Navigating a Broken Dev Culture,lightserver,1 day ago,2025-02-23,14:27:18,58,https://news.ycombinator.com/item?id=43149437,My Current Job is a Mess—But I Won’t Let It De...
7,Ask HN: Do you practice lucid dreaming?,raunometsa,2 days ago,2025-02-22,12:45:26,13,https://news.ycombinator.com/item?id=43138523,Hey!I know this is a question we're not usuall...
10,Ask HN: Are there online communities for singl...,indulona,2 days ago,2025-02-22,12:47:53,5,https://news.ycombinator.com/item?id=43138540,I am wondering if there are any online communi...
12,Ask HN: Anyone building a non AI product/startup?,codegeek,10 hours ago,2025-02-24,17:46:16,5,https://news.ycombinator.com/item?id=43162490,AI is an exciting technology that is surely ch...
13,Ask HN: Why is Cursor IDE accessing all my env...,iyn,3 days ago,2025-02-21,20:07:29,14,https://news.ycombinator.com/item?id=43132313,Recently I tried playing with https://www.curs...
14,Ask HN: What fiction/non-fiction book should e...,Eavolution,7 days ago,2025-02-18,00:40:33,35,https://news.ycombinator.com/item?id=43084739,This should be interpreted in the broadest sen...
15,Ask HN: Advice for someone who stagnated in th...,justonemore,2 days ago,2025-02-23,03:49:26,10,https://news.ycombinator.com/item?id=43146311,Hi HN. 50 year old here. I had a mixed career ...
17,Ask HN: Why is it taking so long to build comp...,louisfialho,2 days ago,2025-02-23,01:19:39,10,https://news.ycombinator.com/item?id=43145225,I'm not a PhD but I assume training computer c...
18,"Ask HN: Tips to make a pitch for ""acquihire of...",rglullis,2 days ago,2025-02-22,10:00:30,2,https://news.ycombinator.com/item?id=43137645,"This could also be called ""How can I pitch mys..."
19,Tell HN: Generational Gap,yonisto,2 days ago,2025-02-22,09:21:37,4,https://news.ycombinator.com/item?id=43137496,"So this week, I was teaching a new employee ab..."
20,Ask HN: A retrofitted C dialect?,anqurvanillapy,2 days ago,2025-02-22,08:11:45,7,https://news.ycombinator.com/item?id=43137171,"Hi I'm Anqur, a senior software engineer with ..."
21,Ask HN: How do you use local LLMs?,Haeuserschlucht,3 days ago,2025-02-21,08:52:01,7,https://news.ycombinator.com/item?id=43125486,"What applications(as in use cases, not in soft..."
23,Ask HN: How can I prepare my digital life for ...,mwinatschek,4 days ago,2025-02-20,09:16:45,30,https://news.ycombinator.com/item?id=43112703,I'm from Germany and currently rely on macOS a...
24,"I'm broke and non-technical, trying to develop...",vyasaveda,2 days ago,2025-02-22,17:47:25,5,https://news.ycombinator.com/item?id=43141235,"Before COVID, I started a marketing and consul..."
25,Ask HN: Did you grow up with adventure games a...,HellDunkel,10 hours ago,2025-02-24,17:48:07,7,https://news.ycombinator.com/item?id=43162513,I grew up with sierra adventure games and thes...
26,Ask HN: How can I get my 7-year-old started wi...,johnz,4 days ago,2025-02-20,22:43:53,9,https://news.ycombinator.com/item?id=43121372,"I started my career as a front-end developer, ..."
27,How to create LLM-driven tiny gnome robots?,r33b33,6 days ago,2025-02-18,12:54:51,13,https://news.ycombinator.com/item?id=43088935,"You know, like in the movie ""The Borrowers"". S..."
28,Ask HN: Dot EU domain instead of dot com?,skwee357,3 days ago,2025-02-21,09:25:03,9,https://news.ycombinator.com/item?id=43125655,I'm working on a service that targets mainly E...
29,How do you approach appealing to formal senior...,begoon,12 hours ago,2025-02-24,16:05:48,6,https://news.ycombinator.com/item?id=43161112,How do you approach appealing to formal senior...

In [ ]:
URL = "https://news.ycombinator.com/item?id=39171079"
r = requests.get(URL)
soup = BeautifulSoup(r.content, 'html.parser')
comments = soup.find_all("div", class_="comment")
count = 0
for comment in comments:
  count = count +1
  comment = comment.get_text(strip=True)
  print(comment)

print("count = ", count)

It definitely ruined a friendship of mine. His startup was making insane amounts of money. He offered me a position, then his business priorities changed and forced me into a poor role with no long term prospects. I struggled in that new role and he noticed that. He then terminated our agreement two months early.There are reasons he's right about what he did and there are reasons I'm right about being upset about it but it definitely cost us our friendship.I think back that if he had operated with integrity and honored his agreement to keep me on for two extra months it would have not been upsetting to leave then. As it was it left me scrambling with three small kids.The lesson to me is that even if the startup is flush with cash, there will be issues. How the founder manages those issues matters.I recall when I had my startup I did a bunch of business coaching and really had to take on a lot of uncomfortable things about myself. I'm grateful for that. I invited him many times to participate in that work and he never did. When the money is good you think you don't need it.
On one side you were a employee, so he needs to treat you kinda like a regular employee. If what he did to you would be normal for another employee, then he has a point. Doing different could even be seem as unfair for the other employees.On the other side you are a friend, I really don't know what he could have done differently, very hard.
Wouldn't the right thing to have done for any employee, friend or not, be to simply pay them the remaining two months but let them go early?
> As it was it left me scrambling with three small kids.you did not mention whether this early termination was communicated beforehand.nevertheless this person probably never was your friend. sry
> nevertheless this person probably never was your friend. sryNo, it's completely common for friendships to break down over business.Very few friendships are robust enough to survive one party costing the other $20,000.
It's wild that you said that amount because that was exactly the number.I have other friendships that have been tested for similar amounts that have survived. But, it leaves a mark.I had an ex-employee who worked for me under starvation wages in a startup long ago. He was upset about that and some tax implications, and brought it up with me. I gave him a smallish lump sum and enabled him to put a down payment on a house. I need to ask him about that, it was really brave to ask me to clean something up, and I never did that with the friend from the OP. I wonder if it would have gone differently.I'm seeing a lot of people in my circle struggling right now. I bet 2024 is going to be a bad year for friendships.
Wow. $20k seems like a paltry sum to end a friendship over.
This forum is so out of touch with reality sometimes I'm just left blinking and shaking my head. 20,000 dollars is an enormous amount of money to a supermajority of people in the developed world. Almost half an annual wage for most industrial workers in the EU and US.
thou, the question is, wheather you can buy a friendship with the money. the answer is probably, no, hence it's not worth it.
$500,000 USD is a middle class wage in the Bay Area /s
That's a very privileged perspective to have... I know plenty of people for whom a sudden $20k shortfall would be existential.
I probably could have phrased it better, but my comment was taken out of context. What I mean is $20k is a paltry sum for a tech startup to screw someone over for. I don’t think it’s a small sum for most individual wage earners (especially with young children).
Really? Try glancing the sorts of wages and earnings that literally 99% of the world's population makes on downwards and you'll quickly see that it's far, far from "paltry" for the vast majority of people.
I'm unsure why my sibling comments seem to think the sentence ends at "sum".Is it possible to buy a real friendship for $20k? Is a friendship of many years worth more to you than $20k - would you stop being friends if someone else offered you that much to do so?This isn't a paltry sum of money, it is a paltry sum to end a friendship over.
An interesting thought experiment to me is how much I would be willing to spend to preserve a friendship. Various situations over the past few years, including some businesses with friends made me think about hypotheticals.
I struggle to find any situation where 20k is a paltry sum
I was going to say "maybe to launch a rocket into space" but then I realized SpaceX has made even that much cheaper than it used to be. (Still more than 20K though :))
> Very few friendships are robust enough to survive one party costing the other $20,000.That probably depends on how critical that $20k is to you.  If it's your only $20k, then yeah it'd be much more impactful than if it's just one of many.
Certainly, if the loss means you encounter financial hardship, you'd be understandably resentful.But even when the loss causes little financial hardship, it could put a strain on a relationship.Imagine you invest $20k in my business and I buy a $5k industrial juicing machine for the office so my staff can have freshly squeezed orange juice. I tell you that employees expect free luxury food these days and it'll make hiring much easier. You have your doubts.If the business does well and we both make a big profit - we're both happy. You still think the juicer was a bit extravagant - but it all worked out in the end, and maybe I was right that it helped with recruitment.But if the business fails - you might resent the fact I wasted $5k of your money on a juicer.
So we can put a price on friendship? (/s)
obviously we can't.hence no money can be enough to compensate for a friendship
When we started working together I suggested a six month trial, and he said let's do 12 months. That role was perfect and I had the skills for it. 6 months in his business priorities changed, so he pushed me into a new role. Then, at the ten month mark said "I just don't have any more work for you."It all depends on what is a friend. Your statement makes me question what makes a good friend. I don't really know right now. It is a lot harder to make them at 50, of that I'm sure.
"friends are people that show up when it's not convenient for them" - my mum
I've seen friendships break down over one person not doing the dishes for a prolonged period.The issue with friendships is usually there's some expectation of being in it 'together' and to put in some sort of similar effort, despite the major power imbalance of employee vs. cofounder.If the founder feels their friend is for instance, giving say half the effort they are (which I feel personally is reasonable for an early stage employee, that they have a life), they may feel their friend is violating some notion of trust, despite the friend getting maybe 1% equity at best.
One of my favorite quotes is attributed to Saint Augustine:"If two friends ask you to judge a dispute, don't accept, because you will lose one friend; on the other hand, if two strangers come with the same request, accept, because you will gain one friend."It sort of applies, here, as well.
Years back a coworker and I were having a small interpersonal disagreement. My supervisor declined to get involved, basically told us to sort it out without wasting work time.It wasn’t anything serious enough to involve HR (in my eyes anyway), but I spent a solid while annoyed with this response. It took me a solid five years to realize he had made the right overall decision.He had not played favorites, did not burn any bridges, and caused at worst a mild annoyance to both of us rather than potentially leading one of us to quit.
That’s very PC, but there’s a fine line between that and not showing leadership. What good is a leader who doesn’t standup for what’s right? That’s annoying for the person who is right
If two friends ask you to judge a dispute, and youdon'taccept... You might loose two friends since both of them think they are right and will not understand you do not support them.
Then they aren't my friends. If a "friendship" is that delicate, I'm better off, without.I have extremely close friends, with whom I have deep, fundamental, disagreements.I have absolutely no problem, telling people that they are dreaming, if they think they can extort me into taking their side."Support" can mean that I won't participate in destructive behavior. I often can't stop others from doing it, but I can make sure I don't get dragged into the cesspool, and be ready with towels and a power washer, when they get out.
This same exact argument could be applied to the first saying as well.
That is correct. It's just a quote. Real life tends to have more subtlety.
If they are that sensitive, I can also be sensitive and ask them why they've involved me in a conundrum where I stand to gain nothing.
That would be a mildly weird reaction to "I don't want to get involved in your dispute", in _most_ cases. (I think there are edge-cases where not wanting to get involved might in itself be taking a stand, but certainly for everyday disputes most people wouldn't take offence to "I don't want to get involved").
I would trust they would instead be happy to have such a socially intelligent friend once the dust has cooled.
The friend you gain will be a fairweather friend though, most likely.If the person you disagrees with becomes your friend then that’s a good sign!
Didn’t end up going to work for the friend, but the situation still strained the friendship.An engineer I worked with for several years (and became friends with outside of work) started his own company, a couple of years later he recruited me to join as his business was taking off. He’d also brought in a business guy who seemed to put in lots of processes including a mandatory take-home coding assignment as part of their interview process.So anyhow, this guy who I’d worked alongside for years, who’d seen plenty of my code and wanted me to join his company, was going to make me do this homework to get an offer.So I did a verrry basic solution to this thing and sent it back. A bit later I got an email from someone in their office that they regretted they didn’t have any positions that fit my experience.Later my friend (and his wife) encouraged me to do the homework thing again but I laughed them off. I didn’t want to work for a small company that somehow had hamstrung itself with unnecessary processes that kept the founder from hiring someone he wanted to hire.A few years later they sold and a couple engineers I know made multiple millions. So yeah, I dunno, I felt good about my decision at the time, but in retrospect it would have been better to act like any job seeker and just go to work for my friend.Your mileage will certainly vary.
>So anyhow, this guy who I’d worked alongside for years, who’d seen plenty of my code and wanted me to join his company, was going to make me do this homework to get an offer.Had your friend delegated the engineering hiring decisions/process to someone else, and was trying not to step on their toes?Or friend had instituted the process, and didn't think it would go well with the other people, if you looked like a nepotism hire who bypassed the process?Or friend was trying to put you in your employee place (where you had to meet his process), or otherwise was getting a bit full of himself, or a bit sleep-deprived and nutty?
> Or friend was trying to put you in your employee place (where you had to meet his process), or otherwise was getting a bit full of himself, or a bit sleep-deprived and nutty?This would be a strange take. CEO shouldn't be letting people in on the nod. If hiring is someone else's job, CEO shouldn't be overriding. At best suggesting candidates but saying that it's totally the hiring manager's call.If a candidate didn't pass a hiring process because they didn't put effort in as they felt they should get the job due to connections, I would agree with the company's decision.
The purpose of a hiring process (as in take home assignment) is to see that the person is competent to do the job. It was already established that he was. So following a formal process is a stupid waste of time (on both ends) that has nothing to do with strengthening the company and is simply an unnecessary ego trip. The company disqualified itself.
How was it established?
They mean it was established by the CEO's experience with him as an engineer.To the company it was never, and as high a recommendation as the CEO would be; most people would agree they did the right thing. Unless you're hired before a hiring manager or whomever is doing the hiring you should follow the process. If you treat it like a joke because you feel entitled by your connections then be willing to accept the outcome.
You are describing the HR person's ego trip.That person should be fired, for being unprofessional and for inability to adapt to a trivial non-standard situation ("normally we test the applicant's technical competency with a take-home test; now it already has been established; so I need to stop wasting everybody's time and spend my time doing something actually useful".)Obviously, HR could still be useful in establishing a culture fit, but even then it's pretty much a formality since the CEO worked with and recommended the guy.
I think the fundamental difference is just that you think that the technical competency has been established, and the hiring manager did not. Given the candidate did the exercise, but did it badly, I think the hiring manager was right.None of the other stuff you're saying is relevant. No point doing armchair psychoanalysis.
The only thing the candidate did wrong was to even start the assignment. Either communicate that it is a waste of time and refuse to do it, or decide to do it and do it properly. No point in half-assing anything in life.
Indeed. That's why the HR person (or whoever it was) wasn't on a fireable ego trip. They just enforced their normal process that they use to not let people slip in through nepotism.
The process that they designed. This means they can change it and the excuse "I am simply following the pre-determined process" will not work.Clearly, the process (of cutting technically incompetent people while letting through the technically competent ones) is not working properly; that alone is fireable incompetency ("You had only one job and you failed at it!").Another fireable thing is that HR does not understand that they are under the CEO, they are implementing the CEO's vision, in the way he envisioned. But instead of that, HR is indeed ego-tripping.
If I was a hiring manager who set up a hiring process to evaluate candidates, and someone did poorly on it but the CEO came and said "no no, hire this person anyway, I know they failed but it's fine" I would quit.
If I were a CEO trying to build a successful company and found a willing competent worker, whose hiring would fail because of the hiring manager's ego and inability to adapt and do what's right, I would consider it a purposeful sabotage and would fire the drag-downer.
You keep assuming ego. No ego is required to make sure people are put through the same hiring process.
Sure, but I think it's likely you haven't worked on high performing teams if you think this.
Not an argument.
It's one possibility, and I would bet money that it happens sometimes.  I itemized it last because it seems the least-likely of those possibilities.I think it's kinda intuitive that this could happen.  Startups tend to require early people to figure out and apply a ton of diverse skills.  You can guess many founders will think "I'm hiring my friend, and I don't know how the power dynamic will work out".  And some percentage of those will then think, "...so I should establish from the start that they're the employee, to avoid problems later."  And from there you get the dance-for-our-approval tests that so many techbros have cargo-culted.
Tbf the hiring already said they don't have the position open, and rather than doing something about it, the CEO asked OP to make another homework, which is also not a guarantee. Another round of interview may be fine, but another homework, that's laughable.OTOH, it may be that the company already have one or some super programmer, that he/she carry the company to success. Having OP, if we assume is another super programmer, may halt the company rather than improve it.
Separate from whether the process was any good, your friend wasn't necessarily wrong not to make you an exception to it. Nepotism can be pretty rough on a team's morale.
Programmers are the least capable engineers but the most cocksure and entitledAm an EE and I cannot stand the CS people at work. Oh you wrapped well known math in machine syntax sugar, none of which you invented, or defined? High 5, edgelord.
If I was another employee or applicant, I would be legitimately upset if someone didn't have to jump through the same hoops that I did simply because he knew the boss.
That's insane. My CEO is 60 years old and has built and sold 4 different companies before this. His network of former colleagues is deep. It would be childish for me to believe all of the potential people from his former working relationships should be beholden to the exact same homework assignments as someone who is a complete stranger.
Yeah, if I were someone working at a company having gone through the "normal" hiring process and then someone new joined my team and I found out they didn't have to go through it because they thought it was a waste of time and they were friends with the founder, that would feel pretty shitty.
it depends on their previous relationship. if they have worked together before then the test should be redundant. so why should i feel bothered that they didn't have to do a test?
If the founder is not really involved with the hiring team then you are essentially going over them without them having any idea how you work.While I know what you're saying that the founder is vouching for your experience, its still going to cause friction, I think. Especially, again, to all the people that fought for the job.
sure, i am thinking of cases where the founder is still involved with hiring, and especially more so, where the founder is the lead developer and still coding.i agree with you that once the company is large enough that the founder is no longer involved with hiring decisions then they should not just go over the hiring team.more specifically, as in this article:https://www.cio.com/article/236189/5-reasons-ceos-should-be-...i am talking about smaller companies that don't yet have senior management and HR teams
Did you ask them if they were advised by HR/legal to do these tests to everyone to avoid possible future discrimination lawsuits?
That is such a bizarre story.
I can see your perspective, and it would be reasonable for them to say, "I already know this guy's work. He doesn't have to do the take-home.", which is not like saying, "I already know this guy from [irrelevant source]." I would do this, and have before.You also could have just smiled and nodded and actually done a good job to demonstrate your skills. It looks to me like you pulled your punches.
Was it 10, 100 employees at the time?
Poorly. I did all the work while my friend goofed off and ran personal errands all day. The friend eventually made a fortune selling their equity and retired young. I did not get awarded the same privilege. We no longer speak and I still get angry when I think about that.On the other hand, I have made good friends through the workplace who I would start a startup with in a heartbeat.

In [ ]:
type(comments)

bs4.element.ResultSet

In [ ]:
URL = "https://news.ycombinator.com/item?id=39171079"
r = requests.get(URL)
soup = BeautifulSoup(r.content, 'html.parser')
comments = soup.find("span", class_="comhead")
user_element = comments.find("a", class_="hnuser")
user = user_element.get_text(strip=True)
age_element = comments.find("span", class_="age")
age = age_element["title"]
date_time_string = age.split()[0]  # Extract only "YYYY-MM-DDTHH:MM:SS"

try:
    datetime_object = datetime.fromisoformat(date_time_string)
    date = datetime_object.date()
    time = datetime_object.time()
except ValueError as e:
    print(f"Error parsing datetime: {e}")
    date = None
    time = None  # Handle errors gracefully

print(date)
print(user)

2024-01-29
xrd

In [ ]:
URL = "https://news.ycombinator.com/item?id=39171079"

r = requests.get(URL)
soup = BeautifulSoup(r.content, 'html.parser')

comments = soup.find("table", class_="comment-tree")

com = comments.find_all("tr", class_="athing comtr")

for comment in com:
    c = comment.find("span", class_="comhead")
    user_element = c.find("a", class_="hnuser")
    user = user_element.get_text(strip=True) if user_element else "Unknown"

    age_element = c.find("span", class_="age")

    if age_element and age_element.has_attr("title"):
        age = age_element["title"]
        date_time_string = age.split()[0]

        try:
            datetime_object = datetime.fromisoformat(date_time_string)
            date = datetime_object.date()
            time = datetime_object.time()
        except ValueError as e:
            print(f"Error parsing datetime: {e}")
            date = None
            time = None
    else:
        date = None
        time = None

    text = comment.find("div", class_="comment")
    comment_content = text.get_text(strip=True) if text else "No comment"

    print(f"Date: {date}")
    print(f"User: {user}")
    print(f"Comment: {comment_content}")
    print("---")

Date: 2024-01-29
User: xrd
Comment: It definitely ruined a friendship of mine. His startup was making insane amounts of money. He offered me a position, then his business priorities changed and forced me into a poor role with no long term prospects. I struggled in that new role and he noticed that. He then terminated our agreement two months early.There are reasons he's right about what he did and there are reasons I'm right about being upset about it but it definitely cost us our friendship.I think back that if he had operated with integrity and honored his agreement to keep me on for two extra months it would have not been upsetting to leave then. As it was it left me scrambling with three small kids.The lesson to me is that even if the startup is flush with cash, there will be issues. How the founder manages those issues matters.I recall when I had my startup I did a bunch of business coaching and really had to take on a lot of uncomfortable things about myself. I'm grateful for that. I invited him many times to participate in that work and he never did. When the money is good you think you don't need it.
---
Date: 2024-01-29
User: mercenario
Comment: On one side you were a employee, so he needs to treat you kinda like a regular employee. If what he did to you would be normal for another employee, then he has a point. Doing different could even be seem as unfair for the other employees.On the other side you are a friend, I really don't know what he could have done differently, very hard.
---
Date: 2024-01-31
User: solardev
Comment: Wouldn't the right thing to have done for any employee, friend or not, be to simply pay them the remaining two months but let them go early?
---
Date: 2024-01-29
User: geraldhh
Comment: > As it was it left me scrambling with three small kids.you did not mention whether this early termination was communicated beforehand.nevertheless this person probably never was your friend. sry
---
Date: 2024-01-29
User: michaelt
Comment: > nevertheless this person probably never was your friend. sryNo, it's completely common for friendships to break down over business.Very few friendships are robust enough to survive one party costing the other $20,000.
---
Date: 2024-01-29
User: xrd
Comment: It's wild that you said that amount because that was exactly the number.I have other friendships that have been tested for similar amounts that have survived. But, it leaves a mark.I had an ex-employee who worked for me under starvation wages in a startup long ago. He was upset about that and some tax implications, and brought it up with me. I gave him a smallish lump sum and enabled him to put a down payment on a house. I need to ask him about that, it was really brave to ask me to clean something up, and I never did that with the friend from the OP. I wonder if it would have gone differently.I'm seeing a lot of people in my circle struggling right now. I bet 2024 is going to be a bad year for friendships.
---
Date: 2024-01-29
User: catlifeonmars
Comment: Wow. $20k seems like a paltry sum to end a friendship over.
---
Date: 2024-01-29
User: dbspin
Comment: This forum is so out of touch with reality sometimes I'm just left blinking and shaking my head. 20,000 dollars is an enormous amount of money to a supermajority of people in the developed world. Almost half an annual wage for most industrial workers in the EU and US.
---
Date: 2024-01-30
User: geraldhh
Comment: thou, the question is, wheather you can buy a friendship with the money. the answer is probably, no, hence it's not worth it.
---
Date: 2024-01-29
User: felixg3
Comment: $500,000 USD is a middle class wage in the Bay Area /s
---
Date: 2024-01-29
User: InitialLastName
Comment: That's a very privileged perspective to have... I know plenty of people for whom a sudden $20k shortfall would be existential.
---
Date: 2024-01-31
User: catlifeonmars
Comment: I probably could have phrased it better, but my comment was taken out of context. What I mean is $20k is a paltry sum for a tech startup to screw someone over for. I don’t think it’s a small sum for most individual wage earners (especially with young children).
---
Date: 2024-01-29
User: southernplaces7
Comment: Really? Try glancing the sorts of wages and earnings that literally 99% of the world's population makes on downwards and you'll quickly see that it's far, far from "paltry" for the vast majority of people.
---
Date: 2024-02-03
User: averageRoyalty
Comment: I'm unsure why my sibling comments seem to think the sentence ends at "sum".Is it possible to buy a real friendship for $20k? Is a friendship of many years worth more to you than $20k - would you stop being friends if someone else offered you that much to do so?This isn't a paltry sum of money, it is a paltry sum to end a friendship over.
---
Date: 2024-01-29
User: drpgq
Comment: An interesting thought experiment to me is how much I would be willing to spend to preserve a friendship. Various situations over the past few years, including some businesses with friends made me think about hypotheticals.
---
Date: 2024-01-29
User: blantonl
Comment: I struggle to find any situation where 20k is a paltry sum
---
Date: 2024-01-29
User: elevatedastalt
Comment: I was going to say "maybe to launch a rocket into space" but then I realized SpaceX has made even that much cheaper than it used to be. (Still more than 20K though :))
---
Date: 2024-01-29
User: justinclift
Comment: > Very few friendships are robust enough to survive one party costing the other $20,000.That probably depends on how critical that $20k is to you.  If it's your only $20k, then yeah it'd be much more impactful than if it's just one of many.
---
Date: 2024-01-29
User: michaelt
Comment: Certainly, if the loss means you encounter financial hardship, you'd be understandably resentful.But even when the loss causes little financial hardship, it could put a strain on a relationship.Imagine you invest $20k in my business and I buy a $5k industrial juicing machine for the office so my staff can have freshly squeezed orange juice. I tell you that employees expect free luxury food these days and it'll make hiring much easier. You have your doubts.If the business does well and we both make a big profit - we're both happy. You still think the juicer was a bit extravagant - but it all worked out in the end, and maybe I was right that it helped with recruitment.But if the business fails - you might resent the fact I wasted $5k of your money on a juicer.
---
Date: 2024-01-29
User: polynomial
Comment: So we can put a price on friendship? (/s)
---
Date: 2024-02-07
User: geraldhh
Comment: obviously we can't.hence no money can be enough to compensate for a friendship
---
Date: 2024-01-29
User: xrd
Comment: When we started working together I suggested a six month trial, and he said let's do 12 months. That role was perfect and I had the skills for it. 6 months in his business priorities changed, so he pushed me into a new role. Then, at the ten month mark said "I just don't have any more work for you."It all depends on what is a friend. Your statement makes me question what makes a good friend. I don't really know right now. It is a lot harder to make them at 50, of that I'm sure.
---
Date: 2024-02-10
User: geraldhh
Comment: "friends are people that show up when it's not convenient for them" - my mum
---
Date: 2024-01-29
User: brandall10
Comment: I've seen friendships break down over one person not doing the dishes for a prolonged period.The issue with friendships is usually there's some expectation of being in it 'together' and to put in some sort of similar effort, despite the major power imbalance of employee vs. cofounder.If the founder feels their friend is for instance, giving say half the effort they are (which I feel personally is reasonable for an early stage employee, that they have a life), they may feel their friend is violating some notion of trust, despite the friend getting maybe 1% equity at best.
---
Date: 2024-01-29
User: ChrisMarshallNY
Comment: One of my favorite quotes is attributed to Saint Augustine:"If two friends ask you to judge a dispute, don't accept, because you will lose one friend; on the other hand, if two strangers come with the same request, accept, because you will gain one friend."It sort of applies, here, as well.
---
Date: 2024-01-29
User: donatj
Comment: Years back a coworker and I were having a small interpersonal disagreement. My supervisor declined to get involved, basically told us to sort it out without wasting work time.It wasn’t anything serious enough to involve HR (in my eyes anyway), but I spent a solid while annoyed with this response. It took me a solid five years to realize he had made the right overall decision.He had not played favorites, did not burn any bridges, and caused at worst a mild annoyance to both of us rather than potentially leading one of us to quit.
---
Date: 2024-01-29
User: abc_lisper
Comment: That’s very PC, but there’s a fine line between that and not showing leadership. What good is a leader who doesn’t standup for what’s right? That’s annoying for the person who is right
---
Date: 2024-01-29
User: illys
Comment: If two friends ask you to judge a dispute, and youdon'taccept... You might loose two friends since both of them think they are right and will not understand you do not support them.
---
Date: 2024-01-29
User: ChrisMarshallNY
Comment: Then they aren't my friends. If a "friendship" is that delicate, I'm better off, without.I have extremely close friends, with whom I have deep, fundamental, disagreements.I have absolutely no problem, telling people that they are dreaming, if they think they can extort me into taking their side."Support" can mean that I won't participate in destructive behavior. I often can't stop others from doing it, but I can make sure I don't get dragged into the cesspool, and be ready with towels and a power washer, when they get out.
---
Date: 2024-01-29
User: ensignavenger
Comment: This same exact argument could be applied to the first saying as well.
---
Date: 2024-01-29
User: ChrisMarshallNY
Comment: That is correct. It's just a quote. Real life tends to have more subtlety.
---
Date: 2024-01-29
User: spiderfarmer
Comment: If they are that sensitive, I can also be sensitive and ask them why they've involved me in a conundrum where I stand to gain nothing.
---
Date: 2024-01-29
User: rsynnott
Comment: That would be a mildly weird reaction to "I don't want to get involved in your dispute", in _most_ cases. (I think there are edge-cases where not wanting to get involved might in itself be taking a stand, but certainly for everyday disputes most people wouldn't take offence to "I don't want to get involved").
---
Date: 2024-01-29
User: brandall10
Comment: I would trust they would instead be happy to have such a socially intelligent friend once the dust has cooled.
---
Date: 2024-02-02
User: quickthrower2
Comment: The friend you gain will be a fairweather friend though, most likely.If the person you disagrees with becomes your friend then that’s a good sign!
---
Date: 2024-01-29
User: ytdytvhxgydvhh
Comment: Didn’t end up going to work for the friend, but the situation still strained the friendship.An engineer I worked with for several years (and became friends with outside of work) started his own company, a couple of years later he recruited me to join as his business was taking off. He’d also brought in a business guy who seemed to put in lots of processes including a mandatory take-home coding assignment as part of their interview process.So anyhow, this guy who I’d worked alongside for years, who’d seen plenty of my code and wanted me to join his company, was going to make me do this homework to get an offer.So I did a verrry basic solution to this thing and sent it back. A bit later I got an email from someone in their office that they regretted they didn’t have any positions that fit my experience.Later my friend (and his wife) encouraged me to do the homework thing again but I laughed them off. I didn’t want to work for a small company that somehow had hamstrung itself with unnecessary processes that kept the founder from hiring someone he wanted to hire.A few years later they sold and a couple engineers I know made multiple millions. So yeah, I dunno, I felt good about my decision at the time, but in retrospect it would have been better to act like any job seeker and just go to work for my friend.Your mileage will certainly vary.
---
Date: 2024-01-29
User: neilv
Comment: >So anyhow, this guy who I’d worked alongside for years, who’d seen plenty of my code and wanted me to join his company, was going to make me do this homework to get an offer.Had your friend delegated the engineering hiring decisions/process to someone else, and was trying not to step on their toes?Or friend had instituted the process, and didn't think it would go well with the other people, if you looked like a nepotism hire who bypassed the process?Or friend was trying to put you in your employee place (where you had to meet his process), or otherwise was getting a bit full of himself, or a bit sleep-deprived and nutty?
---
Date: 2024-01-29
User: robertlagrant
Comment: > Or friend was trying to put you in your employee place (where you had to meet his process), or otherwise was getting a bit full of himself, or a bit sleep-deprived and nutty?This would be a strange take. CEO shouldn't be letting people in on the nod. If hiring is someone else's job, CEO shouldn't be overriding. At best suggesting candidates but saying that it's totally the hiring manager's call.If a candidate didn't pass a hiring process because they didn't put effort in as they felt they should get the job due to connections, I would agree with the company's decision.
---
Date: 2024-01-29
User: machomaster
Comment: The purpose of a hiring process (as in take home assignment) is to see that the person is competent to do the job. It was already established that he was. So following a formal process is a stupid waste of time (on both ends) that has nothing to do with strengthening the company and is simply an unnecessary ego trip. The company disqualified itself.
---
Date: 2024-01-29
User: robertlagrant
Comment: How was it established?
---
Date: 2024-01-29
User: wifipunk
Comment: They mean it was established by the CEO's experience with him as an engineer.To the company it was never, and as high a recommendation as the CEO would be; most people would agree they did the right thing. Unless you're hired before a hiring manager or whomever is doing the hiring you should follow the process. If you treat it like a joke because you feel entitled by your connections then be willing to accept the outcome.
---
Date: 2024-01-29
User: machomaster
Comment: You are describing the HR person's ego trip.That person should be fired, for being unprofessional and for inability to adapt to a trivial non-standard situation ("normally we test the applicant's technical competency with a take-home test; now it already has been established; so I need to stop wasting everybody's time and spend my time doing something actually useful".)Obviously, HR could still be useful in establishing a culture fit, but even then it's pretty much a formality since the CEO worked with and recommended the guy.
---
Date: 2024-01-30
User: robertlagrant
Comment: I think the fundamental difference is just that you think that the technical competency has been established, and the hiring manager did not. Given the candidate did the exercise, but did it badly, I think the hiring manager was right.None of the other stuff you're saying is relevant. No point doing armchair psychoanalysis.
---
Date: 2024-01-30
User: machomaster
Comment: The only thing the candidate did wrong was to even start the assignment. Either communicate that it is a waste of time and refuse to do it, or decide to do it and do it properly. No point in half-assing anything in life.
---
Date: 2024-02-01
User: robertlagrant
Comment: Indeed. That's why the HR person (or whoever it was) wasn't on a fireable ego trip. They just enforced their normal process that they use to not let people slip in through nepotism.
---
Date: 2024-02-01
User: machomaster
Comment: The process that they designed. This means they can change it and the excuse "I am simply following the pre-determined process" will not work.Clearly, the process (of cutting technically incompetent people while letting through the technically competent ones) is not working properly; that alone is fireable incompetency ("You had only one job and you failed at it!").Another fireable thing is that HR does not understand that they are under the CEO, they are implementing the CEO's vision, in the way he envisioned. But instead of that, HR is indeed ego-tripping.
---
Date: 2024-01-30
User: VirusNewbie
Comment: If I was a hiring manager who set up a hiring process to evaluate candidates, and someone did poorly on it but the CEO came and said "no no, hire this person anyway, I know they failed but it's fine" I would quit.
---
Date: 2024-01-31
User: machomaster
Comment: If I were a CEO trying to build a successful company and found a willing competent worker, whose hiring would fail because of the hiring manager's ego and inability to adapt and do what's right, I would consider it a purposeful sabotage and would fire the drag-downer.
---
Date: 2024-02-01
User: robertlagrant
Comment: You keep assuming ego. No ego is required to make sure people are put through the same hiring process.
---
Date: 2024-01-31
User: VirusNewbie
Comment: Sure, but I think it's likely you haven't worked on high performing teams if you think this.
---
Date: 2024-01-31
User: machomaster
Comment: Not an argument.
---
Date: 2024-01-29
User: neilv
Comment: It's one possibility, and I would bet money that it happens sometimes.  I itemized it last because it seems the least-likely of those possibilities.I think it's kinda intuitive that this could happen.  Startups tend to require early people to figure out and apply a ton of diverse skills.  You can guess many founders will think "I'm hiring my friend, and I don't know how the power dynamic will work out".  And some percentage of those will then think, "...so I should establish from the start that they're the employee, to avoid problems later."  And from there you get the dance-for-our-approval tests that so many techbros have cargo-culted.
---
Date: 2024-01-29
User: fendy3002
Comment: Tbf the hiring already said they don't have the position open, and rather than doing something about it, the CEO asked OP to make another homework, which is also not a guarantee. Another round of interview may be fine, but another homework, that's laughable.OTOH, it may be that the company already have one or some super programmer, that he/she carry the company to success. Having OP, if we assume is another super programmer, may halt the company rather than improve it.
---
Date: 2024-01-29
User: FreakLegion
Comment: Separate from whether the process was any good, your friend wasn't necessarily wrong not to make you an exception to it. Nepotism can be pretty rough on a team's morale.
---
Date: 2024-01-29
User: mewziq
Comment: Programmers are the least capable engineers but the most cocksure and entitledAm an EE and I cannot stand the CS people at work. Oh you wrapped well known math in machine syntax sugar, none of which you invented, or defined? High 5, edgelord.
---
Date: 2024-01-29
User: GandalfTheWhite
Comment: If I was another employee or applicant, I would be legitimately upset if someone didn't have to jump through the same hoops that I did simply because he knew the boss.
---
Date: 2024-01-29
User: Solvency

In [ ]:
df2.head()

,Title,User,Relative time,Date,Time,Score,Link,Question
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065,What are you working on? Any new ideas that y...
1,"Ask HN: Former devs who can't get a job, what ...",throw81398475,7 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498,"That's all.Savings are getting low, and I'm go..."
2,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,9,https://news.ycombinator.com/item?id=43166256,It has been one month since he passed and i ha...
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408,Hello HN! I believe some of you might have co...
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368,When I was learning to build websites in 2010 ...

In [ ]:
df2

,Title,User,Relative time,Date,Time,Score,Link,Question
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065,What are you working on? Any new ideas that y...
1,"Ask HN: Former devs who can't get a job, what ...",throw81398475,7 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498,"That's all.Savings are getting low, and I'm go..."
2,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,9,https://news.ycombinator.com/item?id=43166256,It has been one month since he passed and i ha...
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408,Hello HN! I believe some of you might have co...
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368,When I was learning to build websites in 2010 ...
6,Navigating a Broken Dev Culture,lightserver,1 day ago,2025-02-23,14:27:18,58,https://news.ycombinator.com/item?id=43149437,My Current Job is a Mess—But I Won’t Let It De...
7,Ask HN: Do you practice lucid dreaming?,raunometsa,2 days ago,2025-02-22,12:45:26,13,https://news.ycombinator.com/item?id=43138523,Hey!I know this is a question we're not usuall...
10,Ask HN: Are there online communities for singl...,indulona,2 days ago,2025-02-22,12:47:53,5,https://news.ycombinator.com/item?id=43138540,I am wondering if there are any online communi...
12,Ask HN: Anyone building a non AI product/startup?,codegeek,10 hours ago,2025-02-24,17:46:16,5,https://news.ycombinator.com/item?id=43162490,AI is an exciting technology that is surely ch...
13,Ask HN: Why is Cursor IDE accessing all my env...,iyn,3 days ago,2025-02-21,20:07:29,14,https://news.ycombinator.com/item?id=43132313,Recently I tried playing with https://www.curs...
14,Ask HN: What fiction/non-fiction book should e...,Eavolution,7 days ago,2025-02-18,00:40:33,35,https://news.ycombinator.com/item?id=43084739,This should be interpreted in the broadest sen...
15,Ask HN: Advice for someone who stagnated in th...,justonemore,2 days ago,2025-02-23,03:49:26,10,https://news.ycombinator.com/item?id=43146311,Hi HN. 50 year old here. I had a mixed career ...
17,Ask HN: Why is it taking so long to build comp...,louisfialho,2 days ago,2025-02-23,01:19:39,10,https://news.ycombinator.com/item?id=43145225,I'm not a PhD but I assume training computer c...
18,"Ask HN: Tips to make a pitch for ""acquihire of...",rglullis,2 days ago,2025-02-22,10:00:30,2,https://news.ycombinator.com/item?id=43137645,"This could also be called ""How can I pitch mys..."
19,Tell HN: Generational Gap,yonisto,2 days ago,2025-02-22,09:21:37,4,https://news.ycombinator.com/item?id=43137496,"So this week, I was teaching a new employee ab..."
20,Ask HN: A retrofitted C dialect?,anqurvanillapy,2 days ago,2025-02-22,08:11:45,7,https://news.ycombinator.com/item?id=43137171,"Hi I'm Anqur, a senior software engineer with ..."
21,Ask HN: How do you use local LLMs?,Haeuserschlucht,3 days ago,2025-02-21,08:52:01,7,https://news.ycombinator.com/item?id=43125486,"What applications(as in use cases, not in soft..."
23,Ask HN: How can I prepare my digital life for ...,mwinatschek,4 days ago,2025-02-20,09:16:45,30,https://news.ycombinator.com/item?id=43112703,I'm from Germany and currently rely on macOS a...
24,"I'm broke and non-technical, trying to develop...",vyasaveda,2 days ago,2025-02-22,17:47:25,5,https://news.ycombinator.com/item?id=43141235,"Before COVID, I started a marketing and consul..."
25,Ask HN: Did you grow up with adventure games a...,HellDunkel,10 hours ago,2025-02-24,17:48:07,7,https://news.ycombinator.com/item?id=43162513,I grew up with sierra adventure games and thes...
26,Ask HN: How can I get my 7-year-old started wi...,johnz,4 days ago,2025-02-20,22:43:53,9,https://news.ycombinator.com/item?id=43121372,"I started my career as a front-end developer, ..."
27,How to create LLM-driven tiny gnome robots?,r33b33,6 days ago,2025-02-18,12:54:51,13,https://news.ycombinator.com/item?id=43088935,"You know, like in the movie ""The Borrowers"". S..."
28,Ask HN: Dot EU domain instead of dot com?,skwee357,3 days ago,2025-02-21,09:25:03,9,https://news.ycombinator.com/item?id=43125655,I'm working on a service that targets mainly E...
29,How do you approach appealing to formal senior...,begoon,12 hours ago,2025-02-24,16:05:48,6,https://news.ycombinator.com/item?id=43161112,How do you approach appealing to formal senior...

In [ ]:
comments_df = pd.DataFrame()
comments_list = []

for link in df2["Link"]:
    r = requests.get(link)
    soup = BeautifulSoup(r.content, 'html.parser')
    comments_element = soup.find("table", class_="comment-tree")

    if not comments_element:
        print(f"No comments found for {link}")
        continue

    com = comments_element.find_all("tr", class_="athing comtr")

    for comment in com:
        c = comment.find("span", class_="comhead")

        user_element = c.find("a", class_="hnuser") if c else None
        user = user_element.get_text(strip=True) if user_element else "Unknown"

        age_element = c.find("span", class_="age") if c else None
        if age_element and age_element.has_attr("title"):
            age = age_element["title"]
            date_time_string = age.split()[0]

            try:
                datetime_object = datetime.fromisoformat(date_time_string)
                date = datetime_object.date()
                time = datetime_object.time()
            except ValueError as e:
                print(f"Error parsing datetime for {link}: {e}")
                date = None
                time = None
        else:
            date = None
            time = None

        text = comment.find("div", class_="comment")
        comment_content = text.get_text(strip=True) if text else "No comment"

        print(f"Link: {link}")
        print(f"Author: {user}")
        print(f"Comment: {comment_content}")
        print(f"Date: {date}")
        print(f"Time: {time}")
        print("---")

        comments_list.append({
            "Link": link,
            "Author": user,
            "Comment": comment_content,
            "Date": date,
            "Time": time
        })

comments_df = pd.DataFrame(comments_list)

Streaming output truncated to the last 5000 lines.
Time: 07:29:19
---
Link: https://news.ycombinator.com/item?id=43154065
Author: zft
Comment: That's super nice. Can I eventually replace my centralized forge ?reply
Date: 2025-02-24
Time: 07:37:47
---
Link: https://news.ycombinator.com/item?id=43154065
Author: icy
Comment: Yes! This architecture allows you to host your git repos on your own server, while allowing contributions from others with a unified identity (unlike say, Gitea or GitLab, where you’d have to make yet another account).reply
Date: 2025-02-24
Time: 07:50:18
---
Link: https://news.ycombinator.com/item?id=43154065
Author: dcreater
Comment: We need to get away from GitHub! Look forward to seeing this growreply
Date: 2025-02-24
Time: 07:36:49
---
Link: https://news.ycombinator.com/item?id=43154065
Author: hundredwatt
Comment: I'm building a new tool for end-to-end data validation and reconciliation in ELT pipelines, especially for teams replicating data from relational databases (Postgres, MySQL, SQL Server, Oracle) to data warehouses or data lakes.Most existing solutions only validate at the destination (dbt tests, Great Expectations), rely on aggregate comparisons (row counts, checksums), or generate too much noise (alert fatigue from observability tools). My tool:* Validates every row and column directly between source and destination
* Handles live source changes without false positives
* Eliminates noise by distinguishing in-flight changes from real discrepancies
* Detects even the smallest data mismatches without relying on thresholds
* Performs efficiently with an IO-bound, bandwidth-efficient algorithmIf you're dealing with data integrity issues in ELT workflows, I'd love to hear about your challenges!reply
Date: 2025-02-24
Time: 15:17:33
---
Link: https://news.ycombinator.com/item?id=43154065
Author: paddy_m
Comment: This sounds interesting.  Is this meant to run in pipelines or be used interactively?Are you building something open source?  Link to the repo?reply
Date: 2025-02-24
Time: 17:11:08
---
Link: https://news.ycombinator.com/item?id=43154065
Author: hundredwatt
Comment: It’s meant to run in or alongside the pipeline continuously.Not planning to open source, working on a commercial offering but haven’t launched anything publicly yet.Would love to hear any more thoughts on the concepts here or my email is in bioreply
Date: 2025-02-25
Time: 01:21:03
---
Link: https://news.ycombinator.com/item?id=43154065
Author: elpepito1
Comment: A flight simulator for software engineers.
Think LeetCode x CodeCrafters x HackerRank but doing actual large-scale simulated work to practice your skills (DevOps/Data/AI/ML/MLOps) and then be able to land a job.
Looking for beta users and feedback!reply
Date: 2025-02-24
Time: 16:51:16
---
Link: https://news.ycombinator.com/item?id=43154065
Author: onre
Comment: A no-frills X toolkit. Think Athena, add things like dialogs, file picker and make it completely vectored. No antialiasing, top goal is small size and fast execution. Can display vector and bitmap fonts, only external dependency is xcb. I just recently got my first digital storage oscilloscope and begun writing a companion software for it, as I couldn't find anything usable. This is one of the offshoots of that, the other being a somewhat Postscript-like language for scripting the thing.Once I get this done, I get back to the actual project of a 2.11-BSD based handheld computing appliance.Also there is this thing called "day job".reply
Date: 2025-02-24
Time: 07:23:12
---
Link: https://news.ycombinator.com/item?id=43154065
Author: bottled_poe
Comment: I'm working to make private hosting easier. I've been running a software development agency in Melbourne for 10+ years and have been building this platform in the background to help automate and standardise the hosting needs for our clients.We're now getting ready to launch a web portal for others to manage their own private hosting in a simpler way. The product also includes a directory of off-the-shelf applications which can be launched in a few clicks (eg. Deepseek chatbot).If you're interested in being part of our closed-Beta in March, reach out! (e: james at below domain)https://getbach.ioreply
Date: 2025-02-24
Time: 06:54:12
---
Link: https://news.ycombinator.com/item?id=43154065
Author: hkaju
Comment: I discovered the world of specialty coffee last year, fell into the rabbit hole and am now building a coffee journal and bean tracking app called Coffee Library (https://apps.apple.com/us/app/coffee-library/id6664071528?uo...).Probably the best way to develop your taste and understand the spectrum of different coffees available is to do comparative tasting aka try a small number of coffees in parallel to compare and contrast. I was having trouble finding tasting sets so I started freezing a little portion of every coffee bag I bought to create a collection for doing these tastings at home.I needed something to keep track of them all (as well as my tasting notes in general) so instead of using a spreadsheet I built a full app for it. The app supports NFC-tagged containers which I've found to make my workflow a whole lot easier.I also set up an online store to sell the NFC-equipped single-dosing tubes:https://store.coffeelibrary.appPlanning on adding more containers that work well with the app in the future.reply
Date: 2025-02-24
Time: 11:30:53
---
Link: https://news.ycombinator.com/item?id=43154065
Author: bosmanos
Comment: nice, fun project!there is a really great app that i found super useful called roastguide (roastguide.app). i have tried many of them but this is by far the most complete onereply
Date: 2025-02-24
Time: 11:57:24
---
Link: https://news.ycombinator.com/item?id=43154065
Author: maxehmookau
Comment: This is awesome. I was considering building something very similar, but great to see it already exists.How are you building the app? The interface makes me think it's native SwiftUI?reply
Date: 2025-02-24
Time: 11:33:21
---
Link: https://news.ycombinator.com/item?id=43154065
Author: hkaju
Comment: Yeah, all SwiftUI. I'm curious, was there anything specific that you saw in the interface that makes it obvious (vs UIKit)?reply
Date: 2025-02-24
Time: 11:40:40
---
Link: https://news.ycombinator.com/item?id=43154065
Author: maxehmookau
Comment: The segmented view at the top of each of the screenshots is "modern" app vibe which tend to be SwiftUI. It was just a hunch.The photos too. That kind of stuff with the text overlays is way easier to build in SwiftUI; especially in a tableview.reply
Date: 2025-02-24
Time: 13:52:51
---
Link: https://news.ycombinator.com/item?id=43154065
Author: chantepierre
Comment: Continuing bootstrapping my software+service company Alzo (https://alzo.archi/), an Elixir modular monolith.The first clients are here and I am working on "darker tech" now, a single codebase injecting their data in both MS Office and Adobe's software suites. That's quite a change from Elixir.Also working on the reverse feature, reading/writing MS Office files inside Alzo. For that, I'm writing a Java app behaving as an Erlang node, connected to my main app via Erlang distribution, to leverage existing rich Java libraries for office tech.reply
Date: 2025-02-24
Time: 07:01:30
---
Link: https://news.ycombinator.com/item?id=43154065
Author: cmontella
Comment: I’m working on a programming language for robots called Mech!https://github.com/mech-lang/mechMostly a research project until I find some more people interested in pushing it further.A recent blog for anyone who wants to check it out:https://mech-lang.org/post/2025-01-09-programming-chatgpt/And a 10 minute video:https://www.hytradboi.com/2022/i-tried-rubbing-a-database-on...reply
Date: 2025-02-24
Time: 16:51:15
---
Link: https://news.ycombinator.com/item?id=43154065
Author: yellowapple
Comment: My ADD brain keeps jumping around between various projects.  Some highlights:- Last month I demonstrated the ability to build Nintendo 64 ROMs with Zig¹, making some headway on Zig-native APIs for interfacing with the N64's memory-mapped hardware.  Taking a break for a moment; will probably resume when Zig 0.14 drops (within a couple months IIRC).  Next planned milestone will be to implement interrupt handlers.- Gradually migrating my code repos from Git to Fossil (with plans to continue to mirror to Git).  Experimenting with bidirectional syncs in order to preserve the ability to handle merge/pull requests from the various Git repo hosts on which I syndicate my repos.  The above Zig64 project will probably be the first real guinea pig.- Migrating my personal website away from Jekyll has been an ongoing project (going on almost a year now) with multiple parallel efforts: using Fossil's wiki features², using Scroll, and (most recently) using Typst's newly-announced HTML export feature.  All three approaches have their pros and cons.- I've been tinkering with my PowerBook G4; recently swapped in an SSD (using an mSATA→PATA enclosure) and installed the latest OpenBSD (with all partitions except for '/' encrypted; working on documenting that process and the associated kinks - and possibly turning said documentation into installer and initscript patches so that hardware platforms like macppc that lack support for encrypting '/' can still enjoy not-quite-full-disk encryption).  Next on the list is rebuilding the battery.- That PowerBook is also the only working machine I have that has an optical drive, so as soon as it was consistently booting right, I took the opportunity to back up the stack of burned CDs/DVDs I'd accumulated throughout my lifetime.- I have a bunch of my dad's old photos and schoolwork and such that I've been meaning to digitize and organize.----¹https://fsl.yellowapple.us/zig64²https://fsl.yellowapple.us/websitereply
Date: 2025-02-24
Time: 07:40:27
---
Link: https://news.ycombinator.com/item?id=43154065
Author: markatkinson
Comment: Ahh yes, I know the feeling. My current list of projects:- There's no speciality grade coffee in Zambia, and all the coffee beans in Zambia are from Zambian coffee farms. I've bought a small roaster and will start sourcing speciality grade coffee beans from Malawi, Kenya and Ethiopia and roasting for a few of the small stores and cafes around us.- Converting a beat up Suzuki Samurai into a capable 4x4 rock crawler/off road vehicle to enter my own team into the Elephant Charge 2025https://elephantcharge.org/ec-charge-2025/.- Growing and propogating cuttings of coffee plants in my backyard to start an outgrowers scheme in on the border of Zambia & Congo.- An emotion recognition app that has animated fruits and animals that dance and respond to emotion. I'd like to create something a bit more responsive for my child than the YT videos that exist (Unity).- Helping my wifes company prototype and spec out some lease management software.- Sourcing the equipment and ingredients to process my own coffee cherries into green coffee. I'll likely buy coffee from nearby growers and start processing as my own plants still have a couple years before they produce any fruit.- Migrating a Flow project to Typescript.- Learning Haskell by building a back-office API for another project in it.reply
Date: 2025-02-24
Time: 09:24:54
---
Link: https://news.ycombinator.com/item?id=43154065
Author: urda
Comment: Writing, just some writing. It does not matter if it is technical, creative, or something else. Just wanting to put pen to paper, and get it out there. See it athttps://urda.comreply
Date: 2025-02-24
Time: 22:35:26
---
Link: https://news.ycombinator.com/item?id=43154065
Author: renegat0x0
Comment: I am maintaining the internet on the github. Take a look.[0]https://github.com/rumca-js/Internet-Places-DatabaseI use it for various projects, like simple search[1]https://rumca-js.github.io/search?page=1&search=emulation[2]https://rumca-js.github.io/search?page=1&search=amigareply
Date: 2025-02-24
Time: 07:09:20
---
Link: https://news.ycombinator.com/item?id=43154065
Author: ideashower
Comment: Would be cool to see sites mapped on a network graph.reply
Date: 2025-02-24
Time: 13:38:10
---
Link: https://news.ycombinator.com/item?id=43154065
Author: nico
Comment: Experimenting with training and running ML models on a “normal computer” (ie. no GPU or cloud servers, just locally on CPU/ram)Don’t have a background in ML, so mostly just for learning purposesBeen playing a lot with the MNIST dataset. Trying things like training only on the examples the model gets wrong, or training only on random samples of the image (ie. using only a small subset of the pixels of the image as the input), or creating one model per label to overfit the data and then merging the models for testing, or just testing performance of different architectures and frameworks on the same problemreply
Date: 2025-02-24
Time: 17:29:39
---
Link: https://news.ycombinator.com/item?id=43154065
Author: bratao
Comment: I´m super excited, sleepless for a couple of days already. I´m trying to use all tricks possible to improve a Sequence Labeling using Conditional Random Fields. I need to NER billion of documents, and need to be fast.
CRFSuite is a workhorse, and a baseline very hard to beat with speed and precision. But with o3 I´m created a frank-stain with many tricks such as CRF with variable order, feature interactions, bidirectional, jointly learning with word embeddings. The precision is already over than CRFSuite. And I believe that would be better than many other solutions such as bi-lstm-crf. Definitely much faster.Now i´m trying to port to Cython to make as fast as possible. Here o3 is almost useless, but I´m progressing.reply
Date: 2025-02-24
Time: 15:45:10
---
Link: https://news.ycombinator.com/item?id=43154065
Author: muxneo
Comment: My family uses multiple messenger apps - WhatsApp, Slack, Discord etc. I get so many messages on these everyday. I am also member of multiple WhatsApp groups and slack channels. Needless to say, I miss out on a lot (actually every) important message in groups and channels and sometimes DMs.
I am working on ML solution to summarize the messages and info in these messengers for people whenever they access my service. The idea is to reduce the amount of info from 100:1 and give extremely succinct data without losing any important info.WOULD YOU BE INTERESTED?reply
Date: 2025-02-24
Time: 07:12:54
---
Link: https://news.ycombinator.com/item?id=43154065
Author: elric
Comment: I would be much more interested in a unified inbox on top of all those communication apps. An *actual* inbox, which lets me flag things, mark as (un)read, move to folders etc.reply
Date: 2025-02-24
Time: 09:53:07
---
Link: https://news.ycombinator.com/item?id=43154065
Author: threeseed
Comment: This sounds an awful like Siri Intelligence.And sorry to say it's a pretty underwhelming experience.reply
Date: 2025-02-24
Time: 08:53:43
---
Link: https://news.ycombinator.com/item?id=43154065
Author: azuanrb
Comment: In my country (Malaysia), most banks only export bank and credit card statements as PDFs, with no standard format for displaying the data. Since most of my transactions are cashless, I want a way to track my spending habits. I don't want to manually key in each transaction, so apps that require that won’t work for me.Right now, I'm building a bank statement PDF converter to track my past spending. I’m about halfway there, with a semi-automated way to categorize transactions too. So far, it’s working great!reply
Date: 2025-02-24
Time: 08:18:17
---
Link: https://news.ycombinator.com/item?id=43154065
Author: monroewalker
Comment: Do the banks offer email notifications for transactions? That could be another approach if you automate pulling info from the emailsreply
Date: 2025-02-24
Time: 08:27:52
---
Link: https://news.ycombinator.com/item?id=43154065
Author: azuanrb
Comment: For individual transactions, it's not really reliable, unfortunately. But for monthly reporting, they do have it, so that could be the next step. There's an app here that does something similar, but it doesn’t seem to be actively developed anymore. It’s a free app, so I guess there’s no reason for them to keep investing in it. Fair enough. Looks like they’re shifting toward a B2B solution instead, so that might be my next direction too.That said, my main goal for now is just to make it work for personal B2C use first. I do think there’s some potential here because major cities are pretty much cashless now, and there aren’t any good existing solutions for B2C.There are some other decent options, but they mainly focus on B2B (that’s where the money is), so they’re quite expensive and overkill for what I need.reply
Date: 2025-02-24
Time: 09:35:05
---
Link: https://news.ycombinator.com/item?id=43154065
Author: masteruvpuppetz
Comment: I was wondering about building a payment SMS notification ->  Tracking app.It would be more real-time and give me heartaches everytime I go out of budget :D:D:Dreply
Date: 2025-02-24
Time: 10:21:20
---
Link: https://news.ycombinator.com/item?id=43154065
Author: boramalper
Comment: A web-native[1] protocol for secure[2], decentralised[3] access to files distributed across mirrors:1. "Web-native" as in the protocol is designed with HTTP and modern web browsers in mind. Consequently, it can be implemented using Service Workers so that no additional software (nor even browser extensions) are needed to access files.2. Files are addressed by their cryptographic hash of their content (a) to ensure the authenticity of the data received from mirrors and (b) to avoid hard-coding specific locations/servers (i.e. content addressing).3. Files can be mirrored by anyone and users can retrieve files from any mirror; no party requires any permission from any authority. This is in contrast to traditional mirroring schemes, where mirrors have to "register" with the owner of the content (e.g. to mirror a Linux distro).Demo:https://webmirror-demo.netlify.app/Code:https://gitlab.com/webmirror/webmirror/Work in progress!reply
Date: 2025-02-24
Time: 11:02:51
---
Link: https://news.ycombinator.com/item?id=43154065
Author: bambax
Comment: I'm making an OCR website focused on outputting ascii text that follows the layout of the original, so that it doesn't need to understand or interpret zones in the source: it just resembles the source. This makes proofing easier and should also improve feeding documents to LLMs.reply
Date: 2025-02-24
Time: 14:32:58
---
Link: https://news.ycombinator.com/item?id=43154065
Author: aylmao
Comment: I've been building a little web DAW on the side for a minute. It's very early and not great yet, but it features some Faust effects [1] and WAMs [2].https://minidaw.aykev.dev/[1]:https://faust.grame.fr/[2]:https://www.webaudiomodules.com/reply
Date: 2025-02-24
Time: 09:11:44
---
Link: https://news.ycombinator.com/item?id=43154065
Author: overiit
Comment: Currently working on a tool that allows you to get data insights/aggregations via natural language. currently only sql based databases/warehouses (Postgres, Bigquery and soon Clickhouse, Snowflake, sqlite, etc.). I will be working on document Databases at some point as well.I started this for a bunch of reasons but mainly to allow non technical team members get any data insight they might need, without wasting dev resources on creating dashboards, queries etc.I personally dislike this "everything in LLM/AI has to be a chat room" approach.working on making it generally available but for now its early access onlyhttps://askquery.ai/If you have any ideas, thoughts or concerns please let me know.reply
Date: 2025-02-24
Time: 15:01:23
---
Link: https://news.ycombinator.com/item?id=43154065
Author: dend

In [ ]:
comments_df = pd.DataFrame(comments_list)

comments_df.head()

,Link,Author,Comment,Date,Time
0,https://news.ycombinator.com/item?id=43154065,zzo38computer,I am working on a ZZT-like game engine called ...,2025-02-25,04:25:26
1,https://news.ycombinator.com/item?id=43154065,jtwaleson,I'm creating an infinite canvas that has all y...,2025-02-24,08:27:29
2,https://news.ycombinator.com/item?id=43154065,abakker,Man...If you built this for large mainframe co...,2025-02-24,16:39:33
3,https://news.ycombinator.com/item?id=43154065,Cthulhu_,On a smaller scale it reminds me of the origin...,2025-02-24,13:21:21
4,https://news.ycombinator.com/item?id=43154065,jtwaleson,Cool. My long-term vision for software develop...,2025-02-24,18:04:44

In [ ]:
comments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168 entries, 0 to 1167
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Link     1168 non-null   object
 1   Author   1168 non-null   object
 2   Comment  1168 non-null   object
 3   Date     1168 non-null   object
 4   Time     1168 non-null   object
dtypes: object(5)
memory usage: 45.8+ KB

In [ ]:
link = "https://news.ycombinator.com/item?id=39171079"
r = requests.get(link)
soup = BeautifulSoup(r.content, 'html.parser')
comments_element = soup.find("table", class_="comment-tree")

if comments_element:
    com = comments_element.find_all("tr", class_="athing comtr")

    for comment in com:
        c = comment.find("span", class_="comhead")

        user_element = c.find("a", class_="hnuser") if c else None
        user = user_element.get_text(strip=True) if user_element else "Unknown"

        age_element = c.find("span", class_="age") if c else None
        if age_element and age_element.has_attr("title"):
            age = age_element["title"]
            date_time_string = age.split()[0]

            try:
                datetime_object = datetime.fromisoformat(date_time_string)
                date = datetime_object.date()
                time = datetime_object.time()
            except ValueError as e:
                print(f"Error parsing datetime for {link}: {e}")
                date = None
                time = None
        else:
            date = None
            time = None

        text = comment.find("div", class_="comment")
        comment_content = text.get_text(strip=True) if text else "No comment"

        print(f"Link: {link}")
        print(f"Author: {user}")
        print(f"Comment: {comment_content}")
        print(f"Date: {date}")
        print(f"Time: {time}")
        print("---")
else:
    print(f"No comments found for {link}")

Link: https://news.ycombinator.com/item?id=39171079
Author: xrd
Comment: It definitely ruined a friendship of mine. His startup was making insane amounts of money. He offered me a position, then his business priorities changed and forced me into a poor role with no long term prospects. I struggled in that new role and he noticed that. He then terminated our agreement two months early.There are reasons he's right about what he did and there are reasons I'm right about being upset about it but it definitely cost us our friendship.I think back that if he had operated with integrity and honored his agreement to keep me on for two extra months it would have not been upsetting to leave then. As it was it left me scrambling with three small kids.The lesson to me is that even if the startup is flush with cash, there will be issues. How the founder manages those issues matters.I recall when I had my startup I did a bunch of business coaching and really had to take on a lot of uncomfortable things about myself. I'm grateful for that. I invited him many times to participate in that work and he never did. When the money is good you think you don't need it.
Date: 2024-01-29
Time: 01:12:45
---
Link: https://news.ycombinator.com/item?id=39171079
Author: mercenario
Comment: On one side you were a employee, so he needs to treat you kinda like a regular employee. If what he did to you would be normal for another employee, then he has a point. Doing different could even be seem as unfair for the other employees.On the other side you are a friend, I really don't know what he could have done differently, very hard.
Date: 2024-01-29
Time: 15:20:53
---
Link: https://news.ycombinator.com/item?id=39171079
Author: solardev
Comment: Wouldn't the right thing to have done for any employee, friend or not, be to simply pay them the remaining two months but let them go early?
Date: 2024-01-31
Time: 16:35:43
---
Link: https://news.ycombinator.com/item?id=39171079
Author: geraldhh
Comment: > As it was it left me scrambling with three small kids.you did not mention whether this early termination was communicated beforehand.nevertheless this person probably never was your friend. sry
Date: 2024-01-29
Time: 08:47:53
---
Link: https://news.ycombinator.com/item?id=39171079
Author: michaelt
Comment: > nevertheless this person probably never was your friend. sryNo, it's completely common for friendships to break down over business.Very few friendships are robust enough to survive one party costing the other $20,000.
Date: 2024-01-29
Time: 12:56:27
---
Link: https://news.ycombinator.com/item?id=39171079
Author: xrd
Comment: It's wild that you said that amount because that was exactly the number.I have other friendships that have been tested for similar amounts that have survived. But, it leaves a mark.I had an ex-employee who worked for me under starvation wages in a startup long ago. He was upset about that and some tax implications, and brought it up with me. I gave him a smallish lump sum and enabled him to put a down payment on a house. I need to ask him about that, it was really brave to ask me to clean something up, and I never did that with the friend from the OP. I wonder if it would have gone differently.I'm seeing a lot of people in my circle struggling right now. I bet 2024 is going to be a bad year for friendships.
Date: 2024-01-29
Time: 13:24:45
---
Link: https://news.ycombinator.com/item?id=39171079
Author: catlifeonmars
Comment: Wow. $20k seems like a paltry sum to end a friendship over.
Date: 2024-01-29
Time: 13:42:00
---
Link: https://news.ycombinator.com/item?id=39171079
Author: dbspin
Comment: This forum is so out of touch with reality sometimes I'm just left blinking and shaking my head. 20,000 dollars is an enormous amount of money to a supermajority of people in the developed world. Almost half an annual wage for most industrial workers in the EU and US.
Date: 2024-01-29
Time: 14:42:03
---
Link: https://news.ycombinator.com/item?id=39171079
Author: geraldhh
Comment: thou, the question is, wheather you can buy a friendship with the money. the answer is probably, no, hence it's not worth it.
Date: 2024-01-30
Time: 11:46:47
---
Link: https://news.ycombinator.com/item?id=39171079
Author: felixg3
Comment: $500,000 USD is a middle class wage in the Bay Area /s
Date: 2024-01-29
Time: 17:53:51
---
Link: https://news.ycombinator.com/item?id=39171079
Author: InitialLastName
Comment: That's a very privileged perspective to have... I know plenty of people for whom a sudden $20k shortfall would be existential.
Date: 2024-01-29
Time: 14:56:59
---
Link: https://news.ycombinator.com/item?id=39171079
Author: catlifeonmars
Comment: I probably could have phrased it better, but my comment was taken out of context. What I mean is $20k is a paltry sum for a tech startup to screw someone over for. I don’t think it’s a small sum for most individual wage earners (especially with young children).
Date: 2024-01-31
Time: 03:14:08
---
Link: https://news.ycombinator.com/item?id=39171079
Author: southernplaces7
Comment: Really? Try glancing the sorts of wages and earnings that literally 99% of the world's population makes on downwards and you'll quickly see that it's far, far from "paltry" for the vast majority of people.
Date: 2024-01-29
Time: 17:43:59
---
Link: https://news.ycombinator.com/item?id=39171079
Author: averageRoyalty
Comment: I'm unsure why my sibling comments seem to think the sentence ends at "sum".Is it possible to buy a real friendship for $20k? Is a friendship of many years worth more to you than $20k - would you stop being friends if someone else offered you that much to do so?This isn't a paltry sum of money, it is a paltry sum to end a friendship over.
Date: 2024-02-03
Time: 04:13:48
---
Link: https://news.ycombinator.com/item?id=39171079
Author: drpgq
Comment: An interesting thought experiment to me is how much I would be willing to spend to preserve a friendship. Various situations over the past few years, including some businesses with friends made me think about hypotheticals.
Date: 2024-01-29
Time: 21:52:42
---
Link: https://news.ycombinator.com/item?id=39171079
Author: blantonl
Comment: I struggle to find any situation where 20k is a paltry sum
Date: 2024-01-29
Time: 15:13:39
---
Link: https://news.ycombinator.com/item?id=39171079
Author: elevatedastalt
Comment: I was going to say "maybe to launch a rocket into space" but then I realized SpaceX has made even that much cheaper than it used to be. (Still more than 20K though :))
Date: 2024-01-29
Time: 17:10:30
---
Link: https://news.ycombinator.com/item?id=39171079
Author: justinclift
Comment: > Very few friendships are robust enough to survive one party costing the other $20,000.That probably depends on how critical that $20k is to you.  If it's your only $20k, then yeah it'd be much more impactful than if it's just one of many.
Date: 2024-01-29
Time: 14:08:10
---
Link: https://news.ycombinator.com/item?id=39171079
Author: michaelt
Comment: Certainly, if the loss means you encounter financial hardship, you'd be understandably resentful.But even when the loss causes little financial hardship, it could put a strain on a relationship.Imagine you invest $20k in my business and I buy a $5k industrial juicing machine for the office so my staff can have freshly squeezed orange juice. I tell you that employees expect free luxury food these days and it'll make hiring much easier. You have your doubts.If the business does well and we both make a big profit - we're both happy. You still think the juicer was a bit extravagant - but it all worked out in the end, and maybe I was right that it helped with recruitment.But if the business fails - you might resent the fact I wasted $5k of your money on a juicer.
Date: 2024-01-29
Time: 16:43:15
---
Link: https://news.ycombinator.com/item?id=39171079
Author: polynomial
Comment: So we can put a price on friendship? (/s)
Date: 2024-01-29
Time: 13:22:38
---
Link: https://news.ycombinator.com/item?id=39171079
Author: geraldhh
Comment: obviously we can't.hence no money can be enough to compensate for a friendship
Date: 2024-02-07
Time: 15:19:00
---
Link: https://news.ycombinator.com/item?id=39171079
Author: xrd
Comment: When we started working together I suggested a six month trial, and he said let's do 12 months. That role was perfect and I had the skills for it. 6 months in his business priorities changed, so he pushed me into a new role. Then, at the ten month mark said "I just don't have any more work for you."It all depends on what is a friend. Your statement makes me question what makes a good friend. I don't really know right now. It is a lot harder to make them at 50, of that I'm sure.
Date: 2024-01-29
Time: 13:26:43
---
Link: https://news.ycombinator.com/item?id=39171079
Author: geraldhh
Comment: "friends are people that show up when it's not convenient for them" - my mum
Date: 2024-02-10
Time: 14:33:36
---
Link: https://news.ycombinator.com/item?id=39171079
Author: brandall10
Comment: I've seen friendships break down over one person not doing the dishes for a prolonged period.The issue with friendships is usually there's some expectation of being in it 'together' and to put in some sort of similar effort, despite the major power imbalance of employee vs. cofounder.If the founder feels their friend is for instance, giving say half the effort they are (which I feel personally is reasonable for an early stage employee, that they have a life), they may feel their friend is violating some notion of trust, despite the friend getting maybe 1% equity at best.
Date: 2024-01-29
Time: 15:34:23
---
Link: https://news.ycombinator.com/item?id=39171079
Author: ChrisMarshallNY
Comment: One of my favorite quotes is attributed to Saint Augustine:"If two friends ask you to judge a dispute, don't accept, because you will lose one friend; on the other hand, if two strangers come with the same request, accept, because you will gain one friend."It sort of applies, here, as well.
Date: 2024-01-29
Time: 12:43:47
---
Link: https://news.ycombinator.com/item?id=39171079
Author: donatj
Comment: Years back a coworker and I were having a small interpersonal disagreement. My supervisor declined to get involved, basically told us to sort it out without wasting work time.It wasn’t anything serious enough to involve HR (in my eyes anyway), but I spent a solid while annoyed with this response. It took me a solid five years to realize he had made the right overall decision.He had not played favorites, did not burn any bridges, and caused at worst a mild annoyance to both of us rather than potentially leading one of us to quit.
Date: 2024-01-29
Time: 15:09:03
---
Link: https://news.ycombinator.com/item?id=39171079
Author: abc_lisper
Comment: That’s very PC, but there’s a fine line between that and not showing leadership. What good is a leader who doesn’t standup for what’s right? That’s annoying for the person who is right
Date: 2024-01-29
Time: 16:55:04
---
Link: https://news.ycombinator.com/item?id=39171079
Author: illys
Comment: If two friends ask you to judge a dispute, and youdon'taccept... You might loose two friends since both of them think they are right and will not understand you do not support them.
Date: 2024-01-29
Time: 13:11:46
---
Link: https://news.ycombinator.com/item?id=39171079
Author: ChrisMarshallNY
Comment: Then they aren't my friends. If a "friendship" is that delicate, I'm better off, without.I have extremely close friends, with whom I have deep, fundamental, disagreements.I have absolutely no problem, telling people that they are dreaming, if they think they can extort me into taking their side."Support" can mean that I won't participate in destructive behavior. I often can't stop others from doing it, but I can make sure I don't get dragged into the cesspool, and be ready with towels and a power washer, when they get out.
Date: 2024-01-29
Time: 13:28:07
---
Link: https://news.ycombinator.com/item?id=39171079
Author: ensignavenger
Comment: This same exact argument could be applied to the first saying as well.
Date: 2024-01-29
Time: 13:45:46
---
Link: https://news.ycombinator.com/item?id=39171079
Author: ChrisMarshallNY
Comment: That is correct. It's just a quote. Real life tends to have more subtlety.
Date: 2024-01-29
Time: 13:46:44
---
Link: https://news.ycombinator.com/item?id=39171079
Author: spiderfarmer
Comment: If they are that sensitive, I can also be sensitive and ask them why they've involved me in a conundrum where I stand to gain nothing.
Date: 2024-01-29
Time: 13:47:23
---
Link: https://news.ycombinator.com/item?id=39171079
Author: rsynnott
Comment: That would be a mildly weird reaction to "I don't want to get involved in your dispute", in _most_ cases. (I think there are edge-cases where not wanting to get involved might in itself be taking a stand, but certainly for everyday disputes most people wouldn't take offence to "I don't want to get involved").
Date: 2024-01-29
Time: 13:57:30
---
Link: https://news.ycombinator.com/item?id=39171079
Author: brandall10
Comment: I would trust they would instead be happy to have such a socially intelligent friend once the dust has cooled.
Date: 2024-01-29
Time: 14:48:10
---
Link: https://news.ycombinator.com/item?id=39171079
Author: quickthrower2
Comment: The friend you gain will be a fairweather friend though, most likely.If the person you disagrees with becomes your friend then that’s a good sign!
Date: 2024-02-02
Time: 10:56:47
---
Link: https://news.ycombinator.com/item?id=39171079
Author: ytdytvhxgydvhh
Comment: Didn’t end up going to work for the friend, but the situation still strained the friendship.An engineer I worked with for several years (and became friends with outside of work) started his own company, a couple of years later he recruited me to join as his business was taking off. He’d also brought in a business guy who seemed to put in lots of processes including a mandatory take-home coding assignment as part of their interview process.So anyhow, this guy who I’d worked alongside for years, who’d seen plenty of my code and wanted me to join his company, was going to make me do this homework to get an offer.So I did a verrry basic solution to this thing and sent it back. A bit later I got an email from someone in their office that they regretted they didn’t have any positions that fit my experience.Later my friend (and his wife) encouraged me to do the homework thing again but I laughed them off. I didn’t want to work for a small company that somehow had hamstrung itself with unnecessary processes that kept the founder from hiring someone he wanted to hire.A few years later they sold and a couple engineers I know made multiple millions. So yeah, I dunno, I felt good about my decision at the time, but in retrospect it would have been better to act like any job seeker and just go to work for my friend.Your mileage will certainly vary.
Date: 2024-01-29
Time: 01:21:11
---
Link: https://news.ycombinator.com/item?id=39171079
Author: neilv
Comment: >So anyhow, this guy who I’d worked alongside for years, who’d seen plenty of my code and wanted me to join his company, was going to make me do this homework to get an offer.Had your friend delegated the engineering hiring decisions/process to someone else, and was trying not to step on their toes?Or friend had instituted the process, and didn't think it would go well with the other people, if you looked like a nepotism hire who bypassed the process?Or friend was trying to put you in your employee place (where you had to meet his process), or otherwise was getting a bit full of himself, or a bit sleep-deprived and nutty?
Date: 2024-01-29
Time: 05:58:19
---
Link: https://news.ycombinator.com/item?id=39171079
Author: robertlagrant
Comment: > Or friend was trying to put you in your employee place (where you had to meet his process), or otherwise was getting a bit full of himself, or a bit sleep-deprived and nutty?This would be a strange take. CEO shouldn't be letting people in on the nod. If hiring is someone else's job, CEO shouldn't be overriding. At best suggesting candidates but saying that it's totally the hiring manager's call.If a candidate didn't pass a hiring process because they didn't put effort in as they felt they should get the job due to connections, I would agree with the company's decision.
Date: 2024-01-29
Time: 09:40:09
---
Link: https://news.ycombinator.com/item?id=39171079
Author: machomaster
Comment: The purpose of a hiring process (as in take home assignment) is to see that the person is competent to do the job. It was already established that he was. So following a formal process is a stupid waste of time (on both ends) that has nothing to do with strengthening the company and is simply an unnecessary ego trip. The company disqualified itself.
Date: 2024-01-29
Time: 12:37:57
---
Link: https://news.ycombinator.com/item?id=39171079
Author: robertlagrant
Comment: How was it established?
Date: 2024-01-29
Time: 16:58:53
---
Link: https://news.ycombinator.com/item?id=39171079
Author: wifipunk
Comment: They mean it was established by the CEO's experience with him as an engineer.To the company it was never, and as high a recommendation as the CEO would be; most people would agree they did the right thing. Unless you're hired before a hiring manager or whomever is doing the hiring you should follow the process. If you treat it like a joke because you feel entitled by your connections then be willing to accept the outcome.
Date: 2024-01-29
Time: 17:42:09
---
Link: https://news.ycombinator.com/item?id=39171079
Author: machomaster
Comment: You are describing the HR person's ego trip.That person should be fired, for being unprofessional and for inability to adapt to a trivial non-standard situation ("normally we test the applicant's technical competency with a take-home test; now it already has been established; so I need to stop wasting everybody's time and spend my time doing something actually useful".)Obviously, HR could still be useful in establishing a culture fit, but even then it's pretty much a formality since the CEO worked with and recommended the guy.
Date: 2024-01-29
Time: 21:06:37
---
Link: https://news.ycombinator.com/item?id=39171079
Author: robertlagrant
Comment: I think the fundamental difference is just that you think that the technical competency has been established, and the hiring manager did not. Given the candidate did the exercise, but did it badly, I think the hiring manager was right.None of the other stuff you're saying is relevant. No point doing armchair psychoanalysis.
Date: 2024-01-30
Time: 10:00:09
---
Link: https://news.ycombinator.com/item?id=39171079
Author: machomaster
Comment: The only thing the candidate did wrong was to even start the assignment. Either communicate that it is a waste of time and refuse to do it, or decide to do it and do it properly. No point in half-assing anything in life.
Date: 2024-01-30
Time: 16:16:26
---
Link: https://news.ycombinator.com/item?id=39171079
Author: robertlagrant
Comment: Indeed. That's why the HR person (or whoever it was) wasn't on a fireable ego trip. They just enforced their normal process that they use to not let people slip in through nepotism.
Date: 2024-02-01
Time: 08:53:06
---
Link: https://news.ycombinator.com/item?id=39171079
Author: machomaster
Comment: The process that they designed. This means they can change it and the excuse "I am simply following the pre-determined process" will not work.Clearly, the process (of cutting technically incompetent people while letting through the technically competent ones) is not working properly; that alone is fireable incompetency ("You had only one job and you failed at it!").Another fireable thing is that HR does not understand that they are under the CEO, they are implementing the CEO's vision, in the way he envisioned. But instead of that, HR is indeed ego-tripping.
Date: 2024-02-01
Time: 15:45:42
---

In [ ]:
df2.to_csv("questions2.csv", index=False)
comments_df.to_csv("comments2.csv", index=False)

In [ ]:
comments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168 entries, 0 to 1167
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Link     1168 non-null   object
 1   Author   1168 non-null   object
 2   Comment  1168 non-null   object
 3   Date     1168 non-null   object
 4   Time     1168 non-null   object
dtypes: object(5)
memory usage: 45.8+ KB

In [ ]:
URL = "https://news.ycombinator.com/ask?p=1"
r = requests.get(URL)
soup = BeautifulSoup(r.content, 'html.parser')

data = []
listings = soup.find_all("tr", class_="athing")

for listing in listings:
    title_element = listing.find("span", class_="titleline")
    title = title_element.find("a").text.strip()
    link_element = title_element.find("a")
    href = link_element["href"]
    full_link = f"https://news.ycombinator.com/{href}"

    next_row = listing.find_next("tr")
    subtext_element = next_row.find("td", class_="subtext")

    user_element = subtext_element.find("a", class_="hnuser") if subtext_element else None
    user = user_element.text.strip() if user_element else "Unknown"

    age_element = subtext_element.find("span", class_="age") if subtext_element else None
    relative_time = age_element.find("a").text.strip() if age_element else "Unknown"

    if age_element and "title" in age_element.attrs:
        age = age_element["title"]
        date_time_string = age.split()[0]

        try:
            datetime_object = datetime.fromisoformat(date_time_string)
            date = datetime_object.date()
            time = datetime_object.time()
        except ValueError as e:
            print(f"Error parsing datetime for {full_link}: {e}")
            date, time = None, None
    else:
        date, time = None, None

    score_element = subtext_element.find("span", class_="score") if subtext_element else None
    score = int(score_element.text.split()[0]) if score_element else 0

    print(f"Title: {title}")
    print(f"User: {user}")
    print(f"Relative time: {relative_time}")
    print(f"Date: {date}")
    print(f"Time: {time}")
    print(f"Score: {score}")
    print(f"Link: {full_link}")
    print("---")

    data.append({
        "Title": title,
        "User": user,
        "Relative time": relative_time,
        "Date": date,
        "Time": time,
        "Score": score,
        "Link": full_link
    })

df3 = pd.DataFrame(data)

Title: Ask HN: What are you working on? (February 2025)
User: david927
Relative time: 23 hours ago
Date: 2025-02-23
Time: 23:00:16
Score: 203
Link: https://news.ycombinator.com/item?id=43154065
---
Title: Ask HN: My father passed away. How do deal with the grief?
User: gogo61
Relative time: 4 hours ago
Date: 2025-02-24
Time: 23:37:25
Score: 10
Link: https://news.ycombinator.com/item?id=43166256
---
Title: Ask HN: Former devs who can't get a job, what did you end up doing for work?
User: throw81398475
Relative time: 8 hours ago
Date: 2025-02-24
Time: 20:22:37
Score: 20
Link: https://news.ycombinator.com/item?id=43164498
---
Title: Ask HN: Have you written or consumed OpenAPI Arazzo specification?
User: sb13
Relative time: 16 hours ago
Date: 2025-02-24
Time: 11:41:47
Score: 5
Link: https://news.ycombinator.com/item?id=43158402
---
Title: Tell HN: Five random IndieWeb blog links on your terminal
User: susam
Relative time: 1 day ago
Date: 2025-02-23
Time: 10:55:47
Score: 44
Link: https://news.ycombinator.com/item?id=43148408
---
Title: Ask HN: Is anyone still using Dreamweaver?
User: gillytech
Relative time: 2 days ago
Date: 2025-02-22
Time: 17:59:27
Score: 165
Link: https://news.ycombinator.com/item?id=43141368
---
Title: Navigating a Broken Dev Culture
User: lightserver
Relative time: 1 day ago
Date: 2025-02-23
Time: 14:27:18
Score: 58
Link: https://news.ycombinator.com/item?id=43149437
---
Title: Ask HN: Do you practice lucid dreaming?
User: raunometsa
Relative time: 2 days ago
Date: 2025-02-22
Time: 12:45:26
Score: 13
Link: https://news.ycombinator.com/item?id=43138523
---
Title: Ask HN: Tired of startups â€“ want a normal job. Help
User: mertleee
Relative time: 4 days ago
Date: 2025-02-21
Time: 00:59:57
Score: 95
Link: https://news.ycombinator.com/item?id=43122800
---
Title: Ask HN: What happened to all those metaverse projects from 2022?
User: herval
Relative time: 4 hours ago
Date: 2025-02-24
Time: 23:57:08
Score: 6
Link: https://news.ycombinator.com/item?id=43166405
---
Title: Ask HN: Are there online communities for single-owner run companies?
User: indulona
Relative time: 2 days ago
Date: 2025-02-22
Time: 12:47:53
Score: 5
Link: https://news.ycombinator.com/item?id=43138540
---
Title: Ask HN: Can I really create a company around my open-source software?
User: darkhorse13
Relative time: 4 days ago
Date: 2025-02-18
Time: 08:37:01
Score: 73
Link: https://news.ycombinator.com/item?id=43087383
---
Title: Ask HN: Anyone building a non AI product/startup?
User: codegeek
Relative time: 10 hours ago
Date: 2025-02-24
Time: 17:46:16
Score: 5
Link: https://news.ycombinator.com/item?id=43162490
---
Title: Ask HN: What fiction/non-fiction book should everyone read on the topic of CS?
User: Eavolution
Relative time: 7 days ago
Date: 2025-02-18
Time: 00:40:33
Score: 35
Link: https://news.ycombinator.com/item?id=43084739
---
Title: Ask HN: Why is Cursor IDE accessing all my env vars?
User: iyn
Relative time: 3 days ago
Date: 2025-02-21
Time: 20:07:29
Score: 14
Link: https://news.ycombinator.com/item?id=43132313
---
Title: Ask HN: Advice for someone who stagnated in their career. Help
User: justonemore
Relative time: 2 days ago
Date: 2025-02-23
Time: 03:49:26
Score: 10
Link: https://news.ycombinator.com/item?id=43146311
---
Title: Ask HN: Tips on how to find great technical recruiters to land the right job?
User: Glimjaur
Relative time: 16 hours ago
Date: 2025-02-24
Time: 12:27:57
Score: 3
Link: https://news.ycombinator.com/item?id=43158741
---
Title: Ask HN: Why is it taking so long to build computer controlling agents?
User: louisfialho
Relative time: 2 days ago
Date: 2025-02-23
Time: 01:19:39
Score: 10
Link: https://news.ycombinator.com/item?id=43145225
---
Title: Ask HN: Tips to make a pitch for "acquihire of one"?
User: rglullis
Relative time: 2 days ago
Date: 2025-02-22
Time: 10:00:30
Score: 2
Link: https://news.ycombinator.com/item?id=43137645
---
Title: Tell HN: Generational Gap
User: yonisto
Relative time: 2 days ago
Date: 2025-02-22
Time: 09:21:37
Score: 4
Link: https://news.ycombinator.com/item?id=43137496
---
Title: Ask HN: How do you use local LLMs?
User: Haeuserschlucht
Relative time: 3 days ago
Date: 2025-02-21
Time: 08:52:01
Score: 7
Link: https://news.ycombinator.com/item?id=43125486
---
Title: Ask HN: A retrofitted C dialect?
User: anqurvanillapy
Relative time: 2 days ago
Date: 2025-02-22
Time: 08:11:45
Score: 7
Link: https://news.ycombinator.com/item?id=43137171
---
Title: Segment for LLM Traces? Seeking Feedback on an Open Source LLM Log Router
User: patethegreat
Relative time: 3 days ago
Date: 2025-02-21
Time: 22:44:57
Score: 11
Link: https://news.ycombinator.com/item?id=43133994
---
Title: Ask HN: How can I prepare my digital life for geopolitical disruptions?
User: mwinatschek
Relative time: 4 days ago
Date: 2025-02-20
Time: 09:16:45
Score: 30
Link: https://news.ycombinator.com/item?id=43112703
---
Title: I'm broke and non-technical, trying to develop tech startup
User: vyasaveda
Relative time: 2 days ago
Date: 2025-02-22
Time: 17:47:25
Score: 5
Link: https://news.ycombinator.com/item?id=43141235
---
Title: Ask HN: Did you grow up with adventure games and how did that affect yo?
User: HellDunkel
Relative time: 10 hours ago
Date: 2025-02-24
Time: 17:48:07
Score: 7
Link: https://news.ycombinator.com/item?id=43162513
---
Title: Ask HN: How can I get my 7-year-old started with web development?
User: johnz
Relative time: 4 days ago
Date: 2025-02-20
Time: 22:43:53
Score: 9
Link: https://news.ycombinator.com/item?id=43121372
---
Title: How to create LLM-driven tiny gnome robots?
User: r33b33
Relative time: 6 days ago
Date: 2025-02-18
Time: 12:54:51
Score: 13
Link: https://news.ycombinator.com/item?id=43088935
---
Title: Ask HN: Dot EU domain instead of dot com?
User: skwee357
Relative time: 3 days ago
Date: 2025-02-21
Time: 09:25:03
Score: 9
Link: https://news.ycombinator.com/item?id=43125655
---
Title: Ask HN: Free/Open Source Brainstorming Agents
User: sujayk_33
Relative time: 3 days ago
Date: 2025-02-21
Time: 08:22:02
Score: 9
Link: https://news.ycombinator.com/item?id=43125296
---

In [ ]:
df3

,Title,User,Relative time,Date,Time,Score,Link
0,Ask HN: What are you working on? (February 2025),david927,23 hours ago,2025-02-23,23:00:16,203,https://news.ycombinator.com/item?id=43154065
1,Ask HN: My father passed away. How do deal wit...,gogo61,4 hours ago,2025-02-24,23:37:25,10,https://news.ycombinator.com/item?id=43166256
2,"Ask HN: Former devs who can't get a job, what ...",throw81398475,8 hours ago,2025-02-24,20:22:37,20,https://news.ycombinator.com/item?id=43164498
3,Ask HN: Have you written or consumed OpenAPI A...,sb13,16 hours ago,2025-02-24,11:41:47,5,https://news.ycombinator.com/item?id=43158402
4,Tell HN: Five random IndieWeb blog links on yo...,susam,1 day ago,2025-02-23,10:55:47,44,https://news.ycombinator.com/item?id=43148408
5,Ask HN: Is anyone still using Dreamweaver?,gillytech,2 days ago,2025-02-22,17:59:27,165,https://news.ycombinator.com/item?id=43141368
6,Navigating a Broken Dev Culture,lightserver,1 day ago,2025-02-23,14:27:18,58,https://news.ycombinator.com/item?id=43149437
7,Ask HN: Do you practice lucid dreaming?,raunometsa,2 days ago,2025-02-22,12:45:26,13,https://news.ycombinator.com/item?id=43138523
8,Ask HN: Tired of startups â€“ want a normal jo...,mertleee,4 days ago,2025-02-21,00:59:57,95,https://news.ycombinator.com/item?id=43122800
9,Ask HN: What happened to all those metaverse p...,herval,4 hours ago,2025-02-24,23:57:08,6,https://news.ycombinator.com/item?id=43166405
10,Ask HN: Are there online communities for singl...,indulona,2 days ago,2025-02-22,12:47:53,5,https://news.ycombinator.com/item?id=43138540
11,Ask HN: Can I really create a company around m...,darkhorse13,4 days ago,2025-02-18,08:37:01,73,https://news.ycombinator.com/item?id=43087383
12,Ask HN: Anyone building a non AI product/startup?,codegeek,10 hours ago,2025-02-24,17:46:16,5,https://news.ycombinator.com/item?id=43162490
13,Ask HN: What fiction/non-fiction book should e...,Eavolution,7 days ago,2025-02-18,00:40:33,35,https://news.ycombinator.com/item?id=43084739
14,Ask HN: Why is Cursor IDE accessing all my env...,iyn,3 days ago,2025-02-21,20:07:29,14,https://news.ycombinator.com/item?id=43132313
15,Ask HN: Advice for someone who stagnated in th...,justonemore,2 days ago,2025-02-23,03:49:26,10,https://news.ycombinator.com/item?id=43146311
16,Ask HN: Tips on how to find great technical re...,Glimjaur,16 hours ago,2025-02-24,12:27:57,3,https://news.ycombinator.com/item?id=43158741
17,Ask HN: Why is it taking so long to build comp...,louisfialho,2 days ago,2025-02-23,01:19:39,10,https://news.ycombinator.com/item?id=43145225
18,"Ask HN: Tips to make a pitch for ""acquihire of...",rglullis,2 days ago,2025-02-22,10:00:30,2,https://news.ycombinator.com/item?id=43137645
19,Tell HN: Generational Gap,yonisto,2 days ago,2025-02-22,09:21:37,4,https://news.ycombinator.com/item?id=43137496
20,Ask HN: How do you use local LLMs?,Haeuserschlucht,3 days ago,2025-02-21,08:52:01,7,https://news.ycombinator.com/item?id=43125486
21,Ask HN: A retrofitted C dialect?,anqurvanillapy,2 days ago,2025-02-22,08:11:45,7,https://news.ycombinator.com/item?id=43137171
22,Segment for LLM Traces? Seeking Feedback on an...,patethegreat,3 days ago,2025-02-21,22:44:57,11,https://news.ycombinator.com/item?id=43133994
23,Ask HN: How can I prepare my digital life for ...,mwinatschek,4 days ago,2025-02-20,09:16:45,30,https://news.ycombinator.com/item?id=43112703
24,"I'm broke and non-technical, trying to develop...",vyasaveda,2 days ago,2025-02-22,17:47:25,5,https://news.ycombinator.com/item?id=43141235
25,Ask HN: Did you grow up with adventure games a...,HellDunkel,10 hours ago,2025-02-24,17:48:07,7,https://news.ycombinator.com/item?id=43162513
26,Ask HN: How can I get my 7-year-old started wi...,johnz,4 days ago,2025-02-20,22:43:53,9,https://news.ycombinator.com/item?id=43121372
27,How to create LLM-driven tiny gnome robots?,r33b33,6 days ago,2025-02-18,12:54:51,13,https://news.ycombinator.com/item?id=43088935
28,Ask HN: Dot EU domain instead of dot com?,skwee357,3 days ago,2025-02-21,09:25:03,9,https://news.ycombinator.com/item?id=43125655
29,Ask HN: Free/Open Source Brainstorming Agents,sujayk_33,3 days ago,2025-02-21,08:22:02,9,https://news.ycombinator.com/item?id=43125296

In [ ]:
df3.drop(index=8, inplace=True)
df3.drop(index=15, inplace=True)
df3.drop(index=17, inplace=True)
df3.drop(index=22, inplace=True)
df3.drop(index=23, inplace=True)
df3.drop(index=24, inplace=True)
df3.drop(index=25, inplace=True)
df3.drop(index=26, inplace=True)
df3.drop(index=29, inplace=True)

In [ ]:
for link in df3['Link']:
    URL = link
    r = requests.get(URL)
    soup = BeautifulSoup(r.content, 'html.parser')
    listing = soup.find("div", class_="toptext")

    if listing:
        text_content = listing.get_text(strip=True)
        row_index = df3[df3['Link'] == link].index[0]
        df3.loc[row_index, 'Question'] = text_content
    else:
        print("Warning: 'div' element with class 'toptext' not found for link:", link)
        df3.loc[row_index, 'Question'] = None

    print(link)
    print(text_content)

https://news.ycombinator.com/item?id=43154065
What are you working on?  Any new ideas that you're thinking about?
https://news.ycombinator.com/item?id=43166256
It has been one month since he passed and i have been continuously crying. I am writing this with tears in my eye.
https://news.ycombinator.com/item?id=43164498
That's all.Savings are getting low, and I'm going to be struggling to pay rent soon.  I'm curious what other kinds of work other former developers got into and if they like it.  Cheers.
https://news.ycombinator.com/item?id=43158402
Hi HN,I recently came across the Arazzo specification within the OpenAPI initiative. It defines a standard to express workflows involving multiple APIs. A couple of main use cases here are automatic API invocation with LLMs and automated tests.I want to auto generate API tests based on these specs and would like to see other examples. Is anyone here writing or consuming Arazzo specs?Reference: https://www.openapis.org/arazzo
https://news.ycombinator.com/item?id=43148408
Hello HN!  I believe some of you might have come across this pretty interesting post about discovering IndieWeb blogs, one blog at a time: <https://news.ycombinator.com/item?id=43139953>That post is actually a link to <https://indieblog.page/>, which features an impressive list of independently maintained personal websites and blogs with RSS feeds.I was wondering, if instead of discovering one blog at a time, I could discover five blogs at once, directly from my terminal!  Turns out the website has <https://indieblog.page/random> which picks a random blog and redirects you to it.  It has daily feeds of N random posts too, where N = 1, 3, 5, and 10.But if, like me, you'd like to have five random blogs suggested in your terminal, here is a quick shell one-liner I'd like to share.  It fetches the random blog picker page five times, cleans up the URLs a bit, and prints them on the terminal:for _ in $(seq 1 5); do curl -sSI https://indieblog.page/random | grep location | sed 's/location: \(.*\).utm_source=.*/\1/'; doneOr if you want something to go in ~/.zshrc, ~/.bashrc, etc., then you could have a tiny shell function like this:iw5() {
      for _ in $(seq 1 5)
      do
          curl -sSI https://indieblog.page/random |
              grep location |
              sed 's/location: \(.*\).utm_source=.*/\1/'
      done
  }Here is an example output:$ iw5
  https://justinsimoni.com/colorado-trail-24-hour-backpacking-challenge-in-may-how-far-can-i-hike/
  http://www.iamcal.com/2024-09/10218/
  https://dracos.co.uk/wrote/advent-of-code-2024-7/
  https://leancrew.com/all-this/2024/12/mind-your-plotting/
  http://i.never.nu/personal-foundational-texts/It helps me to quickly browse through a set of random suggestions on the terminal, decide which one I want to visit, right click on it, and select the "open link" option to open the link in a web browser.  Yes, I know this amounts to judging a post by its link, but sometimes the post slug (if present) alone sparks enough curiosity to dive deeper, and it's a quick way to explore new posts without overthinking it.If you're using this, please be considerate of the indieblog.page web server.  Avoid running it too frequently to prevent putting unnecessary strain on the server.
https://news.ycombinator.com/item?id=43141368
When I was learning to build websites in 2010 Dreamweaver was the go-to. I remember it thoroughly confused the heck out of me. Anyone here able to use it effectively?
https://news.ycombinator.com/item?id=43149437
My Current Job is a Mess—But I Won’t Let It Define Me(Disclaimer: Not here to trash my company, just sharing my experience.)I work on the AI team at my current job, meaning I get to play with cutting-edge generative AI tech. I’ve built some pretty cool things:
 • Designed an end-to-end image generation pipeline for a virtual friend app.
 • Implemented self-hosted Stable Diffusion with Automatic1111, adding sentiment-based image optimization & image retrieval.
 • Used Vicuna (uncensored) + VLLM for serving our text model.Sounds exciting, right? That’s about where the good part ends.The Bad: A Tech Culture Stuck in the Stone AgeThe engineering practices at my company are, to put it mildly, nonexistent:
 • Testing? None. Even revenue-generating products (~$200K/yr) are tested manually.
 • Deployments? Manual SSH into the server, copy the build, and pray.
 • CI/CD? What’s that?
 • Docker/Kubernetes? Not in our vocabulary.
 • Code Quality? Negative.I’ve tried pushing for better practices—heck, I even gave a Docker session to the team—but there’s no buy-in.The New Obsession: AI is Eating Our JobsManagement (none of whom are engineers) has fully bought into the “AI replaces devs” hype. Our CTO literally said:“Use GPT to write code. This is a one-day task; it shouldn’t take more than that.”They genuinely believe AI can replace skilled developers overnight. Meanwhile, they’ve never used GPT to write production code themselves. They just read the PR spin and assume it’s magic.Despite this chaos, I’ve refused to let the environment affect my growth. WFH helped me stay sane, but now that we’re back in the office, I know it’s time to move on.I never had a formal AI background, but I self-learned everything while on the job. Along the way:
 • Cleared GSoC and worked on Intel’s ML toolkit OpenVINO (JS bindings).
 • Discovered OpenTensor (decentralized intelligence), cold-emailed a contributor, and worked part-time on his startup.
 • Got my Rust PR accepted into Docify (used by Polkadot).
 • Built a Rust + HTMX startup backend using Rocket (signed an NDA, so can’t share details).What’s Next?I’m scrambling to find a new job. Ideally, I’d love to work on FOSS full-time rather than jumping into another corporate dev job. The problem? Finding an opportunity that matches my current compensation in India.I recently worked a contract gig for $17.35/hr—if I had a year-long commitment at that rate, I’d have left my job yesterday.I know going full-time into FOSS isn’t easy, but if you have advice—or know FOSS projects that need contributors—I’d love to connect.My stack:
 • Frontend: React / Next.js / TypeScript
 • Backend: Node.js / FastAPI / Flask
 • GenAI: LangChain, RAG, Stable Diffusion, Tool-Calling
 • DevOps: (Self-learning)I’m in a phase where I can afford to push myself to maximize my learning, but I also need to be practical. If you’ve been through something similar or have insights on making a sustainable career in FOSS, I’d love to hear from you.Thanks for reading—I appreciate any thoughts, advice, or connections!
https://news.ycombinator.com/item?id=43138523
Hey!I know this is a question we're not usually discussing here on HN but I'm sure some of you have at least once in their life experienced lucid dreaming if not practicing regularly.Would be fun to hear about your experiences. I'm not actively practicing now but should pick it up again (it was a lot of fun).What I always emphasise when talking about LD's this: it's REAL. It's a full virtual reality experience not only with visuals and sounds but with taste, touch, and emotions, too.I'm putting together a small report called The State of Lucid Dreaming 2025. Here are 9 questions if you'd like to participate:
https://dreamvr.co/stats/questionsAnd here are the preliminary results:
https://dreamvr.co/stats
Warning: 'div' element with class 'toptext' not found for link: https://news.ycombinator.com/item?id=43166405
https://news.ycombinator.com/item?id=43166405
Hey!I know this is a question we're not usually discussing here on HN but I'm sure some of you have at least once in their life experienced lucid dreaming if not practicing regularly.Would be fun to hear about your experiences. I'm not actively practicing now but should pick it up again (it was a lot of fun).What I always emphasise when talking about LD's this: it's REAL. It's a full virtual reality experience not only with visuals and sounds but with taste, touch, and emotions, too.I'm putting together a small report called The State of Lucid Dreaming 2025. Here are 9 questions if you'd like to participate:
https://dreamvr.co/stats/questionsAnd here are the preliminary results:
https://dreamvr.co/stats
https://news.ycombinator.com/item?id=43138540
I am wondering if there are any online communities(discord, slack, forums) for people who have single-handedly built and run their online businesses - AND it is not a cesspool of never-ending promos and garbage ads ala linkedin?
https://news.ycombinator.com/item?id=43087383
This is a serious question because I'll be the first to admit, I'm not a great business person. Also genuinely not trying to just promote my software either, but looking for some advice and feedback.I recently built and launched Forms.md, which is an open source JS library that lets you create multi-step forms and surveys. The forms themselves are very similar to what you would find on Typeform. The library works anywhere you can run JS, so it works with all web tech stacks: Django, Rails, React, Angular, etc. The library itself is just the front-end form builder, there is no backend because I expect people to just submit their forms directly to their database as that should be fairly easy to set up. It's also licensed under Apache-2.0.Website:https://forms.mdRepo:https://github.com/formsmd/formsmdSome backstory, this was initially known as blocks.md, and I was charging for a one-time license under BUSL. But that version was quite difficult to use because it only worked with Markdown files.This time, I'm charging around $25/month in order to remove the branding. Everything else is completely free. Now this is the part I struggle with: I feel like the quality of the software is quite high and so is the output. But can this be an actually viable business model? I have really thought about just making it entirely free (even the branding removal) and just seeing it grow, but I would love to make some money from this and potentially even do this full-time (God willing). I spent months building this, and I constantly keep on doubting myself on what to do. I even hesitated to launch for 2 weeks because I was really anxious.Any honest feedback on this? Could I actually make this into a company or do I need to start adding more features like backend, integrations, etc.? I'm kinda burned out at the moment, just left my day-job, so it's all a bit of a mess really. If anyone has any advice, I'm all ears. My email is also on my profile.Some other questions:- Should I go back to charging a one-time fee?- How do I even reach out to potential customers/users?
https://news.ycombinator.com/item?id=43162490
AI is an exciting technology that is surely changing the world. But I would love to know if anyone is building non AI stuff in 2025. At least not primarily AI.
https://news.ycombinator.com/item?id=43084739
This should be interpreted in the broadest sense to include books like both American Kingpin and Practical Vim as examples.
https://news.ycombinator.com/item?id=43132313
Recently I tried playing with https://www.cursor.com/ but got spooked by the LuLu alert (https://objective-see.org/products/lulu.html) when launching the app, where the process args included "JSON.stringify(process.env)" part, see screenshot here: https://imgur.com/a/DmDuGTzIs this... normal? I don't understand why they might want to serialize/access all of my env vars. Does anyone have a suggestion for that behaviour? I'm probably missing some reasonable explanation, happy to learn more.I've been running a lot of stuff in VMs lately anyway, but don't want to end up having to spin up a VM for the core app like a code editor. How do you all deal with untrusted (but not really malware-level untrusted) software?
Warning: 'div' element with class 'toptext' not found for link: https://news.ycombinator.com/item?id=43158741
https://news.ycombinator.com/item?id=43158741
Recently I tried playing with https://www.cursor.com/ but got spooked by the LuLu alert (https://objective-see.org/products/lulu.html) when launching the app, where the process args included "JSON.stringify(process.env)" part, see screenshot here: https://imgur.com/a/DmDuGTzIs this... normal? I don't understand why they might want to serialize/access all of my env vars. Does anyone have a suggestion for that behaviour? I'm probably missing some reasonable explanation, happy to learn more.I've been running a lot of stuff in VMs lately anyway, but don't want to end up having to spin up a VM for the core app like a code editor. How do you all deal with untrusted (but not really malware-level untrusted) software?
https://news.ycombinator.com/item?id=43137645
This could also be called "How can I pitch myself for a job at a company for a position that does not exist?".Is there such a thing? Can anyone share any stories of how they got in contact with an acquiring company? Does it just become a job interview?
https://news.ycombinator.com/item?id=43137496
So this week, I was teaching a new employee about the system. He is 30 years old and has been in the industry for six years now. At one point, I described an external tool that we use, which produces an XML file. Something felt off about his questions, and then a realization hit me:"Do you know what XML is?"He didn't.I have a few takeaways:1. I'm old.
2. I envy him—I hate XML. 99% of the time, it actively sabotages my work.
3. JSON simplicity won.That's it. No moral.
https://news.ycombinator.com/item?id=43125486
What applications(as in use cases, not in software names) have you found for local LLMs that you use yourself on a daily basis, and which LLMs do you use?
https://news.ycombinator.com/item?id=43137171
Hi I'm Anqur, a senior software engineer with different backgrounds where development in C was often an important part of my work. E.g.1) Game: A Chinese/Vietnam game with C/C++ for making server/client, Lua for scripting [1]. 2) Embedded systems: Switch/router with network stack all written in C [2]. 3) (Networked) file system: Ceph FS client, which is a kernel module. [3](I left some unnecessary details in links, but are true projects I used to work on.)Recently, there's a hot topic about Rust and C in kernel and a message [4] just draws my attention, where it talks about the "Rust" experiment in kernel development:> I'd like to understand what the goal of this Rust "experiment" is:  If we want to fix existing issues with memory safety we need to do that for existing code and find ways to retrofit it.So for many years, I keep thinking about having a new C dialect for retrofitting the problems, but ofC itself.Sometimes big systems and software (e.g. OS, browsers, databases) could be made entirely in different languages like C++, Rust, D, Zig, etc. But typically, like I slightly mentioned above, making a good filesystem client requires one to write kernel modules (i.e. to provide a VFS implementation. I do know FUSE, but I believe it's better if one could use VFS directly), it's not always feasible to switch languages.And I still love C, for its unique "bare-bone" experience:1) Just talk to the platform, almost all the platforms speak C. Nothing like Rust's PAL (platform-agnostic layer) is needed. 2) Just talk to other languages, C is the lingua franca (except Go needs no libc by default). Not to mention if I want WebAssembly to talk to Rust, `extern "C"` is need in Rust code. 3) Just a libc, widely available, write my own data structures carefully. Since usually one is writing some critical components of a bigger system in C, it's just okay there are not many choices of existing libraries to use. 4) I don't need an over-generalized generics functionality, use of generics is quite limited.So unlike a few `unsafe` in a safe Rust, I want something like a few "safe" in an ambient "unsafe" C dialect. But I'm not saying "unsafe" is good or bad, I'm saying that "don't talk about unsafe vs safe", it's C itself, you wouldn't say anything is "safe" or "unsafe" in C.Actually I'm also an expert on implementing advanced type systems, some of my works include:1) A row-polymorphic JavaScript dialect [5]. 2) A tiny theorem prover with Lean 4 syntax in less than 1K LOC [6]. 3) A Rust dialect with reuse analysis [7].Language features like generics, compile-time eval, trait/typeclass, bidirectional typechecking are trivial for me, I successfully implemented them above.For the retrofitted C, these features initially come to my mind:1) Code generation directly to C, no LLVM IR, no machine code. 2) Module, like C++20 module, to eliminate use of headers. 3) Compile-time eval, type-level computation, like `malloc(int)` is actually a thing. 4) Tactics-like metaprogramming to generate definitions, acting like type-safe macros. 5) Quantitative types [8] to track the use of resources (pointers, FDs). The typechecker tells the user how to insert `free` in all possible positions, don't do anything like RAII. 6) Limited lifetime checking, but some people tells me lifetime is not needed in such a language.Any further insights? Shall I kickstart such project? Please I need your ideas very much.[1]: https://vi.wikipedia.org/wiki/V%C3%B5_L%C3%A2m_Truy%E1%BB%81n_K%E1%BB%B3[2]: https://e.huawei.com/en/products/optical-access/ma5800[3]: https://docs.ceph.com/en/reef/cephfs/[4]: https://lore.kernel.org/rust-for-linux/Z7SwcnUzjZYfuJ4-@infradead.org/[5]: https://github.com/rowscript/rowscript[6]: https://github.com/anqurvanillapy/TinyLean[7]: https://github.com/SchrodingerZhu/reussir-lang[8]: https://bentnib.org/quantitative-type-theory.html
https://news.ycombinator.com/item?id=43088935
You know, like in the movie "The Borrowers". Since we have human-sized bipedals now, it shouldn't be impossible to create miniture robots that would act like living beings, right?It would be amazing to have a small family of electric gnomes living with you. Doll house and everything. Kind of like real life Sims.So realistically, how complex would it be to scale it all down to five, seven inches? Any startups working on this?
https://news.ycombinator.com/item?id=43125655
I'm working on a service that targets mainly EU companies/businesses. I have either the option to get servicename.eu or euservicename.comI know the .com is king, and I always prefer to get .com for non-personal projects. However, I don't have much experience targeting primarily EU markets, so I'm not sure how common it is for EU businesses to be familiar with .eu domains.Can anyone share their experience with .eu domains? Is it as popular as .com for EU or just a niche TLD created for the sake of consistency?

In [ ]:
df3 = df3.dropna(subset=["Question"])

In [ ]:
comments_list = []

for link in df3["Link"]:
    r = requests.get(link)
    soup = BeautifulSoup(r.content, "html.parser")

    comments_element = soup.find("table", class_="comment-tree")
    if not comments_element:
        continue

    comments = comments_element.find_all("tr", class_="athing comtr")
    for comment in comments:
        c = comment.find("span", class_="comhead")

        user_element = c.find("a", class_="hnuser") if c else None
        user = user_element.get_text(strip=True) if user_element else "Unknown"

        age_element = c.find("span", class_="age") if c else None
        if age_element and "title" in age_element.attrs:
            age = age_element["title"]
            date_time_string = age.split()[0]
            try:
                datetime_object = datetime.fromisoformat(date_time_string)
                date = datetime_object.date()
                time = datetime_object.time()
            except ValueError as e:
                print(f"Error parsing datetime for {link}: {e}")
                date, time = None, None
        else:
            date, time = None, None

        text_element = comment.find("div", class_="comment")
        comment_content = text_element.get_text(strip=True) if text_element else "No content"

        print("Link:", link)
        print("Author:", user)
        print("Comment:", comment_content)
        print("Date:", date)
        print("Time:", time)
        print("-" * 30)

        comments_list.append({
            "Link": link,
            "Author": user,
            "Comment": comment_content,
            "Date": date,
            "Time": time
        })

comments_df = pd.DataFrame(comments_list)

Streaming output truncated to the last 5000 lines.
Time: 22:26:08
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: ivylee
Comment: Working on GrocerBird[1] where you upload a grocery receipt, it will parse all of the items and their prices, so you can keep track of grocery spending and prices over time. Please feel free to share your feedback and suggestions![1]:https://www.grocerbird.comreply
Date: 2025-02-24
Time: 18:03:37
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: jsemrau
Comment: I am still writing about Cognitive Agents on my Substack "Encyclopedia Autonomica" [1]. Last month I crossed 500 subscribers (~15 paying) on Substack and since today Google is properly indexing it.
Throughout February I wrote largely about applications in FinTech like Market Making, Agents as Financial Decision Engines, Advanced Named Entity Recognition, and that I built Deep Search for Finance in 2023 and nobody cared.[1]https://jdsemrau.substack.com/reply
Date: 2025-02-24
Time: 20:55:33
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: nileshtrivedi
Comment: Recently, I started building a crowdsourced wiki for repairability of consumer hardware products in India:https://isfixable.com/reply
Date: 2025-02-24
Time: 15:37:35
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: dbremner
Comment: I'm rewriting a suite of network applications from C++ to Rust as a learning exercise. It's a long obsolete and obscure protocol, so the results aren't particularly useful, but it's been a good introduction to the language.reply
Date: 2025-02-25
Time: 02:06:46
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: robviren
Comment: I've been trying to use genetic algorithms to evolve voice style tensors for Kokoro-82M TTS. My current main barrier is that the scoring function is powered by resemblyzer and whatever it is using to compare the audio data has limitations. The generated tensors over fit and make garbage sounding audio that scores high, but doesn't sound like voice. Considering alternate methods of scoring.reply
Date: 2025-02-24
Time: 14:37:02
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: halftheopposite
Comment: I’m creating an observability tool that I’m trying to make user-centric while staying developer friendly. Most of the tools for remote logging, live dashboards and alerts are either too big, too expensive, or have a “per seat” plan, and incorporate the famous “home” screen with metrics and tips you absolutely never care of. I’m also trying to stay cheap and focused on very few techs  (node, Postgres, docker, react) and make it stay as a monolith.So far I’ve put all the side projects I manage (5 of them) and it’s working great. I can follow and query the logs, the JSON payloads by path, see live metrics like number of users currently online, etc. Even if I don’t get any customers I’ll continue developing it for my own needs! Will soon be adding alerts through webhooks, slack, discord, etc.If you want to try it out:https://app.getboringmetrics.com(no landing page yet).Edit: just want to say that if you want to try the software but not keep it, you can create an account in under 10 seconds, send a curl request to see logs arrive in realtime, and delete your account in 5 seconds. I do not track anything and do not keep a single piece of data.reply
Date: 2025-02-24
Time: 13:24:23
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: jay-barronville
Comment: > Even if I don’t get any customers I’ll continue developing it for my own needs!That’s the spirit! A buddy of mine created a tool/API to solve his own problems, opened it to the public and launched it, but he got very few sign-ups, so he just continued to use it for himself. Recently, about two years later and out of nowhere (without doing anything other than the original bit of SEO he did), he started to see a bunch of sign-ups (including paid) and then started receiving feedback and support request emails from customers. Most folks would’ve just called it quits on the product at least a year ago, but he just kept using the product for his own projects and left it open to the public just in case it was helpful for anyone else. Obviously, YMMV, but good luck with this!I’m on mobile right now, but I think I’ll give it a try when I’m back at my computer.reply
Date: 2025-02-24
Time: 15:22:51
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: halftheopposite
Comment: That's so refreshing to hear to be honest! I've went on so many side projects hoping I would see adoption for months and was basically chasing the dream. However I've came to realize that I really take happiness in developing things sustainably over time, with small steps, and most importantly for myself and what I would like a product to look like. Lately I've even been able to onboard a friend on it using it for his own projects as well, couldn't be happier so far.If you ever have feedback/advices, don't hesitate to reach me out on contact[at]halftheopposite.dev and I'll happily answer.reply
Date: 2025-02-24
Time: 16:53:09
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: dm03514
Comment: I'm building a stream processing framework using DuckDB.https://github.com/turbolytics/sql-flowThe goal is to create a stream processing framework that supports SQL jobs. Apache Flink supports this but is very heavy-weight overall. I work with cost constrained companies that just can't run Flink but still want access to high performance streaming primitives.We are taking a slightly different approach from other competitors by building cloud-native tools for engineers. SQLFlow is built on DuckDB, Native Kafka Library, and Arrow. This allows SQLFlow to handle ~70k+ events / second with low memory overhead (~250MiB).Would love your questions, thoughts and feedback or feature Ideas! Thank youreply
Date: 2025-02-24
Time: 17:28:21
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: arcbyte
Comment: Interesting project. I'm working on a side project that is sort of adjacent but the user cases I'm targeting are fundamentally different from yours.I professionally have some projects where we are doing custom CDC from kafka -> dbms. In that context, we're just using spring boot apps. How is the troubleshooting/recovery story for sqlflow?reply
Date: 2025-02-24
Time: 18:15:30
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: dm03514
Comment: Very Cool! Which use cases are you targeting?I'm surprised at the relatively sparse state of streaming. I feel like there are:- Flink
- Spark
- ~Benthos
- Arroyo
- Then mostly custom / bespoke frameworksMaybe there just isn't that much money in it? But I think there's still lots of opportunity to improve the Dev/UX over the JVM and the enterprise solutions.-----I would say recovery is achieved through kafka consumer groups right now, which results in at least once processing semantics.We also support websocket input for the bluesky firehose but that is completely ephemeral. I have a story in the backlog to write ahead to disk which should allow for tolerating process crash/failure.The tumbling windows stores state using duckdb. The end user can configure a disk-based duckdb databases which achieves durability as well.The troubleshooting was actually pretty funky, i didn't realize how tricky it could be with stateful stream processing. I certainly don't have a good story for it, but what I did was added a sql debug HTTP handler. When this is enabled it exposes the duckdb execution context over HTTP. This was how I debugged the tumbling window logic during development. I would start SQLFlow, query to make sure the windows were empty, send some known messages, query the windows to make sure they were aggregated correctly, wait for the windows to close and flush, query the tumbling window state, etc.For troubleshooting it also supports prometheus metrics oriented towards stream processing, # of messages, processing duration, success/failures, etc.SQLFlow also ships with a dev framework, this allows you to execute your sqlflow pipeline against a json input file to make sure the sql processing logic is correct. I wanted to give the ability to decouple testing the logic, from actually having to stream data.I would love to know about more what you're hacking on!reply
Date: 2025-02-24
Time: 20:04:52
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: arcbyte
Comment: This may be outside your use case for sql flow, but in my professional work we have a lot of problems with malformed messages or weird data in the target DB. So only 95% of message succeed in effecting their updatupdated. Leads to a lot of troubleshooting what happened, what was the message, what was the data at the time we processed the message, what did we expect to happen, etc.reply
Date: 2025-02-25
Time: 03:24:24
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: continuational
Comment: Firefly is a typed full stack programming language:- object capabilities- implicit async/await- immutable collectionshttps://www.firefly-lang.org/It's small and (hopefully) fun, and quite usable already. If you try it out, please share your thoughts!reply
Date: 2025-02-24
Time: 06:16:14
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: tealpod
Comment: Firefly language looks simple and beautiful.reply
Date: 2025-02-24
Time: 13:10:48
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: continuational
Comment: Thank you!reply
Date: 2025-02-24
Time: 14:17:43
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: hbroadbent
Comment: I've been building Tailcolors lately, a TailwindCSS color palette:https://tailcolors.comJust recently actually I published a Chrome extension for it too, so you can access and copy all the Tailwind CSS colors directly from an extension:https://chromewebstore.google.com/detail/tailcolors-tailwind...reply
Date: 2025-02-24
Time: 08:32:40
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: lukevp
Comment: I’m working on a cross-platform fast multithreaded HTTP / FTP downloader that will download much more quickly than other clients like FileZilla, hash check files, perform follow up operations (like extracting RARs or deleting files on the remote,) and have a nice graphical UI that runs in the browser and allows local/remote/cloud control. It’s early (started last week) so there’s not much done yet, but if you’re interested, would love a star or watch:https://github.com/lukevp/Speedfulreply
Date: 2025-02-24
Time: 06:15:03
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: p0deje
Comment: I'm working on Alumnium (https://alumnium.ai). It's an open-source library to simplify web application testing with Selenium/Playwright.I aim to create a stable and affordable tool that allows me to eliminate most of the support code I write for web tests (page objects, locators, etc.) and replace it with human-readable actions and assertions. These actions and assertions are then translated by an LLM into browser instructions. The tool, however, should still leverage all existing infrastructure (test runner, CI/CD, Selenium infrastructure).So far, it's working well on simple websites (e.g., a calculator, TodoMVC), and I'm currently working on scaling it to large web applications.reply
Date: 2025-02-24
Time: 15:14:04
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: cmdtab
Comment: Pretty cool. I built my own framework to do something similar very recently.Microsoft omni parser and claude computer use alone can take you very far in testing almost anything.reply
Date: 2025-02-24
Time: 15:20:51
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: p0deje
Comment: I experimented with Computer Use and even though it's pretty cool, I ended up not using it for 2 main reasons:1. It's unreasonably expensive. A single test "2+2=4" for a web calculator costs around $0.15. I run roughly 1k tests per month on CI and I don't want to spend $150 on those. The approach I took with Alumnium costs me $4 per month for the same amount of tests.2. It tries too hard to make the test pass even when it's not possible. When I intentionally introduced bugs in applications, Computer Use sometimes pretended the everything was fine and marked the test passed. Alumnium on the other hand attempts to fail as early as possible.reply
Date: 2025-02-24
Time: 15:29:21
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: cmdtab
Comment: For the 1st point, I generate a script with hashed check points so next run is automated unless something changes in the UI to invoke AI. I make this possible by proxy wrapping playwright library so I can take over every method. Users use playwright like they always have but with one extra method called act.Omini parser lets you split section of the UI to hash and watch for changes that are relevant.For 2, can you give some examples?reply
Date: 2025-02-24
Time: 20:02:39
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: maxbond
Comment: Tangentially, I am glad to see this thread again, I was worried the idea was scrapped since I hadn't seen it in the last few months. For whatever it counts for, I like this idea and hope to see it continue.reply
Date: 2025-02-24
Time: 06:42:33
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: matty22
Comment: I'm working on a project to document all publicly accessible stained glass in North America. The tech itself isn't anything exciting (vanilla HTML/CSS/JS and using Bootstrap for UI).All the work is in collecting and entereing data and hopefully recruiting folks around the country to go to their local church/synagogue/mosque, government building, or glass shop/studio and taking photos and collecting information on glass pieces.Site is still a work in progress, but if anyone out there is interested you can find it here:https://www.stainedglassatlas.comreply
Date: 2025-02-24
Time: 16:25:20
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: kebsup
Comment: I'm working on an AI spaced-repetition flashcards app for learning vocabulary in foreign languages.https://vocabuo.comThe idea is to have srs flashcards, like Anki, but without the pain of creating example sentences, translations, images and audio.As a bonus, I've added the option to add vocabulary from ebooks, YouTube videos and websites.reply
Date: 2025-02-24
Time: 11:46:16
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: msoloviev
Comment: I'm working on a text editor (https://github.com/blackhole89/autopen/) that continuously analyses the buffer with a local LLM to compute token surprisal and generate candidate completions starting from any point, and switch back and forth between different ones by walking a tree structure. This is pretty different from the usual way people interact with LLMs, and has lots of interesting applications - for example, if you are using them to translate and don't like a particular word choice, you can "dig through" top alternatives on the spot or even insert your own.Applying the same approach to chain-of-thought reasoning gave me the feeling that I might be looking at a form of realistic UX for some sort of science-fiction neural AI augmentation - you can let the CoT run on and do its thing, but also interject at any point and insert a "thought" of your own, or go back and revise a thought you did not like, and then let it continue. Imagine such a stream hooked up with a two-way pipe into your phonological loop (https://www.sciencedirect.com/topics/psychology/phonological...- perhaps more attainable with existing tech).reply
Date: 2025-02-24
Time: 17:37:14
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: nickjj
Comment: I've been working onhttps://github.com/nickjj/plutus, it's a command line income and expense tracker. It's a zero dependency Python script that you can curl down.It generates reports to show you your numbers in a bunch of customizable ways, it generates these reports in less than a second and uses a single CSV file as your data source.I've gotten things to the point where I can do my books every quarter in about 5 minutes with complete accuracy since it supports importing arbitrary CSV files such as bank exports with a way to automate categorizing things in any way you see fit. I currently use it to track my income, business expenses and personal expenses.Basically I ran into issues using different finance tracking tools over the last decade which always made me feel unhappy to use those tools so I built Plutus with intent to resolve all of those issues I had and make me happy while using it.reply
Date: 2025-02-24
Time: 11:41:34
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: pizlonator
Comment: Making Fil-C more complete. Fil-C is a memory safe C implementation that can run a lot of stuff. I want to make it run even more stuff.Recently I landed C exceptions support (I didn’t know that was a thing but it is, look for attribute cleanup if you want to know more) and ifunc support.More info about the project here:https://github.com/pizlonator/llvm-project-delugeAnd a Linux/X86_64 binary release if you want to play with it:https://github.com/pizlonator/llvm-project-deluge/releases/t...reply
Date: 2025-02-24
Time: 14:50:28
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: koliber
Comment: Working with clients I realized that many companies lack basic monitoring and observability. E-commerce shops go down and no one notices. DBs do thousands of useless queries per minute. Emails stop sending silently.I’m building a tool to make monitoring setup a no-brainer. I’m talking about basic website monitoring setup in 5-seconds — literally.The problem is not a lack of tools. The existing tools are not even that complicated, but they still require too much thinking to set up.reply
Date: 2025-02-24
Time: 07:45:18
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: Gasp0de
Comment: So uptimerobot.com is complicated for you?reply
Date: 2025-02-24
Time: 09:39:56
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: koliber
Comment: Not for me.Apparently finding and setting up monitoring is too problematic for all of the people who are running their freshly-created startups and e-commerce shops without any monitoring.For someone who does not know HTTP from HTTPs or all the different kinds of probes, reading about them and making decisions about what to set up is a time investment. Complicated might be the wrong word.All you really need to do is to provide a domain name and an email address for alerts to get basic monitoring set up. My goal is to set up monitoring with zero decisions under 30 seconds.Getting pretty close with nixmonitor.comreply
Date: 2025-02-24
Time: 14:44:32
------------------------------
Link: https://news.ycombinator.com/item?id=43154065
Author: lennertjansen

In [ ]:
comments_df2 = pd.DataFrame(comments_list)

comments_df2.head()

,Link,Author,Comment,Date,Time
0,https://news.ycombinator.com/item?id=43154065,jtwaleson,I'm creating an infinite canvas that has all y...,2025-02-24,08:27:29
1,https://news.ycombinator.com/item?id=43154065,abakker,Man...If you built this for large mainframe co...,2025-02-24,16:39:33
2,https://news.ycombinator.com/item?id=43154065,Cthulhu_,On a smaller scale it reminds me of the origin...,2025-02-24,13:21:21
3,https://news.ycombinator.com/item?id=43154065,jtwaleson,Cool. My long-term vision for software develop...,2025-02-24,18:04:44
4,https://news.ycombinator.com/item?id=43154065,Cerium,Sometimes I daydream that we moved beyond text...,2025-02-24,22:00:45

In [ ]:
comments_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1072 entries, 0 to 1071
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Link     1072 non-null   object
 1   Author   1072 non-null   object
 2   Comment  1072 non-null   object
 3   Date     1072 non-null   object
 4   Time     1072 non-null   object
dtypes: object(5)
memory usage: 42.0+ KB

In [ ]:
df3.to_csv("questions1.csv", index=False)
comments_df2.to_csv("comments1.csv", index=False)

In [ ]:
merged_df = pd.concat([df2, df3]).drop_duplicates()
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 11
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          28 non-null     object
 1   User           28 non-null     object
 2   Relative time  28 non-null     object
 3   Date           28 non-null     object
 4   Time           28 non-null     object
 5   Score          28 non-null     int64
 6   Link           28 non-null     object
 7   Question       28 non-null     object
dtypes: int64(1), object(7)
memory usage: 2.0+ KB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, 0 to 29
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          24 non-null     object
 1   User           24 non-null     object
 2   Relative time  24 non-null     object
 3   Date           24 non-null     object
 4   Time           24 non-null     object
 5   Score          24 non-null     int64
 6   Link           24 non-null     object
 7   Question       24 non-null     object
dtypes: int64(1), object(7)
memory usage: 2.2+ KB

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 0 to 28
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          17 non-null     object
 1   User           17 non-null     object
 2   Relative time  17 non-null     object
 3   Date           17 non-null     object
 4   Time           17 non-null     object
 5   Score          17 non-null     int64
 6   Link           17 non-null     object
 7   Question       17 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.2+ KB

In [ ]:
merged_comments = pd.concat([comments_df, comments_df2])
merged_comments.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2144 entries, 0 to 1071
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Link     2144 non-null   object
 1   Author   2144 non-null   object
 2   Comment  2144 non-null   object
 3   Date     2144 non-null   object
 4   Time     2144 non-null   object
dtypes: object(5)
memory usage: 100.5+ KB

In [ ]:
comments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1072 entries, 0 to 1071
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Link     1072 non-null   object
 1   Author   1072 non-null   object
 2   Comment  1072 non-null   object
 3   Date     1072 non-null   object
 4   Time     1072 non-null   object
dtypes: object(5)
memory usage: 42.0+ KB

In [ ]:
merged_df.to_csv("merged_questions.csv", index=False)
merged_comments.to_csv("merged_comments.csv", index=False)