### Data Collection - Capture social media data from platforms (e.g., Twitter, Facebook, LinkedIn, YouTube) using APIs such as Twitter API v2, Facebook Graph API, and YouTube Data API, along with scraping and crawling techniques (e.g., BeautifulSoap, Selenium)

In [ ]:
import os
import pandas as pd
import re
import spacy
from nltk.stem import WordNetLemmatizer
import nltk

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
os.listdir("/content/drive/MyDrive/SMA_DATASET")
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
df_comments = pd.read_csv("/content/drive/MyDrive/SMA_DATASET/merged_comments.csv")
df_comments

,Link,Author,Comment,Date,Time
0,https://news.ycombinator.com/item?id=43154065,jtwaleson,I'm creating an infinite canvas that has all y...,2025-02-24,08:27:29
1,https://news.ycombinator.com/item?id=43154065,abakker,Man...If you built this for large mainframe co...,2025-02-24,16:39:33
2,https://news.ycombinator.com/item?id=43154065,Cthulhu_,On a smaller scale it reminds me of the origin...,2025-02-24,13:21:21
3,https://news.ycombinator.com/item?id=43154065,jtwaleson,Cool. My long-term vision for software develop...,2025-02-24,18:04:44
4,https://news.ycombinator.com/item?id=43154065,Cerium,Sometimes I daydream that we moved beyond text...,2025-02-24,22:00:45
...,...,...,...,...,...
2139,https://news.ycombinator.com/item?id=43125655,phillipseamore,Go with EU or a ccTLD(s) in Europe. If you are...,2025-02-21,10:22:18
2140,https://news.ycombinator.com/item?id=43125655,mytailorisrich,"Better to have the exact ""servicename"" name, s...",2025-02-21,09:49:46
2141,https://news.ycombinator.com/item?id=43125655,skwee357,"Unfortunately, servicename.com is not availabl...",2025-02-21,10:02:09
2142,https://news.ycombinator.com/item?id=43125655,iorrus,As someone based in the EU but an English spea...,2025-02-21,11:35:23
2143,https://news.ycombinator.com/item?id=43125655,mytailorisrich,".de is purely Germany, like .fr is France, ama...",2025-02-21,12:05:44

In [ ]:
comments_list = df_comments["Comment"]
comments_list.head()

0    I'm creating an infinite canvas that has all y...
1    Man...If you built this for large mainframe co...
2    On a smaller scale it reminds me of the origin...
3    Cool. My long-term vision for software develop...
4    Sometimes I daydream that we moved beyond text...
Name: Comment, dtype: object

In [ ]:
lemmatizer = WordNetLemmatizer()
new_comment_list =[]
stopwords = ['the', 'of', 'and', 'is','to','in','a','from','by','that', 'with', 'this', 'as', 'an', 'are','its', 'at', 'for']

In [ ]:
for i in comments_list:
  # lower case
  str = i.lower()
  # remove symbols
  str = re.sub(r'[^\w]', ' ', str)
  # tokens conversion
  words_list = str.split(' ')
  # Lemmatization
  lemma_lst=[]
  for x in words_list:
    if len(x) >=2:
      lemma_lst.append(lemmatizer.lemmatize(x))
  # Removing stop words
  words_without_stopwords = [ word for word in lemma_lst if word not in stopwords ]
  new_comment_list.append(' '.join(words_without_stopwords))
  words_list = []

In [ ]:
for i in range(5):
  print(comments_list[i])
  print(new_comment_list[i],"\n\n")

I'm creating an infinite canvas that has all your organization's code and documentation on it. If you zoom in, you can see the code, if you zoom out you see the big picture. By giving everything a place on the map, it becomes easier to figure out your way through the landscape and understand the systems. Different modes can you show you different things: code age, authorship (bus-factor, is the person still with the company etc), languages used, security issues. There's time-travel, think Gource for all software in your company, and maybe the most fun: a GeoGuessr for code. Select the repos for your team (or if you feel confident, of the entire org), you get a snippet and have to guess where it is. The plan is for LLMs + tree-sitter to analyze all the code and show relations to other systems, databases etc.I had the idea 2 years ago, but starting building in earnest 2 months ago. Spending all my time on it now, minus 3 or 4 days per week of earning money. Currently looking for a GTM/sales-oriented cofounder in NL.reply
creating infinite canvas ha all your organization code documentation on it if you zoom you can see code if you zoom out you see big picture giving everything place on map it becomes easier figure out your way through landscape understand system different mode can you show you different thing code age authorship bus factor person still company etc language used security issue there time travel think gource all software your company maybe most fun geoguessr code select repos your team or if you feel confident entire org you get snippet have guess where it plan llm tree sitter analyze all code show relation other system database etc had idea year ago but starting building earnest month ago spending all my time on it now minus or day per week earning money currently looking gtm sale oriented cofounder nl reply


Man...If you built this for large mainframe codebases, I think every outsourcing provider would use it. many of these apps have >1 yr parallel runs even when rewritten because there is so much dormant and seasonal code that it is very hard to be confident in the apples:apples functional comparison over any shorter timeline.reply
man if you built large mainframe codebases think every outsourcing provider would use it many these apps have yr parallel run even when rewritten because there so much dormant seasonal code it very hard be confident apple apple functional comparison over any shorter timeline reply


On a smaller scale it reminds me of the original concept of Light Table, which let go of the abstraction of individual files in favor of editing your code in a tree like structure. It's a shame this concept seems to have died out, I'd be curious about alternatives to plain file based UX.reply
on smaller scale it reminds me original concept light table which let go abstraction individual file favor editing your code tree like structure it shame concept seems have died out be curious about alternative plain file based ux reply


Cool. My long-term vision for software development would be to make a new programming environment that structures code in ASTs and stores it in a database rather than file based. However, that will have to come later. First this :)reply
cool my long term vision software development would be make new programming environment structure code asts store it database rather than file based however will have come later first reply


Sometimes I daydream that we moved beyond text files and had a format with a UUID per line.Version control could reliably track movement between files, we could identify copy and paste (and prompt when refactoring), and code coverage changes would be accurate.reply
sometimes daydream we moved beyond text file had format uuid per line version control could reliably track movement between file we could identify copy paste prompt when refactoring code coverage change would be accurate reply

In [ ]:
df_comments["Comment"] = new_comment_list
df_comments.head()

,Link,Author,Comment,Date,Time
0,https://news.ycombinator.com/item?id=43154065,jtwaleson,creating infinite canvas ha all your organizat...,2025-02-24,08:27:29
1,https://news.ycombinator.com/item?id=43154065,abakker,man if you built large mainframe codebases thi...,2025-02-24,16:39:33
2,https://news.ycombinator.com/item?id=43154065,Cthulhu_,on smaller scale it reminds me original concep...,2025-02-24,13:21:21
3,https://news.ycombinator.com/item?id=43154065,jtwaleson,cool my long term vision software development ...,2025-02-24,18:04:44
4,https://news.ycombinator.com/item?id=43154065,Cerium,sometimes daydream we moved beyond text file h...,2025-02-24,22:00:45

In [ ]:
df_comments.to_csv('/content/drive/MyDrive/SMA_DATASET/preprocessed_comments.csv')